### ISSUE TITLE
Would it be possible to add an argument to the optimization function?

### ISSUE THREAD

**Issue by juagudeloo** [JuliaNLSolvers/Optim.jl#1022]
I want to define a residual function (resid) that includes the weights (sig) and the data (data), to minimize Chi square (chi_sqr). For example

```
function resid(x, data, sig, params)

a = params[1]
b = params[2]

model(z) = a*exp(b*z)
residual = data - model(x)
chi_sqr = sum((residual./sig).^2)

return chi_sqr

end
```
Is there a way to pass `sig` y `data` through an argument in the `optim` function?

**Comment by longemen3000** [comment]
you could do:
```
f0 = x -> resid(x, data, sig, params)
optimize(f0, zeros(2), BFGS())
```

**Comment by pkofod** [comment]
Yes, the solution is to use a closure as @longemen3000 shows above. You can input parameters in NLSolvers.jl https://github.com/JuliaNLSolvers/NLSolvers.jl .
