### ISSUE TITLE
JuliaNLSolvers has only 1 member?

### ISSUE THREAD

**Issue by JeffFessler** [JuliaNLSolvers/Optim.jl#1025]
Hi @pkofod 
It is disconcerting that the [JuliaNLSolvers](https://github.com/JuliaNLSolvers) organization has only 1 member, or at least only 1 member that is publicly visible.  A topic that is as important and universal to numerical computing and Julia as Optimization would benefit from having a team of interested people helping out!
Just look at https://github.com/orgs/JuliaLinearAlgebra/people for comparison.
I would be willing to help out, and I am sure there are others too.

**Comment by pkofod** [comment]
Hm, it must be a privacy setting. I see 12 people though a few of them are not really active or never really were. It's possible to contribute even if you're not an org member. There are 96 contributors to Optim.jl including a few bots that do janitor work on packages. Open a PR or issue and I'll be happy to participate. If I don't see the contribution, feel free to ping/bump me here or on slack.
