### ISSUE TITLE
Not showing candidate solutions?

### ISSUE THREAD

**Issue by naveenpalli** [JuliaNLSolvers/Optim.jl#1047]
Optim version 1.7.6/ Julia 1.9.2 on Windows 10. Running the basic rosenbrock function and I don't see the candidate solution values just the final objective value. Something missing in my setup?

julia> rosenbrock(x) =  (1.0 - x[1])^2 + 100.0 * (x[2] - x[1]^2)^2
rosenbrock (generic function with 1 method)

julia> result = optimize(rosenbrock, zeros(2), BFGS())
 * Status: success

 * Candidate solution
    Final objective value:     5.471433e-17

 * Found with
    Algorithm:     BFGS

 * Convergence measures
    |x - x'|               = 3.47e-07 ≰ 0.0e+00
    |x - x'|/|x'|          = 3.47e-07 ≰ 0.0e+00
    |f(x) - f(x')|         = 6.59e-14 ≰ 0.0e+00
    |f(x) - f(x')|/|f(x')| = 1.20e+03 ≰ 0.0e+00
    |g(x)|                 = 2.33e-09 ≤ 1.0e-08

 * Work counters
    Seconds run:   0  (vs limit Inf)
    Iterations:    16
    f(x) calls:    53
    ∇f(x) calls:   53

**Comment by naveenpalli** [comment]
Looks like it is stored in result.minimizer as a Vector but not displayed. Closing this issue.

**Comment by grantbrown** [comment]
Note that this [doesn't match](https://julianlsolvers.github.io/Optim.jl/stable/#user/minimization/) the behavior in the documentation - might be worth updating or re-adding this to the output.
