### ISSUE TITLE
Typo on Optim.simplexer() function

### ISSUE THREAD

**Issue by gaston-fernandez** [JuliaNLSolvers/Optim.jl#1064]
Hi

There is a small typo on the function you provided to implement the initial simplex as in Matlab's `fminsearch` in the Nelder-Mead algorithm, in section ["Specifying the initial simplex"](http://julianlsolvers.github.io/Optim.jl/stable/#algo/nelder_mead/).

You defined the function:
```
function Optim.simplexer(A::MatlabSimplexer, initial_x::AbstractArray{T, N}) where {T, N}
    ...    
    for j = 1:n
        initial_simplex[j+1][j] += initial_simplex[j+1][j] == zero(T) ? S.b * initial_simplex[j+1][j] : S.a
    end
    ...
end
```

The typo is on the first argument of `Optim.simplexer()`: the first argument should be `S::MatlabSimplexer`.

**Comment by pkofod** [comment]
Oh, the S. Good catch. Thanks

**Comment by pkofod** [comment]
Wait, looking at the code this is actually correct and I havn't touched that file for four years. I wonder if the docs are not generated as they should on new tags.

**Comment by pkofod** [comment]
See this https://github.com/JuliaNLSolvers/Optim.jl/pull/819

**Comment by pkofod** [comment]
So it's correct on dev docs now after it built, but it looks like I have some cleaning up to do as the old docs code used a very old version of documenter https://julianlsolvers.github.io/Optim.jl/dev/algo/nelder_mead/

**Comment by pkofod** [comment]
docs are now running
