### ISSUE TITLE
Docs Latex expressions displays as raw 

### ISSUE THREAD

**Issue by paulxshen** [JuliaNLSolvers/Optim.jl#1067]
At least on Chrome

**Comment by paulxshen** [comment]
sorry nvm was on older version docs site returned by google

**Comment by pkofod** [comment]
Yeah, unfortunately an old version of the docs seems to be promoted by google search.. I will see if I can maybe add an "this is an old version of Optim" banner at the top?

**Comment by pkofod** [comment]
> > Yeah, unfortunately an old version of the docs seems to be promoted by google search.. I will see if I can maybe add an "this is an old version of Optim" banner at the top?
> 
> That'd be great, as the new version has a cleaner API and more algorithms

There seems to be a function to add it retroactively. I'll try to do that!
