### ISSUE TITLE
Optim.OptimizationState

### ISSUE THREAD

**Issue by nickbrady** [JuliaNLSolvers/Optim.jl#1101]
There seems to be some misalignment of the documentation with the Optim.OptimizationState:
https://docs.sciml.ai/Optimization/stable/API/optimization_state/

The fields in OptimizationState in the documentation are listed as follows:

Fields

    iter: current iteration
    u: current solution
    objective: current objective value
    gradient: current gradient
    hessian: current hessian
    original: if the solver has its own state object then it is stored here

but using the following code:
```julia
using Optim
println(fieldnames(Optim.OptimizationState))
```
gives
1: iteration
2: value
3: g_norm
4: metadata

**Comment by longemen3000** [comment]
Note that this package is `Optim.jl`, whereas the documentation points to `Optimization.jl`. If you check that package, it has the struct with the correct fields:
https://github.com/SciML/Optimization.jl/blob/e987377adc6c6687a6108e5691ffaa8dd30cf26c/src/state.jl#L15

**Comment by pkofod** [comment]
Where does Optim.jl point to Optimization? You are confusing the Optimization.jl documentation with this package I think.

**Comment by pkofod** [comment]
Looking at the link again, I agree with @longemen3000 that this is not an Optim.jl issue but an Optimization.jl issue (two different packages)., You may file an issue at Optimization.jl
