### ISSUE TITLE
When should we throw errors versus return a result that flags a potentially bad result?

### ISSUE THREAD

**Issue by johnmyleswhite** [JuliaNLSolvers/Optim.jl#263]
Continuing discussion in #261, we should decide when we will throw an error and when we will return a result with a no-convergence flag. One proposal was to avoid throwing errors for line search failures or other problematic states (e.g. non-descent directions) and instead return an object that has an internal flags that prevent direct access to results without checking their validity. Other options are to raise warnings but still return results or to continue throwing errors and not returning results.

**Comment by pkofod** [comment]
As far as I could understand, you main concern is that people write 
```julia
using Optim
...
result = optimize(f, inital_x)
my_function_that_depends_on_result(Optim.minimizer(result), other_vars...)
```
but if there's a line search error they don't realize that `optimize` didn't actually succeed. Maybe this is even true for `converged == false`.

My main thought was that there shouldn't be any `Error`s that halts `optimize` altogether. Instead it could break the while loop, and report to the user that: this is the trace I got, this is the value of `x`, and so on. We could then set a flag in `MultivariateOptimizationResults` that indicated if a field could easily be retrieved or not. Warnings are not going to be enough, as code might be run in a script where no one is monitoring the output.

The `unsafe`-api seems almost too much, but maybe it really *is* **important** to make sure that `Optim.minimizer(result)` does not simply give a (meaningless) answer in the non-convergence case.

**Comment by johnmyleswhite** [comment]
Sounds like we generally agree. To try to clarify what I was saying, here's how I see things:

* We should not throw errors as a way of indicating that the results of the optimization process might be wrong. But `optimize` can still throw errors: we just don't add additional errors beyond the basic ones that are intrinsic to Julia code (e.g. array bounds errors). It sounds like we fully agree on this point.

* We should not just warn people when their results are likely to be wrong. In particular, the API for accessing fields like the minimizer should not return a result that we know to be wrong. We could return vectors containing `NaN`, but it seems more informative to actually throw an error when we know the answer is suspect. From my perspective, this is equivalent to moving the errors we're currently throwing to a better place in the control flow: if we throw errors when you already have access to a results object, you can use trace information to debug things in a way that's generally impossible now.

I think the remaining question is whether you want to make it possible to access a potentially wrong minimizer at all given that the official API will block you from this. My fear is that without an API for doing this (which doesn't have to be something `unsafe_minimizer` to have the same effect), people will just revert to accessing the internal fields of a results object to find the stored minimizer. I don't think that's so bad, but it seems to undo the work you've done to replace field access operations with a real API. So providing a mechanism for accessing wrong results seems worth doing, although I could imagine doing it by, say, producing a new results object that has the "DO NOT USE" flag set to false instead of true. Then you didn't multiple functions: you use the existing API, but suddenly it won't error out.

Does that seem reasonable to you?

**Comment by mlubin** [comment]
For comparison, JuMP doesn't throw errors if the solver fails to converge, it just reports such in the solution status.

**Comment by tbreloff** [comment]
I like the idea of offloading errors to after an optimize loop, and I'll
put in a vote for the "unsafe" versions. It would be nice to have
consistency between the APIs and an easy way to use the unsafe version. I'd
rather not remember two distinct APIs, but rather one API that
has "unsafe_xxx" to match.

**Comment by Evizero** [comment]
FWIW I also think the `unsafe_` is a good idea. From an end user's perspective I don't like seeing `unsafe` in my code, so I usually feel compelled to add error checks to avoid that; that seems like a good thing.

**Comment by pkofod** [comment]
I'll have a go at the flag + `unsafe_`-solution.

**Comment by anriseth** [comment]
Can I just add that the outer optimization algorithms (I looked at LBFGS, GradientDescent) do not throw an error if they reach the maximum number of iterations, but just return the optimization result with all converged flags set to false. 

Linesearch, on the other hand, throws an error when it hits maximum iterations.

**Comment by johnmyleswhite** [comment]
I agree that we should not have the line searches ever throw errors, but they also need to return flagged results if they don't meet the line search criteria. We've never made a big effort to pull that code out, but I would really like to see us move towards having the line searches as a separate package one day since they could be useful without any of the other machinery in Optim.

**Comment by pkofod** [comment]
> I agree that we should not have the line searches ever throw errors, but they also need to return flagged results if they don't meet the line search criteria. We've never made a big effort to pull that code out, but I would really like to see us move towards having the line searches as a separate package one day since they could be useful without any of the other machinery in Optim.

This is a great idea! For example, NLsolve.jl uses our line search algorithms which is why it has Optim as a dependency. I also think DSGE.jl (or was it someone else) require Optim for the line search feature. Linesearch.jl or LineSearch.jl? :)

**Comment by johnmyleswhite** [comment]
Probably LineSearches.jl if we export a LineSearch type.

**Comment by pkofod** [comment]
Putting this here for reference https://github.com/iamed2/ResultTypes.jl

**Comment by pkofod** [comment]
That make be a good idea. In DiffEq-verse this is just a `retcode` field in the results type, but the `(res, err)` may actually be a good idea from  a pedagogical standpoint as well.

**Comment by ChrisRackauckas** [comment]
Why return the `err`? And does it make it type-unstable?

**Comment by afbarnard** [comment]
@ChrisRackauckas In Go, one cannot throw exceptions, so one must return errors [1,2]. All the errors in Go are organized into a hierarchy with a common supertype as are the errors in Julia (Python, Java, etc.). So choosing Go style for this situation could be done with type stability.

[1] https://golang.org/doc/effective_go.html#errors
[2] https://blog.golang.org/error-handling-and-go

**Comment by ChrisRackauckas** [comment]
Common supertype but not concrete type hence the instability.

**Comment by pkofod** [comment]
I don’t think it would have to be type unstable as it could just be a symbol or the same retcode type with different information. But then again, that info is already in the results type.

**Comment by pkofod** [comment]
I don't think we'll do anything beyond leaving it up to the users to check for convergence themselves from the results type.
