### ISSUE TITLE
Feature Request: Subplex

### ISSUE THREAD

**Issue by fisherc2** [JuliaNLSolvers/Optim.jl#272]
The subplex is a variant of the Nelder-Mead simplex method that is good for noisy functions and converges faster for some problems. An author of several Julia packages has a C implementation [here.](https://github.com/stevengj/nlopt/tree/master/subplex) This might be a good optimizer to add to the library.

**Comment by johnmyleswhite** [comment]
Translating that code into Julia would be make for a very nice PR.

**Comment by pkofod** [comment]
This is mentioned in #326 so closing this, as there is no plan here.
