### ISSUE TITLE
Naming conventions for absolute and relative tolerance parameters

### ISSUE THREAD

**Issue by gabrielgellner** [JuliaNLSolvers/Optim.jl#279]
I have been trying to get a consensus on the names for the absolute and relative tolerances in Base, see https://github.com/JuliaLang/julia/issues/17322 . I just noticed that `Optim.jl` seems to use `abs_tol` and `rel_tol` in some methods (`brent.jl` for example).

Is there any interest in trying to find one common naming convention for this?

**Comment by johnmyleswhite** [comment]
I would be very eager to do that, but it might be hard since we arguably need to expose both absolute and relative tolerances for all of the quantities we check: movement in values of `x`, movement in the values of `f(x)` and movement in the values of `f'(x)`.

**Comment by gabrielgellner** [comment]
Yeah the `f_tol` `x_tol` etc seem beyond the scope of this issue. Rather ones that are directly related like the Brent method `abs_tol`, and `rel_tol`. Though maybe the underscores are to keep everything in line with the previous method naming. I don't have a strong preference for the underscores one way or the other, but others might.

**Comment by pkofod** [comment]
Correct, we generally split variable names by underscores between "words". The style guide says

"functions are lowercase (maximum(), convert()) and, when readable, with multiple words squashed together (isequal(), haskey()). When **necessary**, use underscores as word separators." (my emphasis)

I guess we just think it is often necessary :)

**Comment by pkofod** [comment]
@gabrielgellner can you enlighten me; did anything ever happen here?

**Comment by gabrielgellner** [comment]
@pkofod sadly no. I have largely given up my excitement on this kind of issue ... and just no longer believe that the underscore naming is going to be consistent. That coupled with the my inexperience with setting up a working environment for Base in windows means I never went thru the full process to get the 3 letter change into Base :(. Feel free to close if you want.

**Comment by pkofod** [comment]
> sadly no. I have largely given up my excitement on this kind of issue ... and just no longer believe that the underscore naming is going to be consistent. That coupled with the my inexperience with setting up a working environment for Base in windows means I never went thru the full process to get the 3 letter change into Base :(. Feel free to close if you want.

Okay. If I have time for it, I might change it to `abstol` and `reltol` in base, and then make the corresponding transition here, so I'll leave it open.
