### ISSUE TITLE
Multiple f evaluations for same state

### ISSUE THREAD

**Issue by cortner** [JuliaNLSolvers/Optim.jl#282]
So far I only checked this for LBFGS, but I suspect this occurs throughout Optim: 

The call to line search is this:

``` julia
 alpha, f_update, g_update = mo.linesearch!(d, x, s, x_ls, g_ls, lsr, alphaguess, mayterminate)
f_calls, g_calls = f_calls + f_update, g_calls + g_update
```

Because the current gradient and objective are not passed in, this means that there is one extra evaluation in `linesearch!`, since in the main loop there is also a call 

``` juli
f_x = d.fg!(x, gr)
```

So I propose to change the `linesearch!` call  to something like 

``` juli
alpha, f_update, g_update = mo.linesearch!(d, x, s, f_x, gr, x_ls, g_ls, lsr, alphaguess, mayterminate)
```

In fact, one could also pass in `dphi0` (or pass this instead of `gr`) which is also recomputed in the linesearch.

This won't affect problems where a lot of work is spent in the line-search, but it will very much affect well-scaled (e.g. preconditioned) problems when solved with LBFGS where ideally the Wolfe conditions are checked and then returned without any evaluation.

I'll test this and post an update here.

**Comment by cortner** [comment]
@anriseth since you are maintaining `LineSearches` (??) it would be good to have your thoughts.

**Comment by KristofferC** [comment]
I have worked around this in NLsolve in a slightly ugly way: https://github.com/EconForge/NLsolve.jl/blob/e41f1701ffe7f2e7060b686f922a7ea15b4a3708/src/newton.jl#L82

Note that in:
https://github.com/EconForge/NLsolve.jl/commit/5fb93cf1aa767f471d672fc56ff9d6e260374ffd
and
https://github.com/EconForge/NLsolve.jl/commit/04ec307c3c6316c76225308f733f2968679eb2dd

this reduced the number of f and g calls significantly.

**Comment by cortner** [comment]
I've been wondering whether the line search interface is not very flexible right now and one should just pass the entire Optimisation State to the line search?

**Comment by KristofferC** [comment]
Could have something like

```
f_updated::Bool
g_updated::Bool
```

and then have each call to `f` or `g` set `f_updated`, `g_updated` to `true` respectively. Any move of the current point sets both these to `false`. If `f_updated` is true, a call to `f` will just return the last value.

**Comment by cortner** [comment]
So you want to put this logic into the implementation of the objective function. You'd then need to trace whether the state has changed, or, for each objective call compare the state argument with the state at which the objective was previously evaluated. That would be fairly easy to do. The counting of evaluations could then also be moved to the Objective.

**Comment by KristofferC** [comment]
Yeah, my idea is to to provide an interface such that the different algorithms don't need to think so much about what the thing they are calling are doing (if they will call `f` again in the start etc) while still not having unnecessary evaluations. 

Something conceptually like:


```jl
# Df keeps track of previous evaulation and if it is updated
type DifferentiableFunction{T}
    f::Function
    g!::Function
    fg!::Function
    prev_f::T
    prev_g::Vector{T}
    f_updated::Bool
    g_updated::Bool
end

# Evaluate returns prev value if updated
function evaluate_f(df::DifferentiableFunction, x)
    !df.f_updated && df.prev_f = df.f(x)
    return df.prev_f
end
    
function evaluate_g(df::DifferentiableFunction, x)
    !df.g_updated && df.prev_g = df.g(x)
    return df.prev_g
end        

# StateVector is like a normal vector except modifying it should
# set the updated state to false in the wrapped df
immutable StateVector{T} <: AbstractVector{T}
    df::DifferentiableFunction
    v::Vector{T}
end
# Implement abstract vector interface as normally except:
function Base.setindex!(v::StateVector, X, i...)
    v.f_updated = false
    v.g_updated = false
    v.v[i...] = X
end
```

**Comment by cortner** [comment]
I am confused where the `f_updated`, `g_updated` live?

**Comment by KristofferC** [comment]
In the `df` object.

**Comment by cortner** [comment]
But on `setindex!` the flags are set in `v`.

**Comment by KristofferC** [comment]
`v` is wrapping a `df`.

**Comment by cortner** [comment]
and each copy of the `x` would become a copy of the full `StateVector`?

That still leaves the potential issue of identical copies or trivial changes to the state vector that are flagged but shouldn't be. Would it really be so costly to just store the previously evaluated `x` in `df` and check whether it has changed on each function call?

**Comment by KristofferC** [comment]
Probably not (and it is exactly what I am doing in https://github.com/EconForge/NLsolve.jl/blob/e41f1701ffe7f2e7060b686f922a7ea15b4a3708/src/newton.jl#L88).

**Comment by KristofferC** [comment]
That is also easier, we just need to stop doing `df.f(x)` (which is a violation of abstraction in itself)) and do something like `evaluate_f(df, x)`.

**Comment by cortner** [comment]
Anyways, I like the idea very much in principle.

I've used it previously in another optimisation code where it worked very well. In that context the objectives are fairly expensive and a vecnorm(xprev,x,Inf) is really negligible.

**Comment by cortner** [comment]
I like the `evaluate` better as well than `df.f`.

**Comment by KristofferC** [comment]
However, I assume there should there be a separate `x_prev` for `f`, `g` and `h` since not all of these are updated at the same time.

**Comment by cortner** [comment]
That sounds like it is getting too complicated . . . what would be the use-case?

**Comment by KristofferC** [comment]
Because some algorithm might do:

```
modify!(x)
evaluate_f(df, x)
# call some function h(df, x)
# in h:
evaluate_fg(df, x)
```

Here we only want to recompute `g` but not `f`

Here we want to recompute `g`

**Comment by cortner** [comment]
fair enough. In that case that's getting a lot of extra storage? Maybe your flag idea was not so bad. I need to check again how this is handled in ASE.

**Comment by cortner** [comment]
I noticed, btw, that `hz_linesearch` and `cg` have the same problem but in a different way: `hz_linesearch` uses the previous f and slope, but after terminating it should have already evaluated f and g at the end-point, yet it does another evaluation of both later in `cg.j`.

(at least this is what it looks like for me)

**Comment by KristofferC** [comment]
I guess it would look something like:
https://gist.github.com/KristofferC/3f7c1dfaea622f9e93e4c91ee0530135

**Comment by KristofferC** [comment]
The state thing is much more intrusive. It makes much more sense in my opinion to try to completely hide everything about how `f` and co are computed inside `df`.

**Comment by cortner** [comment]
I would be very happy with your proposal. I was going to implement something very similar for my specific objective functions, but it hadn't occurred to me that this could just be done at the Optim.jl level. I think it is great.

**Comment by KristofferC** [comment]
What is good about it is that problems like: https://github.com/JuliaOpt/Optim.jl/pull/266#issuecomment-244565624 just go away without any need to think where things should be evaluated and what is calling what etc.

**Comment by KristofferC** [comment]
Instead of putting all these stuff into `df` we should probably have something that wraps a `df` instead. `df` is created too early to initialize things when it is contructed. The thing that wraps `df` is instead initialized at the start of the optimization run.

**Comment by anriseth** [comment]
The only information we should need to pass to a linesearch algorithm is
- current position,
- current function value,
- direction,
- a reference to the optimization type instance, or the objective (and its derivatives)

Here's one way to run things:
1. At 'x', the optimization algorithm calculates `fval` and a direction to move along
2. It calls a linesearch algorithm with the information above, potentially with a computed initial step length
3. The linesearch algorithm updates the step length until it is satisfied, and stores the new value of `x`, and `fval`
4. The outer optimization checks for convergence, given information from the linesearch
5. If not converged, it goes back to 1.

I like an approach where we update LineSearches.jl to have an API that stores a generic type like this:
```jl
type LineSearchData{T}
  x::Vector{T}
  xnew::Vector{T}
  fval::T
  fvalnew::T
  updatedirection::Vector{T}
  df/optimizer # Storage information from the outer solver, we may potentially only need a df type object
  lambda::T # Step length
  keeplambda::Bool # Decides whether to keep the previous lambda
  data # storage for the specific linesearch algorithm
end
```
It is an extension of the `LineSearchResults` type, but creating a more generic API for linesearch algorithms. I'm sure there are more information that can be put in this data type, like maximum iterations, minimum and maximum step lengths etc.

I would take some inspiration from the PETSc project in how we handle things here, see for example how they do this for nonlinear solvers (it's not the easiest to follow if you haven't looked at their codebase before):
- http://www.mcs.anl.gov/petsc/petsc-current/src/snes/impls/ls/ls.c.html#SNESNEWTONLS (Newton with line search)
- http://www.mcs.anl.gov/petsc/petsc-current/src/snes/linesearch/interface/linesearch.c.html#SNESLineSearchApply (Generic line search function, that calls underlying algorithms)
https://www.mcs.anl.gov/petsc/petsc-current/src/snes/linesearch/impls/bt/linesearchbt.c.html#SNESLINESEARCHBT (The BT linesearch algorithm)
https://bitbucket.org/petsc/petsc/src/5f4d30c4cedf6e880b7f2c0f74758cb70d3b4827/include/petsc/private/linesearchimpl.h?at=master&fileviewer=file-view-default#linesearchimpl.h-29 (The struct that contains all the generic information a linesearch type could need)

**Comment by cortner** [comment]
Some of this overhead would become superfluous though if we use KristofferC 's  suggestion to wrap a `df` object.

**Comment by anriseth** [comment]
I like the approach of creating `evaluate_` functions, they can also keep track of how many evaluations we do for different objects. If we want to separate out LineSearches to become independent of Optim.jl, I think KristofferC's proposed types should go in a separate package (to be used by e.g. NLSolve, Optim, and LineSearches).

I'm not sure which parts you mean will become superflous overheads in the `LineSearchType` though?

**Comment by pkofod** [comment]
Yes I think it is clear that er might need some sort of SolverBase package if we truly want to separate these things out. I am all for the evaluate/dispatch approach. SmoothOptimizers use obj and grad!  . Any reason to not just keep f,g!, etc? Is the evaluate part necessary?

**Comment by KristofferC** [comment]
I guess `f` and `g!` is ok if they are not exported.

**Comment by cortner** [comment]
In my view, if `df`, say` is of type `ObjectiveFunction` (or whatever), then 
```
df(x) = evaluate(df, x)   # computes f
grad(df, x)    # (or gradient) computes the gradient   (or in-place)
```

`obj(df)` feels like saying `objective(objective)`. For evaluating both, `eval_and_grad!` or something similar? 

`f, g!` feel a little too succinct, especially because `f` could be used as the value
`f = evaluate(df, x)`

**Comment by pkofod** [comment]
Should the fields be named f, nablaf and maybe nabla2f and then optim can define methods called g or grad or whatever and nlsolve can call them j or jac or..., and instead of the (Twice)DifferentialFunction we call it Objective instead of Function.

**Comment by cortner** [comment]
I went and checked how the other code I know does this (ASE) check-if-state-changed. In that code, there is only a single check whether the state has changed, and if it does then all properties (e.g. f, g) are deleted and recomputed when needed. I am not sure storing multiple copies is really needed. It just needs a flag on what has already been computed for the currently stored state.

**Comment by ahwillia** [comment]
> ```
type DifferentiableFunction{T}
    f::Function
    g!::Function
    fg!::Function
    prev_f::T
    prev_g::Vector{T}
    f_updated::Bool
    g_updated::Bool
end
```

Interesting. To me, it seems unnatural to have `prev_f`, `f_updated`, etc in here. To me it seems like these things should be in `state` -- which is already heavily used and passed around in https://github.com/JuliaOpt/Optim.jl/pull/277.

Does `prev_g` create another copy in addition to anything stored in `state`? Do twice differentiable functions carry around `prev_h`?

I only skimmed the discussion here sorry if I missed something.

**Comment by KristofferC** [comment]
It just made sense to me to encapsulate this in a "function object"  to hide away all those details from the algorithms.

**Comment by ahwillia** [comment]
But isn't this accomplished by `OptimizationState`?

**Comment by timholy** [comment]
The current function value and slope should/could be stored in `lsr`.

In terms of API, with fast anonymous functions in julia 0.5, I'd very much prefer to see the API go to one where you pass in a function `ϕ(α)` that returns either just the value or the value + slope. Line search is a 1-dimensional problem, so passing in all kinds of multidimensional state seems wrong.

**Comment by cortner** [comment]
I think that would be nice *as long as* gradients that are computed along the way are still stored as discussed above.

**Comment by pkofod** [comment]
This is fixed now, right @anriseth  ?

**Comment by anriseth** [comment]
It should be, yes.
