### ISSUE TITLE
Changes to DifferentiableFunction API

### ISSUE THREAD

**Issue by ahwillia** [JuliaNLSolvers/Optim.jl#287]
Now that PR https://github.com/JuliaOpt/Optim.jl/pull/266 looks nearly complete, I'm hoping we can revisit issue https://github.com/JuliaOpt/Optim.jl/issues/156 and a few other additions or changes I've been thinking about. I know @johnmyleswhite mentioned that he would like to change the API in the past (not sure if that was meant in a broader sense or not).

**Minor / Low Priority:**
- As I brought up in https://github.com/JuliaOpt/Optim.jl/issues/156 - I think it would be nice to switch the order of the arguments so that `fg!(x, storage)` becomes `fg!(storage, x)` (making the mutated argument come first seems more consistent with Julian conventions and autodiff packages).
- I kind of like changing the names to `OnceDifferentiable` and `TwiceDifferentiable` for brevity (and clarity in the case of `DifferentiableFunction` which is a bit ambiguous). This could be handled with a depwarn, but maybe isn't worth it. We could also consider merging these into a single type (see some options below)

**Higher Priority:**
- `DifferentiableFunction` and `TwiceDifferentiableFunction` should know about each other somehow. Some ideas:

``` julia
abstract AbstractDifferientiable
type OnceDifferentiable <: AbstractDifferentable ...  end
type TwiceDifferentiable <: AbstractDifferentiable ... end
```

``` julia
typealias Differentiable Union{OnceDifferentiable, TwiceDifferentiable}
```

``` julia
# Merge OnceDifferentiable and TwiceDifferentiable ?
# This could be a problem for dispatching on one vs the other. But there are tricks to fix it.
type Differentiable
    f::Function
    g!::Function
    fg!::Function
    h!::Function
end
# Constructor for a once differentiable function 
Differentiable(f, g!, fg!) = Differentiable(f, g!, fg!, (x,s)->error("Not implemented") )
```
- Specifying a differentiable function with autodiff options. The autodiff packages in Julia are coming along and I'd like the ability to do something along these lines:

``` julia
f(x) = ... # my objective function
DifferentiableFunction(f, method=:autograd) # uses AutoGrad.jl
DifferentiableFunction(f, method=:forward) # uses ForwardDiff.jl
DifferentiableFunction(f, method=:central_diff) # uses finite central differencing
```

I'm not attached to using symbols - we could also dispatch on types if that is preferred.

**Comment by anriseth** [comment]
Jest for reference, we also discussed some sort of unified solver API for relevant objective functions etc. in #282

**Comment by pkofod** [comment]
Some was introduced in #337, storage will be closed in a new PR, and has a separate issue.
