### ISSUE TITLE
OEP: function-objects should keep track of their own call counts

### ISSUE THREAD

**Issue by timholy** [JuliaNLSolvers/Optim.jl#305]
(OEP = Optim Enhancement Proposal) Rather than keeping track of `f_calls` and `g_calls` in the algorithm, it seems much cleaner to have `DifferentiableFunction` store these quantities, and every time you call `value(d, x)` and `gradient!(g, d, x)` the counters get updated. That way there is no chance you're not keeping track of each evaluation (e.g., #219).

**Comment by pkofod** [comment]
I agree, and I know others do as well. We've had other suggestions for `value` and `gradient!`, but I actually like both.

**Comment by pkofod** [comment]
I'd throw my time after this asap (as in asap, not open source work asap), but (and correct me if I'm mistaken) I've seen @johnmyleswhite oppose something similar earlier. Any opinions? If I remember correctly, you said you wanted to go in the opposite direction API wise. Care to elaborate? Or correct me?
