### ISSUE TITLE
Can I maximize a function using Optim.jl?

### ISSUE THREAD

**Issue by pranavtbhat** [JuliaNLSolvers/Optim.jl#308]
R provides the `maximum` keyword to make `optimze` maximize the input function instead of minimizing it. Can this be done using Optim.jl? 

Eg:

```R
f <- function(x) { x ^ 2 }
optimize(f, c(0,100), maximum=TRUE)
```

**Comment by johnmyleswhite** [comment]
No, this is not currently possible. For now you should minimize the negative of your function.

**Comment by pkofod** [comment]
Is this not what other packages do? Multiply the objective, gradient, and hessian with `-1`? I guess we could add it to `Options` if people really want it.

**Comment by johnmyleswhite** [comment]
R's `maximize` keyword is actually an alias for rescaling the whole problem by `-1`, but you can also rescale by other values using R's `fnscale` argument.

I think we should support this at some point.
