### ISSUE TITLE
Separate timing information for internal computations and end-user computations

### ISSUE THREAD

**Issue by johnmyleswhite** [JuliaNLSolvers/Optim.jl#361]
A lot of issues are opened against the Optim.jl repo that reflect performance problems in the code that users provide to `optimize`. We should consider showing how the time spent optimizing a function is split between (a) evaluating the function and (b) using function evaluations to select points at which to evaluate the function.

**Comment by pkofod** [comment]
This should be quite easy to implement with the changes in #337 . I'll see if I can wrap it up next week, I just haven't had any time to work on it lately. I agree it would be very valuable information to communicate, and the cost of doing it is very low. We could also consider if this should be explained in the documentation.

**Comment by anriseth** [comment]
Can be useful https://discourse.julialang.org/t/ann-timeroutputs-jl/2429

**Comment by pkofod** [comment]
I think Kristoffers example at discourse is fine, and as such I don't think we need to implement it IN Optim given how easy it is with timeit. Agree @johnmyleswhite ? We can of course put it in the docs as a debugging tip!

**Comment by johnmyleswhite** [comment]
Sure, that works. I think you should feel free to make all of these decisions without eliciting my input.

**Comment by pkofod** [comment]
I was simply asking you as an issue opener :) gotta keep the costumers happy
