### ISSUE TITLE
allow x_lower==x_upper in univariate optimization

### ISSUE THREAD

**Issue by tpapp** [JuliaNLSolvers/Optim.jl#376]
I wonder if it would be possible to make
```julia
optimize(x->x^2, 1.0, 1.0)
```
work, by simply returning the endpoint, the value, and indicating convergence. (would require modifying [brent.jl](https://github.com/JuliaNLSolvers/Optim.jl/blob/master/src/brent.jl#L37) and [golden_section.jl](https://github.com/JuliaNLSolvers/Optim.jl/blob/master/src/golden_section.jl#L36)).

It is a trivial change, but it would be consistent, and would allow me not to special-case a parametric problem `optimize(f, a, b)` when `a==b`.

If you think this would be acceptable, I would submit a PR.

**Comment by pkofod** [comment]
Go ahead :)

**Comment by tpapp** [comment]
PR #377.

**Comment by pkofod** [comment]
closed by #377
