### ISSUE TITLE
V1.0.0

### ISSUE THREAD

**Issue by pkofod** [JuliaNLSolvers/Optim.jl#382]
When some of the open PRs and issues are closed soon (constrained optimization excluded...), I would like to entertain the thought of tagging Optim as v.1.0.0  the next time we tag.

The old rule of "no v1.0.0 tags before JuliaLang" is gone, and other packages are already > v1.*, and to be honest, this package is as official as it gets. It's got >200 stars, it's bundled with JuliaPro, and it really is the standard `fminunc`/`fminsearch`/`optim` for Julia.

Crossing the v1.0.0 barrier will allow us to use proper semantic versioning, and this really is helpful for us as developers. It allows us to more clearly communicate what types of updates we're throwing out there, and when we're adding features and changing user facing things.

In the end, it's not a big deal. It's just a version number. But it does carry some weight communication wise, so I at least wanted to see if anyone had any objections. Though, I'm rather set on doing it, so it would have to be valid objections (guess who's the judge).

**Comment by pkofod** [comment]
todo

- [ ] add "welcome message" on `using Optim` that warns about the changes to the argument order of `g!` and `h!`
- [ ] add `optimize` methods that of the form `optimize(f, [g!, h!], ::AbstractObjective, method, options)` that is *no* `initial_x` (just go off of what was used to initialize `*Differentiable`.

**Comment by anriseth** [comment]
If it doesn't cause too much mess, can we try to get #411, #414 and https://github.com/JuliaNLSolvers/NLSolversBase.jl/pull/10 (with appropriate version tag) in Optim 1.0.0?

**Comment by pkofod** [comment]
Waiting on https://github.com/JuliaLang/METADATA.jl/pull/9616 https://github.com/JuliaLang/METADATA.jl/pull/9603 https://github.com/JuliaNLSolvers/LsqFit.jl/pull/51

**Comment by Nosferican** [comment]
Waiting for the re-write for `v1.0.0`?

**Comment by pkofod** [comment]
I expect to tag v1.0.0 just before releasing the re-write, and then releasing the re-write as v2.0.0 . This way I'll be able to fix some stuff on v1.0.0 (the old code) if necessary, and it might be a bit easier for people to transition -  since some things will be significantly different from an API point of view.

**Comment by fredrikekre** [comment]
Nice.

**Comment by johnmyleswhite** [comment]
Congrats!
