### ISSUE TITLE
Functionality to check whether gradient and hessian is correct

### ISSUE THREAD

**Issue by anriseth** [JuliaNLSolvers/Optim.jl#386]
I think it can be useful to add a gradient and hessian checker (possibly to NLSolversBase). 
The idea is to make it easy for users to check whether their hardcoded (or autodiff'ed) derivatives give similar values to a finite difference approximation.

I've found this useful before to debug large simulators where my input functions are complicated. 
My inspiration is from PETSC:
http://www.mcs.anl.gov/petsc/petsc-current/docs/manualpages/SNES/SNESTEST.html

**Comment by pkofod** [comment]
Base seems like the place to do it!

**Comment by cortner** [comment]
I already do that for all my codes. Having an "official" implementation in Optim or NLSolversBase would be great. How do you determine whether the test has passed?

**Comment by anriseth** [comment]
> I already do that for all my codes. 

Is it in a general form that can be merged easily?:)

> How do you determine whether the test has passed?

I had in mind the sup-norn and some user defined tolerances. Then if the test fails, it's up to the user to decide whether it is a problem with the derivative calculations, or inaccuracy of the for difference.

**Comment by cortner** [comment]
What I do is that I check that the error over a range of fd parameters decreases by at least 3 orders of magnitude. But this is still heuristic. I just wondered whether there is something more rigorous.

**Comment by pkofod** [comment]
I was thinking of a very simple version where the user provided values. It is basically a convenience function, nothing special. But we could of course allow users to enter a box to check in or something similar as well. But again, I think this belongs in a tools or base package, as it doesn't involve any optim code.

**Comment by cortner** [comment]
Have a look at [Testing.jl](https://github.com/libAtoms/JuLIP.jl/blob/master/src/Testing.jl). For  a general purpose implementation I would rewrite the hessian test as a jacobian test and also add the possibility of only perturbing a randomly selected subset of indices - this is be necessary for large or expensive objectives

**Comment by ngiann** [comment]
How about comparing the user supplied gradient to the gradient obtained by ForwardDiff and then report/return the maximum absolute deviation? i.e. maximum(abs(user_gradient - forwarddiff_gradient))

**Comment by anriseth** [comment]
> How about comparing the user supplied gradient to the gradient obtained by ForwardDiff

ForwardDiff may not work for all user-supplied functions, so I think finite differences should be the default. One could give the user an option for calculating them using Forward/ReverseDiff as well, so long as that adds any value.

**Comment by pkofod** [comment]
Moved the discussion to https://github.com/libAtoms/JuLIP.jl/issues/112

**Comment by pkofod** [comment]
Functionality will be found in https://github.com/cortner/DerivativeTests.jl
