### ISSUE TITLE
Do I need rescaling during the optimization?

### ISSUE THREAD

**Issue by misun6312** [JuliaNLSolvers/Optim.jl#393]
Hi guys,

I have 10-parameter space and try to optimize the function by using Fminbox with Momentum Gradient Descent like below.

```
d4 = DifferentiableFunction(LL_f,
                            LL_g!,
                            LL_fg!)

l = [0, 0, 0, -5, 5, -5, 0.01, 0.005, 0, 0]
u = [200, 200, 30, +5, 25, +5, 1.2, 0.7, 1, 1]

res = optimize(d4, params, l, u, Fminbox(); 
optimizer = MomentumGradientDescent, optimizer_o = Optim.Options(g_tol = 1e-12,
                                                                        iterations = 100,
                                                                        show_every = true,
                                                                        store_trace = true,
                                                                        extended_trace = true,
                                                                        show_trace = true))

```

I tried to cross validate the optimization results with many subsets of data and I got following plots of parameters, gradients and function values. 
All of the optimization has been converged with the f_converge option.

![grad_traces](https://cloud.githubusercontent.com/assets/5979740/24896009/062ba5ca-1e61-11e7-8055-69cdd4e4f7f4.png)
![f_traces](https://cloud.githubusercontent.com/assets/5979740/24896008/06298f9c-1e61-11e7-8d78-7c65ae9582d7.png)
![x_traces](https://cloud.githubusercontent.com/assets/5979740/24896010/062ddad4-1e61-11e7-9786-86b48045dd2d.png)

But I'm not sure that these optimizations are considering all parameters fairly.. Cause I can see that gradients are relatively big for param9 and param10, and not much changes of function values along the iteration.

Looking forward to hearing some advices! 
Thank you.

**Comment by pkofod** [comment]
Thank you for using Optim! I think you'll get better response over at https://discourse.julialang.org/c/domain/opt .

Best

**Comment by misun6312** [comment]
Okay thanks @pkofod I will check it out!
