### ISSUE TITLE
Complex optimization

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaNLSolvers/Optim.jl#438]
Right now, Optim does not support complex optimization (meaning optimize a function F: C^n -> R). Second-order is tricky to get right (because the Hessian cannot be represented as a complex matrix), but first-order should be pretty easy (one should just need to add some real() at appropriate places). This does require changing a bunch of type assertions, though. E.g. in NLSolversBase,

```julia
type OnceDifferentiable{T, Tgrad} <: AbstractObjective
    f
    g!
    fg!
    f_x::T
    g::Tgrad
    last_x_f::Array{T}
    last_x_g::Array{T}
    f_calls::Vector{Int}
    g_calls::Vector{Int}
end
```
is not correct: f_x (real) is not of the same type as last_x_f (complex)
(ref https://github.com/JuliaNLSolvers/Optim.jl/issues/399, which had similar problems).

Is there a proper Julian way of doing this? (I'm still feeling my way around the type system) I've tried a number of variations, none of which seems to work.

An alternative is for Optim to convert the problem to R^2n internally, and only convert back to compute f and g. This can be done without copy, and is the best option for second-order optimization (where the user has to provide the full 2n x 2n hessian in some way or another), but it's less nice.

**Comment by pkofod** [comment]
We can totally do this, and there is no good reason not to have it. A lot of what you see here is based on/limited by a) what the usual contributors use themselves or think is interesting, b) how much time they have to implement things. I love allowing people to use all sorts of inputs, but since I'm not using complex numbers myself, so from my point of view, it's just a problem in R^2N rather than C^N explicitly, but we should be able to do this; others have.

**Comment by ChrisRackauckas** [comment]
The problem is the differentiation tooling. If Calculus and ForwardDiff get support for complex this is easy.

**Comment by antoine-levitt** [comment]
It's not that trivial if you want to type annotate all the fields, see above. It's a similar story when implementing a manifold type or arrays of arrays. The operations are well defined, but creating temp arrays of the right kind and having concrete types is tricky (at least to me).

**Comment by pkofod** [comment]
Thanks :+1:
