### ISSUE TITLE
 no method matching Optim.NelderMeadState

### ISSUE THREAD

**Issue by grandemundo82** [JuliaNLSolvers/Optim.jl#444]
After evaluating the function at the initial test points, using Nelder-Mead algorithm, I get the following error. 

optimize(resid_p2,p2,NelderMead())

[57.6577, 1.33053, 3.35109, 5.4273, 4.58902, 12.1558, 6.68081, 13.7386, 10.3846]
`ERROR: MethodError: no method matching Optim.NelderMeadState(::Array{Float64,2}, ::Int64, ::Array{Array{Float64,2},1}, ::Array{Float64,2}, ::Array{Float64,2}, ::Array{Float64,2}, ::Array{Float64,2}, ::Array{Float64,2}, ::Array{Float64,2}, ::Array{Float64,1}, ::Float64, ::Float64, ::Array{Int64,1}, ::Float64, ::Float64, ::Float64, ::Float64, ::String)
Closest candidates are:
  Optim.NelderMeadState(::Array{T,N}, ::Int64, ::Array{Array{T,N},1}, ::Array{T,N}, ::Array{T,N}, ::Array{T,N}, ::Array{T,N}, ::Array{T,N}, ::Array{T,N}, ::Array{T,N}, ::T, ::T, ::Array{Int64,1}, ::T, ::T, ::T, ::T, ::String) where {T, N} at /Users/nicolas/.julia/v0.6/Optim/src/multivariate/solvers/zeroth_order/nelder_mead.jl:109
Stacktrace:
 [1] initial_state(::Optim.NelderMead{Optim.AffineSimplexer,Optim.AdaptiveParameters}, ::Optim.Options{Void}, ::NLSolversBase.NonDifferentiable{Float64}, ::Array{Float64,2}) at /Users/nicolas/.julia/v0.6/Optim/src/multivariate/solvers/zeroth_order/nelder_mead.jl:145
 [2] optimize(::NLSolversBase.NonDifferentiable{Float64}, ::Array{Float64,2}, ::Optim.NelderMead{Optim.AffineSimplexer,Optim.AdaptiveParameters}, ::Optim.Options{Void}) at /Users/nicolas/.julia/v0.6/Optim/src/multivariate/optimize/optimize.jl:17
 [3] optimize(::Tuple{#resid_p2}, ::Array{Float64,2}, ::Optim.NelderMead{Optim.AffineSimplexer,Optim.AdaptiveParameters}, ::Optim.Options{Void}) at /Users/nicolas/.julia/v0.6/Optim/src/multivariate/optimize/interface.jl:79
 [4] optimize(::Function, ::Array{Float64,2}, ::Optim.NelderMead{Optim.AffineSimplexer,Optim.AdaptiveParameters}) at /Users/nicolas/.julia/v0.6/Optim/src/multivariate/optimize/interface.jl:74`

**Comment by pkofod** [comment]
Could you provide a more complete example I can run? Thanks!

**Comment by grandemundo82** [comment]
@pkofod: thanks for replying. not sure how to give an example as the function I am trying to optimise is rather complicated. I could upload the entire project maybe. What I can say is that the examples in documentation work. And when I switched to LBFGS instead of Nelder-Mead. I get a different error.
`optimize(resid_p2,p2,LBFGS())`
returns
`ERROR: MethodError: no method matching finite_difference!(::#resid_p2, ::Array{Float64,2}, ::Array{Float64,2}, ::Symbol)
Closest candidates are:
  finite_difference!(::Function, ::Array{S<:Number,1}, ::Array{T<:Number,1}, ::Symbol) where {S<:Number, T<:Number} at /Users/nicolas/.julia/v0.6/Calculus/src/finite_difference.jl:105`

**Comment by pkofod** [comment]
So... `p2` is a matrix here? It would be great to know what `p2` was, and some idea about what `resid_p2` takes in and what it spits out

**Comment by pkofod** [comment]
Please open again if you're able to hack up something that we can work off of. Thanks

**Comment by yamaceng** [comment]
Hello. I am also having a similar problem
The code is as follows 
using Optim;
coeff1(B)=transpose(filey-hcat(ones(7352,1), total_data)*B);
coeff2(B)=filey-hcat(ones(7352,1), total_data)*B;
coeff3(B)=sum(abs(B));
lambda=0.1;
total_sum(B)=(coeff1(B)*coeff2(B))[1,1]+lambda*coeff3(B);
result = optimize(total_sum,zeros(1153,1), NelderMead());

The error is LoadError: MethodError: no method matching Optim.NelderMeadState(::Array{Float64,2}, ::Int64, ::Array{Array{Float64,2},1}, ::Array{Float64,2}, ::Array{Float64,2}, ::Array{Float64,2}, ::Array{Float64,2}, ::Array{Float64,2}, ::Array{Float64,2}, ::Array{Float64,1}, ::Float64, ::Float64, ::Array{Int64,1}, ::Float64, ::Float64, ::Float64, ::Float64, ::String)
where total_data  is a 7352x1152 matrice

**Comment by pkofod** [comment]
And what is filey? Please provide a full example that I can run, and show the full stack trace / error message. I'll be happy to help in that case

**Comment by pkofod** [comment]
Ah okay I see, there's already an issue about this already. Nelder mead can't take matrices, but it's fixable
