### ISSUE TITLE
Box minimization example not working

### ISSUE THREAD

**Issue by bshall** [JuliaNLSolvers/Optim.jl#449]
The Box minimization example from  http://julianlsolvers.github.io/Optim.jl/stable/user/minimization/#box-minimization gives the following:
```julia
using Optim
f(x) = (1.0 - x[1])^2 + 100.0 * (x[2] - x[1]^2)^2
function g!(storage, x)
    storage[1] = -2.0 * (1.0 - x[1]) - 400.0 * (x[2] - x[1]^2) * x[1]
    storage[2] = 200.0 * (x[2] - x[1]^2)
end
lower = [1.25, -2.1]
upper = [Inf, Inf]
initial_x = [2.0, 2.0]
optimize(OnceDifferentiable(f, g!), initial_x, lower, upper, Fminbox{LBFGS}())
```
No default objective type for Optim.Fminbox{Optim.LBFGS}() and (Optim.UninitializedOnceDifferentiable{Void}(f, g!, nothing), [2.0, 2.0], [1.25, -2.1]).

But if I construct the `OnceDIfferentiable` as follows `OnceDIfferentiable(f, g!, initial_x)` it works fine.

**Comment by pkofod** [comment]
> No default objective type for Optim.Fminbox{Optim.LBFGS}() and (Optim.UninitializedOnceDifferentiable{Void}(f, g!, nothing), [2.0, 2.0], [1.25, -2.1]).
> 
> But if I construct the OnceDIfferentiable as follows OnceDIfferentiable(f, g!, initial_x) it works fine.

Good catch, that should have had the `initial_x` in there.

**Comment by pkofod** [comment]
Thanks.
