### ISSUE TITLE
Missing docstrings

### ISSUE THREAD

**Issue by pkofod** [JuliaNLSolvers/Optim.jl#469]
We still need docstrings for:

- [x] Fminbox
- [x] NewtonTrustRegion
- [x] SimulatedAnnealing
- [x] ParticleSwarm
- [x] NelderMead

The other doc strings should be plenty inspiration if you're in doubt of what a doc string should contain for these types/constructors.

**Comment by brilhana** [comment]
Up for grabs? I can work on this.

**Comment by anriseth** [comment]
> Up for grabs? I can work on this.

Yes, that would be very helpful :))

**Comment by pkofod** [comment]
@brilhana  It would be super appreciated! You can look at the existing ones for inspiration (I'm in Greece so I'm not on Github too much, but please just post a PR and we'll review!

**Comment by ViralBShah** [comment]
Seems like some of these are added. Worth updating the issue?

**Comment by pkofod** [comment]
Yeah, it's actually just Fminbox. Should add that.
