### ISSUE TITLE
Support for complex numbers

### ISSUE THREAD

**Issue by maartenvd** [JuliaNLSolvers/Optim.jl#470]
I was wondering if there is any support for complex optimization problems. I have a function that takes in an array of complex128s and returns a Float64. Ideally I'd like to minimize that function with the input constrained on a sphere. I'm using ~master (Manifold undefined when using Pkg.add).

The naive call
```
julia> Optim.optimize(tofun,x0,Optim.LBFGS(manifold=Optim.Sphere))
ERROR: TypeError: Type: in typeassert, expected Optim.Manifold, got Type{Optim.Sphere}

```
returns this error, for most solvers (except neldermead, where it complains that eps(Complex128) is undefined, that's easily worked around but also results in the following error). Without manifolds I get 

`ERROR: MethodError: no method matching Optim.NelderMeadState(::Array{Float64,2}, ::Int64, ::Array{Array{Float64,2},1}, ::Array{Float64,2}, ::Array{Float64,2}, ::Array{Float64,2}, ::Array{Float64,2}, ::Array{Float64,2}, ::Array{Float64,2}, ::Array{Float64,1}, ::Float64, ::Float64, ::Array{Int64,1}, ::Float64, ::Float64, ::Float64, ::Float64, ::String)`

The LBFGS solver tries to compare a complex number to a float (isless float,complexfloat) and after temporarily defining that function it runs into inexacterrors (like most other solvers)

Is it at all possible to do what I want or is this package still experimental (I'm on julia 0.6, should I rollback to an earlier version?)

Thanks a lot in advance

**Comment by pkofod** [comment]
You also need to checkout NLSolversBase until we tag Optim! Great to hear you're using this new feature.

**Comment by pkofod** [comment]
If that's not the problem, please post a full MWE

**Comment by maartenvd** [comment]
So I was definitely doing some things wrong, but still no dice.
Pkg.status() :

>  - NLSolversBase                 3.0.0+             master
>  - Optim                         0.9.3+             master 

Julia version 0.6.0

```
using Optim
testfun(x)=abs(x[1]+x[2])
manif=Optim.Sphere() #I previously forgot the ()
Base.eps(::Type{Complex128})=1e-12 #temporary workaround
Optim.optimize(testfun,[1.0im,1.0im],Optim.ConjugateGradient(manifold=manif))
```

now remove the "im" and everything works perfectly fine.

**Comment by maartenvd** [comment]
As an aside, packaging the complex numbers as 2-float64s produces very nice
results. Though it does appear that neldermead ignores the manifold argument

2017-10-02 19:57 GMT+02:00 Patrick Kofod Mogensen <notifications@github.com>
:

**Comment by pkofod** [comment]
Can you post your flattened version? Ie 2xFloat64

**Comment by maartenvd** [comment]
So this is what I do now: 

```
using Optim
using IterTools
unpack(t) = map(x->x[1]+1im*x[2],partition(t,2))
testfun(x)=abs(unpack(x)[1]+unpack(x)[2])
manif=Optim.Sphere() #I previously forgot the ()

res=Optim.optimize(testfun,[1.0,1.0,1.0,1.0],Optim.NelderMead(manifold=manif))
println(norm(Optim.minimizer(res)))

```

but if it's fixed by providing my own gradient (still have to try that out) then that would be a much nicer solution (unpack only works here because I'm working on a sphere)

**Comment by maartenvd** [comment]
Providing my own gradient works. I still don't quite understand how that
works though, shouldn't I also be providing the complex derivative? After
all, my function is really a function of f(z,conj(z)).

2017-10-03 15:38 GMT+02:00 Patrick Kofod Mogensen <notifications@github.com>
:

**Comment by maartenvd** [comment]
It is of course entirely possible to keep working with 2float64s, but then
the gradient becomes quite complicated and every manifold (aside from the
sphere) defined on the real numbers will correspond with something
completely different when packing the real vector back to complex numbers.

2017-10-04 9:08 GMT+02:00 maarten van damme <maartenvd1994@gmail.com>:

**Comment by pkofod** [comment]
I suspect @antoine-levitt has something more intelligent to say on these matters than I do, so I am summoning him!

**Comment by anriseth** [comment]
Does ForwardDiff and/or ReverseDiff work with complex functions? I
understand that there are problems where finite differencing is the easiest
go-to solution, but autodiff could be helpful in many cases.

**Comment by antoine-levitt** [comment]
As far as I know, complex variables don't work with either forward/reverse diff or finite differencing. There's a bunch of open issues on all these repos. It doesn't seem it's a fundamental issue, just that someone has to roll up their sleeves and do it.

```
Providing my own gradient works. I still don't quite understand how that
works though, shouldn't I also be providing the complex derivative? After
all, my function is really a function of f(z,conj(z)).
```
It's a function from complex to real, so you can define the gradient as a vector in C^n, as done in http://julianlsolvers.github.io/Optim.jl/latest/algo/complex/. It's not the same notion of derivative as for a complex-to-complex mapping (non-trivial map from C to R are not holomorphic).

Both complex and manifold stuff are a very recent addition, and as far as I know you're the second user of both features, so it's great to hear it's useful! Any feedback (reports of convergence/non-convergence, issues, PRs) much appreciated.

Nelder-Mead is not supported for manifolds (I wonder if it can be extended to a manifold) and should error out with a Manifold argument.

(also for packing and unpacking, see NLSolversBase.real_to_complex/complex_to_real)

**Comment by maartenvd** [comment]
Oh no, I did not see http://julianlsolvers.github.io/Optim.jl/latest/algo/complex/ .

Providing my own gradient works, ConjugateGradient converges while stayin on the Sphere() and the results are really nice. Thanks for this package.
