### ISSUE TITLE
type promotion confusion

### ISSUE THREAD

**Issue by bhawkins** [JuliaNLSolvers/Optim.jl#472]
My program crashed when optimizing a function that returns a scalar Float64 when given a vector of Float32. It's not obvious why this would be a problem. Somehow it gets called with vector of Int64 after the first call. I get a similar error with the following simple example
```
julia> using Optim
julia> f(x)::Float64 = mean(abs.(x))
julia> optimize(f, Float32[1, 1])
ERROR: StackOverflowError:
Stacktrace:
 [1] NLSolversBase.NonDifferentiable(::Function, ::Float64, ::Array{Int64,1}, ::Array{Int64,1}) at /Users/bhawkins/.julia/v0.6/Optim/src/objective_types.jl:42 (repeats 39997 times)
```
If I change the function to `f{T}(x::Vector{T})::T = mean(abs.(x))` then it works.

I'm using Julia 0.6.0, Optim 0.9.3, on a Mac 10.11.6.

**Comment by anriseth** [comment]
This works for me on master:
- Optim master
- NLSolversBase master
- Julia 0.6.1

```jl
julia> using Optim
julia> f(x)::Float64 = mean(abs.(x))
f (generic function with 1 method)
julia> optimize(f, Float32[1, 1])
Results of Optimization Algorithm
 * Algorithm: Nelder-Mead
 * Starting Point: [1.0,1.0]
 * Minimizer: [8.987691e-9,2.9985152e-9]
 * Minimum: 5.993103e-09
 * Iterations: 62
 * Convergence: true
   *  √(Σ(yᵢ-ȳ)²)/n < 1.0e-08: true
   * Reached Maximum Number of Iterations: false
 * Objective Calls: 119
```

**Comment by pkofod** [comment]
I'll have a look when I'm at a computer, but we've sort of always assumed eltype(x) == typeof(f). Why is it you want float64 out when you put 32 in?

**Comment by bhawkins** [comment]
Thanks, it does seem to be fixed in the latest version using `Pkg.checkout`.

I don't have a really good reason for mixing types. My objective function just happened to involve some Float64 data so the return type got promoted, and I had a tough time figuring out what the problem was because the code was working fine a few months ago.

**Comment by pkofod** [comment]
Alright, no worries. I was just curious!
