### ISSUE TITLE
Citing Optim.jl

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaNLSolvers/Optim.jl#478]
I've found Optim.jl very useful in my work (it's possibly not the most mature or efficient optimization library in existence, but it's been flexible enough to allow me to modify it easily), and want to acknowledge it in a paper I'm writing. Is there a standard way to do that, or do I just put up a link to the github page?

**Comment by ChrisRackauckas** [comment]
Optim.jl should sign up for Zenodo: https://guides.github.com/activities/citable-code/

Other than that, JORS offers guides: https://openresearchsoftware.metajnl.com/about/#q11

That's enough for Google Scholar to catch it at least.

**Comment by anriseth** [comment]
I have currently just cited the github repo. 

Zenodo sounds useful, and maybe we should write a short article for JORS or similar in prep for Optim/Julia 1.0?

**Comment by ChrisRackauckas** [comment]
JORS is a little more involved. But a quick paper is JOSS (http://joss.theoj.org/about). It's like 1 page paper is the only thing that's required, and the rest that's reviewed is your repo. That's something to think about.

**Comment by pkofod** [comment]
Good question @antoine-levitt and thanks for spreading the word! I will figure out a way. Is this work you're submitting soon? Then probably the best we can do is to go the zenodo route, though JOSS could be interesting as well.

**Comment by ChrisRackauckas** [comment]
both JOSS and JORS require that you sign up for Zenodo, so I'd just do that now.

**Comment by antoine-levitt** [comment]
Soon-ish (~1 month?) There's absolutely no hurry, I can change the citation later on, but Zenodo looks very nice.

**Comment by pkofod** [comment]
Alright, I'll create a zenodo...thing.

**Comment by pkofod** [comment]
I believe there's one now in the readme https://github.com/JuliaNLSolvers/Optim.jl

**Comment by antoine-levitt** [comment]
Looks good! I look forward to citing "JuliaNLSolvers/Optim.jl: Minor changes to README.md and some dots" ;-)

**Comment by ChrisRackauckas** [comment]
Generally you cite the package and authors + the DOI, but not the specific version title haha

**Comment by pkofod** [comment]
I'm not going to tag anything for the next month just to be sure that you include the release title, haha!

**Comment by anriseth** [comment]
I can try to submit Optim to JOSS this week, or would anybody prefer that we wait for particular features (e.g. #303 or Julia 1.0)? I assume we could write something more substantial in JORS later on.

**Comment by ChrisRackauckas** [comment]
I can swap out Calculus for DiffEqDiffTools probably in the next week and then you can probably tout full complex support. Has the array support been abstracted here as well or is it still indexing?

**Comment by ChrisRackauckas** [comment]
DiffEq is published and its benchmarks use Optim all throughout the parameter estimation portion. In particular, Google Scholar shows that this article used DiffEq + Optim for studying parameter estimation:

https://www.biorxiv.org/content/early/2018/01/25/254003

**Comment by anriseth** [comment]
Thanks @ChrisRackauckas, I've included the references:)

**Comment by cortner** [comment]
Ive got two where the algorithms were prototyped in Julia but then reimplemented in Python (don’t ask) so used Optim implicitly. I’ve got two more that used Optim directly - but since they are analysis papers the don’t really talk about the code at all. If useful I can postage references here later. (I’m on my phone)

**Comment by anriseth** [comment]
@cortner yes, please do. (I'll decide whether it makes sense to include them tomorrow)

**Comment by pkofod** [comment]
> Using Pptim in the background:
> H. Chen and C. Ortner. QM/MM methods for crystalline defects. Part 2: Consistent energy and force-mixing. Multiscale Model. Simul., 15(1), 2017
> J. Braun, M. Buze, and C. Ortner. The effect of crystal symmetries on the locality of screw dislocation cores. ArXiv e-prints, 1710.07708

For these, I guess the real question is if it was of any advantage to you, or was it "just" because you were already using Julia? I mean if it was because it was easy to experiment with line searches or something like that, then it'd be cool to know (so we can mention it).

**Comment by cortner** [comment]
I needed the preconditioning which was very convenient to add. Without it the simulations would have been very difficult to eun

**Comment by cortner** [comment]
final reference: Preconditioners for the geometry optimisation and saddle point search of molecular systems, L Mones, G Csanyi and C Ortner, submitted.

**Comment by anriseth** [comment]
> final reference: Preconditioners for the geometry optimisation and saddle point search of molecular systems, L Mones, G Csanyi and C Ortner, submitted. 

I can't this anywhere online?

**Comment by cortner** [comment]
It isn’t :). I’ll ask my co-authors whether they are happy to post it.

On 8 Mar 2018, 17:13 +0000, Asbjørn Nilsen Riseth <notifications@github.com>, wrote:

final reference: Preconditioners for the geometry optimisation and saddle point search of molecular systems, L Mones, G Csanyi and C Ortner, submitted.

I can't this anywhere online?

**Comment by anriseth** [comment]
> It isn’t :). I’ll ask my co-authors whether they are happy to post it.

Ah, I was afraid my Googling skills had suffered a severe blow there. 
I assume we can add more references in the JOSS summary article after the reviewers have given us feedback on the code, so it's probably no rush ;)

**Comment by anriseth** [comment]
There's now a JOSS article to cite, in case anyone feels like doing so :smiley: 
http://joss.theoj.org/papers/10.21105/joss.00615

I guess the BiBTeX will look something like this,
```tex
@article{mogensen2018optim,
  author  = {Mogensen, Patrick Kofod and Riseth, Asbj{\o}rn Nilsen},
  title   = {Optim: A mathematical optimization package for {Julia}},
  journal = {Journal of Open Source Software},
  year    = {2018},
  volume  = {3},
  number  = {24},
  pages   = {615},
  doi     = {10.21105/joss.00615}
}
```
