### ISSUE TITLE
Deprecated warnings

### ISSUE THREAD

**Issue by bicycle1885** [JuliaNLSolvers/Optim.jl#490]
I often see deprecated warnings like below:
```
WARNING: `alphainit` is deprecated, use `InitialHagerZhang()` instead
WARNING: `alphatry` is deprecated, use `InitialHagerZhang()` instead
```

I think these are harmless but a little bit annoying.
Any plan to release a patched version of Optim.jl?

I'm using Optim.jl v.0.10.1 and LineSearches.jl v3.2.1.

**Comment by anriseth** [comment]
Until a new Optim release is out, you can use `master` if you wish. `Pkg.checkout("Optim")`

**Comment by bicycle1885** [comment]
Yeah, I do that. But I feel a little bit uncomfortable to do that on all computers I'm using and not to forget getting them back in the future. I thought you noticed the warnings but just in case.

**Comment by pkofod** [comment]
It shouldn't be a problem to make a new release (tomorrow).
