### ISSUE TITLE
Extract final DiffResult

### ISSUE THREAD

**Issue by simonbyrne** [JuliaNLSolvers/Optim.jl#493]
I want to use `TwiceDifferentiable`, but at the end I need not only the value, but also the gradient and hessian. Is there a way I can get a `DiffResult` containing all 3?

**Comment by pkofod** [comment]
You want a container with a copy of the objective, gradient and Hessian? You can get the most recent objective, gradient and Hessian as
```
NLSolversBase.value(df)
NLSolversBase.gradient(df)
NLSolversBase.hessian(df)
```
but the Hessian evaluation is skipped at convergence. To be sure you could do
```
res = optimize(df, ...)
minimizer = Optim.minimizer(res)
NLSolversBase.value(df, minimizer)
NLSolversBase.gradient!(df, minimizer)
NLSolversBase.hessian!(df, minimizer)
```
and it will only re-calculate the various objects of interest if `minimizer` wasn't the last `x` used for evaluation.

So are you asking for something like
```
module Optim

...

struct DiffResults
   fx
   gx
   Hx
   x
end
function DiffResults(df, res)
    minimizer = Optim.minimizer(res)
    NLSolversBase.value(df, minimizer)
    NLSolversBase.gradient!(df, minimizer)
    NLSolversBase.hessian!(df, minimizer)
    DiffResults(NLSolversBase.value(df), NLSolversBase.gradient(df)
                      NLSolversBase.hessian(df), x)
end

NLSolversBase.value(dr::DiffResults) = dr.fx
NLSolversBase.gradient(dr::DiffResults) = dr.gx
NLSolversBase.hessian(dr::DiffResults) = dr.Hx
...

end
```
?

**Comment by anriseth** [comment]
@simonbyrne Could there be an advantage to supporting https://github.com/JuliaDiff/DiffResults.jl within the `*Differentiable` objects?

**Comment by simonbyrne** [comment]
> @simonbyrne Could there be an advantage to supporting https://github.com/JuliaDiff/DiffResults.jl within the *Differentiable objects?

Yes, something like that is what I had in mind.

**Comment by pkofod** [comment]
I don't know the details but I'll have a look.
