### ISSUE TITLE
Optimization stopping with negative |f(x)-f(x')|

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaNLSolvers/Optim.jl#497]
This is the show_trace I get:

```
Iter     Function value   Gradient norm 
     0     1.518564e+00     7.737399e+00
     1     1.257971e+00     5.188361e+00
     2     1.300479e-01     1.925981e+00
Results of Optimization Algorithm
 * Algorithm: BFGS
 * Starting Point: [0.3,0.2,0.1,2.0]
 * Minimizer: [0.4831715754998279,0.27568785340049273, ...]
 * Minimum: 1.300479e-01
 * Iterations: 2
 * Convergence: true
   * |x - x'| < -1.0e+00: false 
     |x - x'| = 7.51e-01 
   * |f(x) - f(x')| / |f(x)| < -1.0e+00: true
     |f(x) - f(x')| / |f(x)| = -1.30e+00 
   * |g(x)| < -1.0e+00: false 
     |g(x)| = 1.93e+00 
   * Stopped by an increasing objective: false
   * Reached Maximum Number of Iterations: false
 * Objective Calls: 11
 * Gradient Calls: 11
```

Note the `|f(x) - f(x')| / |f(x)| = -1.30e+00`!

Call sequence is
`
td = OnceDifferentiable(x -> obj(x),x_init; autodiff = :finite)
result = optimize(td,x_init,BFGS(),Optim.Options(x_tol=-1.0,g_tol=-1.0,f_tol=-1.0,iterations=100,show_trace=true)) #, show_every = 5),
`
Happens on latest master. The code is a bit involved, but I can send if needed.

**Comment by pkofod** [comment]
> Happens on latest master.

Can you qualify this - is it *only* on master, or did you just only *check* master?

**Comment by antoine-levitt** [comment]
I checked and got the same behavior on Pkg.add() version and on master.

**Comment by pkofod** [comment]
I'll check it later. @anriseth suggested some changes to the logic here so he might know what's up

**Comment by anriseth** [comment]
See if this is fixed in my PR? (I'm in Cuba with very restricted internet
access at the moment, so can't check much myself)

**Comment by pkofod** [comment]
Uhm, what about `f_tol = 0.0` @antoine-levitt ?

**Comment by antoine-levitt** [comment]
f_tol = 0.0 does not produce this bug, and it's also fixed in @anriseth's PR. Good job!

**Comment by pkofod** [comment]
anriseths pr is merged so I'll close it. I'll tag a new version quite soon
