### ISSUE TITLE
Pkg.test("Optim") fails

### ISSUE THREAD

**Issue by finmod** [JuliaNLSolvers/Optim.jl#498]
On returning to Optim after a while, Pkg.test("Optim") fails with Julia 0.6 on Windows
_
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.1 (2017-10-24 22:15 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> Pkg.test("Optim")
INFO: Testing Optim

WARNING: deprecated syntax "abstract Optimizer" at C:\Users\Denis\.julia\v0.6\Optim\src\types.jl:2.
Use "abstract type Optimizer end" instead.

WARNING: deprecated syntax "abstract OptimizationResults" at C:\Users\Denis\.julia\v0.6\Optim\src\types.jl:65.
Use "abstract type OptimizationResults end" instead.
WARNING: Compat.ASCIIString is deprecated, use String instead.
  likely near C:\Users\Denis\.julia\v0.6\Optim\src\types.jl:66
WARNING: Compat.ASCIIString is deprecated, use String instead.
  likely near C:\Users\Denis\.julia\v0.6\Optim\src\types.jl:66
WARNING: Compat.ASCIIString is deprecated, use String instead.
  likely near C:\Users\Denis\.julia\v0.6\Optim\src\types.jl:84
WARNING: Compat.ASCIIString is deprecated, use String instead.
  likely near C:\Users\Denis\.julia\v0.6\Optim\src\types.jl:84
ERROR: LoadError: LoadError: UndefVarError: ASCIIString not defined
Stacktrace:
 [1] include_from_node1(::String) at .\loading.jl:576
 [2] include(::String) at .\sysimg.jl:14
 [3] include_from_node1(::String) at .\loading.jl:576
 [4] include(::String) at .\sysimg.jl:14
 [5] anonymous at .\<missing>:2
while loading C:\Users\Denis\.julia\v0.6\Optim\src\problems\unconstrained.jl, in expression starting on line 10
while loading C:\Users\Denis\.julia\v0.6\Optim\src\Optim.jl, in expression starting on line 96
ERROR: LoadError: Failed to precompile Optim to C:\Users\Denis\.julia\lib\v0.6\Optim.ji.
Stacktrace:
 [1] compilecache(::String) at .\loading.jl:710
 [2] _require(::Symbol) at .\loading.jl:497
 [3] require(::Symbol) at .\loading.jl:405
 [4] include_from_node1(::String) at .\loading.jl:576
 [5] include(::String) at .\sysimg.jl:14
 [6] process_options(::Base.JLOptions) at .\client.jl:305
 [7] _start() at .\client.jl:371
while loading C:\Users\Denis\.julia\v0.6\Optim\test\runtests.jl, in expression starting on line 5
================================[ ERROR: Optim ]================================

failed process: Process(`'C:\Users\Denis\AppData\Local\Julia-0.6.1\bin\julia.exe' -Cx86-64 '-JC:\Users\Denis\AppData\Local\Julia-0.6.1\lib\julia\sys.dll' --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=yes --compilecache=yes 'C:\Users\Denis\.julia\v0.6\Optim\test\runtests.jl'`, ProcessExited(1)) [1]

================================================================================
ERROR: Optim had test errors

julia>

**Comment by pkofod** [comment]
Can you please post the output of Pkg.status()?

**Comment by finmod** [comment]
Here it is:

julia> Pkg.status()
29 required packages:
 - BlackBoxOptim                 0.3.0+             master
 - CUDAdrv                       0.7.1
 - Cairo                         0.4.0
 - Conda                         0.7.1
 - DiffEqPhysics                 0.1.0
 - DifferentialEquations         3.0.2
 - Documenter                    0.12.4
 - DynamicDiscreteModels         0.0.3
 - DynamicalSystems              0.7.0
 - Fontconfig                    0.1.1
 - FreqTables                    0.1.0
 - GLM                           0.8.1
 - GR                            0.24.0
 - Gadfly                        0.6.4
 - IJulia                        1.6.2
 - Ipopt                         0.2.6
 - JLD                           0.8.3
 - JuMP                          0.18.0
 - Knet                          0.8.5
 - LeastSquaresOptim             0.4.0
 - MAT                           0.4.0
 - Measurements                  0.5.0
 - Optim                         0.4.7              master
 - Plots                         0.14.1
 - PyCall                        1.15.0
 - PyPlot                        2.3.2
 - RDatasets                     0.2.0
 - Sundials                      0.17.1
 - Winston                       0.13.1
141 additional packages:
 - AlgebraicDiffEq               0.1.0
 - AutoGrad                      0.0.9
 - AxisAlgorithms                0.2.0
 - BandedMatrices                0.3.1
 - BinDeps                       0.8.1
 - Blosc                         0.3.0
 - BoundaryValueDiffEq           0.1.0
 - BufferedStreams               0.3.3
 - CPUTime                       0.0.5
 - CUDAapi                       0.2.1
 - Calculus                      0.2.2
 - ChunkedArrays                 0.1.1
 - CodecZlib                     0.4.1
 - ColorTypes                    0.6.6
 - Colors                        0.8.2
 - Combinatorics                 0.5.0
 - CommonSubexpressions          0.0.1
 - Compat                        0.39.0
 - Compose                       0.5.4
 - Contour                       0.4.0
 - CoupledFields                 0.0.1
 - DataArrays                    0.6.2
 - DataFrames                    0.10.1
 - DataStructures                0.7.3
 - DelayDiffEq                   1.2.1
 - DiffBase                      0.2.0
 - DiffEqBase                    2.6.2
 - DiffEqBiological              0.3.0
 - DiffEqCallbacks               0.4.0
 - DiffEqDevTools                0.11.3
 - DiffEqDiffTools               0.0.2
 - DiffEqFinancial               0.3.0
 - DiffEqJump                    0.6.0
 - DiffEqMonteCarlo              0.9.1
 - DiffEqNoiseProcess            0.7.2
 - DiffEqPDEBase                 0.3.5
 - DiffEqParamEstim              0.7.1+             master
 - DiffEqSensitivity             0.3.0
 - DiffEqUncertainty             0.0.1
 - DimensionalPlotRecipes        0.0.2
 - Distances                     0.5.0
 - DistributedArrays             0.4.0
 - Distributions                 0.15.0
 - DivSigGrad                    0.0.0-             master (unregistered)
 - DocStringExtensions           0.4.1
 - DualNumbers                   0.3.0
 - EikonalInv                    0.0.0-             master (unregistered)
 - EllipsisNotation              0.3.0
 - FWI                           0.0.0-             master (unregistered)
 - FactoredEikonalFastMarching   0.0.0-             master (unregistered)
 - FileIO                        0.6.1
 - FiniteElementDiffEq           0.4.0
 - FixedPointNumbers             0.4.3
 - ForwardDiff                   0.5.0
 - ForwardHelmholtz              0.0.0-             master (unregistered)
 - FunctionWrappers              0.1.0
 - GZip                          0.3.0
 - GenericSVD                    0.1.0
 - Graphics                      0.2.0
 - HDF5                          0.8.8
 - Hexagons                      0.1.0
 - Hiccup                        0.1.1
 - IniFile                       0.3.1
 - Interpolations                0.7.2
 - IterTools                     0.2.0
 - IterativeSolvers              0.4.2
 - JSON                          0.16.3
 - Juno                          0.3.2
 - KernelDensity                 0.4.0
 - KrylovMethods                 0.4.0
 - LaTeXStrings                  0.3.0
 - LearnBase                     0.1.6
 - LegacyStrings                 0.3.0
 - LibExpat                      0.4.0
 - Libz                          0.2.4
 - LineSearches                  0.1.5
 - LinearMaps                    1.0.4
 - Loess                         0.3.0
 - LossFunctions                 0.2.0
 - LsqFit                        0.3.0
 - MacroTools                    0.4.0
 - MathProgBase                  0.7.0
 - MbedTLS                       0.5.1
 - Measures                      0.1.0
 - Media                         0.3.0
 - MuladdMacro                   0.0.2
 - MultiScaleArrays              0.5.0
 - Multigrid                     0.0.0-             master (unregistered)
 - NLSolversBase                 2.1.3
 - NLsolve                       0.11.0
 - NaNMath                       0.3.0
 - NamedArrays                   0.6.1
 - NearestNeighbors              0.3.0
 - Nullables                     0.0.1
 - OptimBase                     0.1.0
 - OrdinaryDiffEq                2.21.2
 - PDMats                        0.7.1
 - ParameterizedFunctions        2.3.0
 - Parameters                    0.8.1
 - PenaltyFunctions              0.0.2
 - PlotThemes                    0.1.4
 - PlotUtils                     0.4.4
 - Polynomials                   0.1.6
 - PositiveFactorizations        0.1.0
 - Primes                        0.2.0
 - QuadGK                        0.1.3
 - RData                         0.2.0
 - RandomNumbers                 0.1.1
 - Ratios                        0.2.0
 - RealInterface                 0.0.3
 - RecipesBase                   0.2.3
 - RecursiveArrayTools           0.12.4
 - Reexport                      0.0.3
 - Requires                      0.4.3
 - ResettableStacks              0.2.0
 - ReverseDiffSparse             0.8.0
 - Rmath                         0.3.0
 - Roots                         0.4.1
 - SHA                           0.5.2
 - ShowItLikeYouBuildIt          0.2.0
 - Showoff                       0.1.1
 - SimpleTraits                  0.5.1
 - SortingAlgorithms             0.2.0
 - SpecialFunctions              0.3.5
 - StaticArrays                  0.6.6
 - StatsBase                     0.19.2
 - StatsFuns                     0.5.0
 - SteadyStateDiffEq             0.1.0
 - StochasticDiffEq              2.15.2
 - SugarBLAS                     0.0.4
 - SymEngine                     0.2.0
 - Tk                            0.5.2
 - TranscodingStreams            0.4.1
 - URIParser                     0.3.0
 - UnicodePlots                  0.2.5
 - VectorizedRoutines            0.0.2
 - WinRPM                        0.3.1
 - WoodburyMatrices              0.2.2
 - ZMQ                           0.5.1
 - jInv                          0.0.0-             master (unregistered)
 - jInvVis                       0.0.0-             master (unregistered)

julia>

**Comment by pkofod** [comment]
You have Optim checkout out as some very very old `master` branch (0.4.7). The current version of Optim is 0.11.0.

**Comment by pkofod** [comment]
Please free Optim (`Pkg.free("Optim")`), if it doesn't work we can reopen.
