### ISSUE TITLE
OnceDifferentiable with autodiff throws method error

### ISSUE THREAD

**Issue by baggepinnen** [JuliaNLSolvers/Optim.jl#499]
I'm trying to follow one of the examples in the docs but encounter the following error
```julia
julia> using Optim

julia> function f(x)
           return (1.0 - x[1])^2 + 100.0 * (x[2] - x[1]^2)^2
       end
f (generic function with 1 method)

julia> initial_x = zeros(2)
2-element Array{Float64,1}:
 0.0
 0.0

julia> od = OnceDifferentiable(f, initial_x; autodiff = :forward)
ERROR: MethodError: no method matching ForwardDiff.GradientConfig(::#f, ::Array{Float64,1})
Stacktrace:
 [1] #OnceDifferentiable#2(::Symbol, ::Type{T} where T, ::#f, ::Array{Float64,1}) at /local/home/fredrikb/.julia/v0.6/Optim/src/objective_types.jl:62
 [2] (::Core.#kw#Type)(::Array{Any,1}, ::Type{NLSolversBase.OnceDifferentiable}, ::Function, ::Array{Float64,1}) at ./<missing>:0

julia> Pkg.status("ForwardDiff")
 - ForwardDiff                   0.7.0

julia> Pkg.status("Optim")
 - Optim                         0.10.1
```

**Comment by pkofod** [comment]
Interesting... What's your ForwardDiff version?

**Comment by pkofod** [comment]
I wonder if some happened here between v0.5.0 and v0.7.0 in ForwardDiff, @simonbyrne (since you recently did something to this part of the code you might know) and that an upper bound should have been placed on Optim.

Anyway, the newest version of Optim is v0.11.0. Did you try updating?

**Comment by baggepinnen** [comment]
Same error appears on 
```julia
julia> Pkg.status("Optim")
 - Optim                         0.11.0
```

**Comment by ChrisRackauckas** [comment]
Works for me:

```julia
Pkg.status("ForwardDiff")

 - ForwardDiff                   0.7.0
Pkg.status("Optim")

 - Optim                         0.11.0+            master
```

and looking at the code it looks like it should work too. Optim release is almost no different than master right now, so it should be fine? @baggepinnen you should try using a new REPL session, without any other packages imported. It could be using an old precompiled cache of ForwardDiff, or there might be a type pirate around these waters? (Though that doesn't make much sense: it isn't exported)

**Comment by pkofod** [comment]
Can you maybe show your full `Pkg.status()`?

**Comment by simonbyrne** [comment]
That's bizarre. What does `methods(ForwardDiff.GradientConfig)` give?

**Comment by baggepinnen** [comment]
Hmm, I manually cleared out all cache files for the packages involved and now it works, sorry for the noise :/

**Comment by pkofod** [comment]
> sorry for the noise

No worries! There's a #math-optimization channel over at the JuliaLang slack where you're more than welcome to post all the usage questions you have https://discourse.julialang.org/t/announcing-a-julia-slack/4866 !
