### ISSUE TITLE
no method matching NLSolversBase.OnceDifferentiable

### ISSUE THREAD

**Issue by maartenvd** [JuliaNLSolvers/Optim.jl#500]
trying to run:

x = rand(2*nump)
x /= vecnorm(x)
Optim.optimize(costfun,x,Optim.ConjugateGradient(manifold=Optim.Sphere()))

Throws:

MethodError: no method matching NLSolversBase.OnceDifferentiable(::#costfun#25{Float64,Float64}, ::Optim.#g!#5{#costfun#25{Float64,Float64}}, ::Optim.#fg!#6{#costfun#25{Float64,Float64}}, ::Float64, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Int64,1}, ::Array{Int64,1})
Closest candidates are:
  NLSolversBase.OnceDifferentiable(::Any, ::Any, ::Any, **::AbstractArray**, ::Union{AbstractArray, Real}, ::Any) at /home/maarten/.julia/v0.6/NLSolversBase/src/objective_types/oncedifferentiable.jl:18

Pkg.status():
14 required packages:
 - NLSolversBase                 4.0.0              master
 - Optim                         0.11.0+            master
 - ForwardDiff                   0.7.0              master
 - (...)
46 additional packages:
 - Calculus                      0.2.2
 - Contour                       0.4.0
 - DataStructures                0.7.3
 - DiffResults                   0.0.2
 - DiffRules                     0.0.2
 - LineSearches                  3.2.3
 - (...)

I removed .julia/.cache/* and .julia/lib/*.ji

This used to work very well, until I updated. What am I doing wrong?

**Comment by pkofod** [comment]
You're on optim master is that on purpose?

**Comment by pkofod** [comment]
It is because nlsolversbase has a newer version that only goes together with my open pr.

**Comment by maartenvd** [comment]
I needed the master a while back to do complex optimization on manifolds (which worked). I probably should move to a fixed release, thanks :)

**Comment by pkofod** [comment]
That should be in the current release! Cool to hear you're using that. Would you mind giving a short description of what you're using it for? :)

**Comment by maartenvd** [comment]
I'm working on tensor networks which is a way to study certain problems in physics, a few people in our research group are using julia to do numerics (and the heretics use matlab).

I'm using optim because it's often not worth it to try and implement some kind of alternating least squares / gradient descent when all you really want is to see if something gives interesting results.

**Comment by maartenvd** [comment]
Oh and before I forget to ask, is your pull request the one about being able to pass abstract types to optim? Because we work with these very weird objects (graded tensors) but they still span a vector space and have all the usual goodies (axpy!,vecnorm,scale!,...) defined on them. It'd be cool if they could be used directly :)

**Comment by pkofod** [comment]
I can't guarantee that it'll be able to go all the way as it stands right now, but I have been looking for a good example (I don't particularly need more than arrays myself). Can you share something here or in a mail that you would like to work but doesn't, that I could try to run to see where some things may be too strictly typed?

**Comment by maartenvd** [comment]
I hope you had a merry christmas.

Everything has been a bit busy with family obligations left and right. In this zip is an almost self contained example : https://www.dropbox.com/s/je5sol1j81xvhrv/TensorKit.jl.zip?dl=0

**Comment by pkofod** [comment]
Same here, but I'll have a look, thanks!

**Comment by pkofod** [comment]
Is there an optimization problem in there somewhere?

**Comment by maartenvd** [comment]
Yes, in example.jl ; which is a pretty poorly chosen name.
