### ISSUE TITLE
Finite Difference: Remove Calculus when DiffEqDiffTools Hessians are implemented

### ISSUE THREAD

**Issue by anriseth** [JuliaNLSolvers/Optim.jl#519]
Remove all uses of `Calculus.jl` when https://github.com/JuliaDiffEq/DiffEqDiffTools.jl/issues/13 is closed.

**Comment by ChrisRackauckas** [comment]
See https://github.com/JuliaDiffEq/DiffEqDiffTools.jl/pull/61

**Comment by pkofod** [comment]
Great, thanks !
