### ISSUE TITLE
Receiving optimize Fminbox deprecation error, even though explicitly providing x

### ISSUE THREAD

**Issue by JavaFXpert** [JuliaNLSolvers/Optim.jl#525]
I began receiving the following error today:
Optimizing an objective `obj` without providing an initial `x` has been deprecated without backwards compatability. Please explicitly provide an `x`: `optimize(obj, x, l, u, method, options)``

I'm not sure what is incorrect, as here is the code that I'm using to invoke the optimize function:

```
lower = zeros(28)
fill!(lower, 0)
upper = zeros(28)
fill!(upper, 359)
initial_x = zeros(28)
fill!(initial_x, 179)
results = optimize(computeCost, initial_x, lower, upper, Fminbox{GradientDescent}())
```
Is there an issue with the way I'm using the optimize function?

Please advise,
James Weaver

**Comment by pkofod** [comment]
No, sorry about the inconvenience. This was reported yesterday as well https://github.com/JuliaNLSolvers/Optim.jl/issues/522 and fixed today https://github.com/JuliaNLSolvers/Optim.jl/pull/524

but you will either have to checkout master or way for the next update (that should be one of the coming days!)

Again, sorry for the inconvenience, but I didn't catch this bug before upgrading Optim to v0.12

**Comment by JavaFXpert** [comment]
Thanks Patrick. I'm using JuliaBox, so will the fix automagically appear
soon (just like the break did)?
Thanks,
James Weaver


On Thu, Feb 1, 2018, at 10:26 AM, Patrick Kofod Mogensen wrote:
> No, sorry about the inconvenience. This was reported yesterday as well
> #522[1] and fixed today #524[2]> but you will either have to checkout master or way for the next update
> (that should be one of the coming days!)> Again, sorry for the inconvenience, but I didn't catch this bug before
> upgrading Optim to v0.12> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[3], or mute the thread[4].> 


Links:

  1. https://github.com/JuliaNLSolvers/Optim.jl/issues/522
  2. https://github.com/JuliaNLSolvers/Optim.jl/pull/524
  3. https://github.com/JuliaNLSolvers/Optim.jl/issues/525#issuecomment-362300245

**Comment by pkofod** [comment]
Yes I believe it should. How are packages updated on JuliaBox @aviks ?

**Comment by aviks** [comment]
We update Juliabox once every few days. The next update should arrive early next week. Which version of Optim will I want, for verification?

**Comment by JavaFXpert** [comment]
Optim 0.7.8 is what the Package Builder page is showing in JuliaBox.
Please do update Julia soon.
Thanks,
James Weaver


On Thu, Feb 1, 2018, at 10:42 AM, Avik Sengupta wrote:
> We update Juliabox once every few days. The next update should arrive
> early next week. Which version of Optim will I want, for verification?> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].> 


Links:

  1. https://github.com/JuliaNLSolvers/Optim.jl/issues/525#issuecomment-362305342

**Comment by pkofod** [comment]
I can see that as well on my end, but that is weird. v0.7.8 is almost a year old

**Comment by aviks** [comment]
You're looking at the versions for Julia `0.5`. Click the link marked `v0.6` to see the packages installed for Julia`0.6`. I can see that the current Optim version on Juliabox is `0.12.0`.

**Comment by pkofod** [comment]
Oh okay. The error message reported here suggests that a v0.6 notebook and v0.12.0 was actually used, so it's still relevant. To answer your question about the version @aviks , it's the one that I will be tagging tomorrow :)

**Comment by JavaFXpert** [comment]
Thanks. Yes, I see v0.12.0 on the JuliaBox v0.6 link.

Regards,
James Weaver


On Thu, Feb 1, 2018, at 11:11 AM, Patrick Kofod Mogensen wrote:
> Oh okay. The error message reported here suggests that a v0.6 notebook
> and v0.12.0 was actually used, so it's still relevant. To answer your
> question about the version @aviks[1] , it's the one that I will be
> tagging tomorrow :)> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[2], or mute the thread[3].> 


Links:

  1. https://github.com/aviks
  2. https://github.com/JuliaNLSolvers/Optim.jl/issues/525#issuecomment-362315250

**Comment by pkofod** [comment]
updated, now you just have to wait forJuliabox to catch up :)
