### ISSUE TITLE
Arbitrary precision

### ISSUE THREAD

**Issue by mohamed82008** [JuliaNLSolvers/Optim.jl#527]
https://github.com/JuliaNLSolvers/Optim.jl/blob/f2e0ac97f6ccdd5f0b46afe94ba25d22c28aa32c/src/types.jl#L63

Don't you think the above should be made a parameter instead of Float64? There are also many instances of `Float64` when I searched for the term in VSCode which I believe may be made a parameter to fully support arbitrary precision.

**Comment by pkofod** [comment]
That should definitely be parametric. BigFloat support was almost an accident, so many things may not be appropriate throughout the code base. I'll have a look tonight, and then I'll tag a new version soon!thanks for bringing these things up
