### ISSUE TITLE
Trust-region solver fails to solve trivial problems

### ISSUE THREAD

**Issue by jomi2801** [JuliaNLSolvers/Optim.jl#534]
I ran the solver for trust-region problems with  `gr=zeros(3); H=zeros(3, 3)` and `delta=1.0` and the method fails to compute an optimal solution of the corresponding trust-region problem. In fact, the code returns `[NaN, NaN, NaN]`...

**Comment by pkofod** [comment]
What does this mean? How did you set `gr` and `H`? Please provide code I can run to reproduce the behaviour you're describing.

**Comment by jomi2801** [comment]
Sure! Here is some code:
```
julia> using Optim
julia> g = zeros(3); H = zeros(3, 3); radius = 1.0; s = zeros(3);
julia> Optim.solve_tr_subproblem!(g, H, radius, s);
julia> s
3-element Array{Float64,1}:
 NaN
 NaN
 NaN

```

**Comment by jomi2801** [comment]
You could add to your code something like
```
if norm(H) == 0.0 && norm(gr) == 0
fill!(s, zero(T))
lambda = zero(T)
elseif elseif min_H_ev >= 1e-8 && p_sq_norm(zero(T), 1, n, qg, H_eig) <= delta_sq
...
```

**Comment by pkofod** [comment]
Ah, okay like that. Did this come up in an actual optimization run?

I will have a look as soon as I have time. Thanks for testing this!

**Comment by jomi2801** [comment]
Yes it did. I am running multiple trust-region problems and one of these problems happened to be "trivial."

**Comment by pkofod** [comment]
Yeah, we certainly don't want it to fail at a minimizer :)

**Comment by pkofod** [comment]
Hm, what I don't understand is that the gradient should have been checked at this point... Can you give me a reproducing call to `optimize` ?

**Comment by jomi2801** [comment]
I have used Optim.solve_tr_subproblem! directly.

**Comment by pkofod** [comment]
oh, that is why. Interesting :)

**Comment by jomi2801** [comment]
Yes, I did. I will unsubscribe from this thread. Thanks for your replies.

**Comment by pkofod** [comment]
@jomi2801 I'm sorry if I scared you away, if this is useful to people, we can make a safe version.
