### ISSUE TITLE
NelderMead calls undefined method

### ISSUE THREAD

**Issue by mohamed82008** [JuliaNLSolvers/Optim.jl#537]
https://github.com/JuliaNLSolvers/Optim.jl/blob/13786da32a5421497386c3afc14e4071f99a63bc/src/multivariate/solvers/zeroth_order/nelder_mead.jl#L54

The above line seems to be a forgotten leftover from some changes in the NelderMead file. It's calling an undefined method.

**Comment by pkofod** [comment]
yes it's calling a deprecated constructor that was then removed, apparently without removing this branch. Good catch.
