### ISSUE TITLE
Trust-Region code does not handle the hard case

### ISSUE THREAD

**Issue by jomi2801** [JuliaNLSolvers/Optim.jl#540]
It seems that the trust region method does not handle the hard case properly.
Here some code
```
julia>  g = [1.0, 0.0, -1.0]; H = zeros(3, 3); H[2, 2] = -20.0; r = zeros(3);
_, _, lambda, _, _ = Optim.solve_tr_subproblem!(g, H, 1.0, r); 
```
An optimality conditions is `(H+lambda*eye(3))*r+g = 0.` However, we obtain
```
julia> (H+lambda*eye(3))*r+g
3-element Array{Float64,1}:
  2.0       
  1.99499e-7
 -2.0 
```
I believe the gradient information is handled in a wrong way. Consider for example
```
(H+lambda*eye(3))*r-g
3-element Array{Float64,1}:
 0.0       
 1.99499e-7
 0.0       
```
Moreover, I do not understand why you "regularize" `lambda`. It should be `ļambda=20` however is computed as
```
julia> lambda
20.0000002
```
I do not understand why we should compute lambda according to 
` lambda_lb = -min_H_ev + max(1e-8, 1e-8 * (max_H_ev - min_H_ev))` 
in the hard case. It is supposed to be `-min_H_eve`...

**Comment by anriseth** [comment]
Seems like the trust region subproblem could do with an overhaul. I believe most people have been using the line search algorithm, so it's good to get some focus on this.


If you can provide some PRs to address the different issues you encounter, that would be very helpful!

**Comment by pkofod** [comment]
@jeff-regier might have something to say here

**Comment by jeff-regier** [comment]
I added the line
```
lambda_lb = -min_H_ev + max(1e-8, 1e-8 * (max_H_ev - min_H_ev))
```
to fix a numerical instability issue that happens when we're not in the hard case, as far as I recall (it was awhile ago). I'm not familiar with the hard case code---maybe lambda should be set to exactly `min_H_ev` there?

**Comment by jomi2801** [comment]
If you ask me, yes lambda should be the minimum eigenvalue of the Hessian in hard cases (see e.g.  Nocedal and Wright). It's kind of impressive that there are explicit formulas for optimal solutions in hard cases.

**Comment by pkofod** [comment]
Some issues with numerically adjusting lambda have been fixed, but I won't do a major overhaul here. NLSolvers.jl has completely rewritten TR code.
