### ISSUE TITLE
Finite differencing should respect box constraints

### ISSUE THREAD

**Issue by simonbyrne** [JuliaNLSolvers/Optim.jl#541]
If I specify box constraints, the finite differencing code still sometimes steps outside these bounds, which can cause errors.

**Comment by ChrisRackauckas** [comment]
Then it needs a `max_eps` argument to pass down to the finite difference method. That's kind of odd though, since if you use a smaller eps then it can be numerically bad. Is it better just to switch to forward or backward differencing automatically?

**Comment by pkofod** [comment]
So just to be clear, you use `Fminbox` with a finite difference gradient for the objective? Or are we talking about finite differencing on the objective + barrier penalty?

**Comment by simonbyrne** [comment]
As an example:
```
julia> f(x) = x[1] < 0 ? error("oh no: x[1] = $(x[1])") : x[1]^2 + x[2]^2
f (generic function with 1 method)

julia> Optim.optimize(OnceDifferentiable(f, [1.0,2.0]), [1.0,2.0], [0.0,-Inf], [Inf,Inf], Fminbox{LBFGS}())
ERROR: oh no: x[1] = -8.69673602412312e-7
Stacktrace:
 [1] f(::Array{Float64,1}) at ./REPL[12]:1
 ...
```

**Comment by mohamed82008** [comment]
Finite difference is only used for the objective function, the log-barrier derivative is hard coded. The problem is that the constructor of `OnceDifferentiable` is not aware that it is being used in an Fminbox context, so perhaps a macro can do the trick to allow for checking the seed at runtime and pushing it inside the bounds if necessary before constructing the objective.

**Comment by pkofod** [comment]
This happens because the linesearches assume that this is handled by returning something that isn't finite if you're in such a case.
```
using Optim
f(x) = x[1] < 0 ? NaN : x[1]^2 + x[2]^2
Optim.optimize(OnceDifferentiable(f, [1.0,2.0]), [1.0,2.0], [0.0,-Inf], [Inf,Inf], Fminbox{LBFGS}())
```
https://github.com/JuliaNLSolvers/LineSearches.jl/blob/6873fa5a2264a40f6e5b9fa2df2681a2847eec72/src/backtracking.jl#L68

So a hack is simply to check for the bounds in your objective. The correct fix is of course to avoid looking outside the box at all here. In Fminbox that would simply be truncating the initial step size in the line search.

**Comment by pkofod** [comment]
Huh, it seems like there is already such a function in the file

https://github.com/JuliaNLSolvers/Optim.jl/blob/be51a8f0024fe4dd4a14736d04e5105073db6f57/src/multivariate/solvers/constrained/fminbox.jl#L74

That will limit the step size accoding to the current x, the current search direction and the bounding box.

**Comment by pkofod** [comment]
> Finite difference is only used for the objective function, the log-barrier derivative is hard coded. The problem is that the constructor of `OnceDifferentiable` is not aware that it is being used in an Fminbox context, so perhaps a macro can do the trick to allow for checking the seed at runtime and pushing it inside the bounds if necessary before constructing the objective.

This is not correct though... If close enough to the bounds, the gradient evaluation using central finite differences *can* indeed, as Simon alluded to in the original comment, evaluate `f` outside of the bounds. So even if we don't evaluate the barrier contribution outside the box, we still might get a problem if `f` can't even be evaluated outside of the box without erroring.

It's a good question what to do with the finite differencing. I've prepared a PR that'll handle the general problem of evaluating the objective (!) outside of the box, and relying on a backtracking procedure in the line search to find a finite objective, but I'm not sure what do to here, beyond the solution of detecting if you should leave the central scheme and step backwards if at the upper bounds (and do this element wise!) or forwards if at the lower bound. I guess this can be implemented by choosing forward finite diff mode, and then subtracting `epsilon` by using `compute_epsilon_factor` and `compute_epsilon` from DiffEQDiffTools...

**Comment by ChrisRackauckas** [comment]
We should change DiffEqDiffTools to not have the diff choice be based on type information. It's just a quick conditional (and constant prop would handle it anyways in most cases), so it's a bit of an over-optimization. If it's just a symbol or enum then we can allow you to more effectively switch it around.
