### ISSUE TITLE
Fminbox with Optim.Options gives error

### ISSUE THREAD

**Issue by simonbyrne** [JuliaNLSolvers/Optim.jl#542]
```
using Optim
f(x) = dot(x,x)
Optim.optimize(OnceDifferentiable(f, [1.0,2.0], autodiff=:forward),
               [1.0,2.0], [0.0,-Inf], [Inf,Inf],
               Fminbox{BFGS}(), Optim.Options(x_tol=1e-4))
```

```
julia> Optim.optimize(OnceDifferentiable(f, [1.0,2.0], autodiff=:forward),
                      [1.0,2.0], [0.0,-Inf], [Inf,Inf],
                      Fminbox{BFGS}(), Optim.Options(x_tol=1e-4))
ERROR: No default objective type for Optim.Fminbox{Optim.BFGS}() and (NLSolversBase.OnceDifferentiable{Float64,Array{Float64,1},Array{Float64,1},Val{false}}(f, Optim.#6, Optim.#7, 0.0, [NaN, NaN], [NaN, NaN], [NaN, NaN], [0], [0]), [1.0, 2.0], [0.0, -Inf]).
Stacktrace:
 [1] optimize at /Users/simon/.julia/v0.6/Optim/src/multivariate/optimize/interface.jl:80 [inlined]
 [2] optimize(::NLSolversBase.OnceDifferentiable{Float64,Array{Float64,1},Array{Float64,1},Val{false}}, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Optim.Fminbox{Optim.BFGS}, ::Optim.Options{Float64,Void}) at /Users/simon/.julia/v0.6/Optim/src/multivariate/optimize/interface.jl:77
```

**Comment by mohamed82008** [comment]
Seems like a dispatch problem. This works:
```julia
julia> Optim.optimize(OnceDifferentiable(f, [1.0,2.0], autodiff=:forward),
                      [1.0,2.0], [0.0,-Inf], [Inf,Inf],
                      Fminbox{BFGS}(), optimizer_o=Optim.Options(x_tol=1e-4))
Results of Optimization Algorithm
 * Algorithm: Fminbox with BFGS
 * Starting Point: [1.0,2.0]
 * Minimizer: [1.732490485369608e-14,-9.553697010690142e-24, ...]
 * Minimum: 1.931213e-26
 * Iterations: 7
 * Convergence: true
   * |x - x'| ≤ 1.0e-04: false
     |x - x'| = 2.90e-06
   * |f(x) - f(x')| ≤ 1.0e-32 |f(x)|: false
     |f(x) - f(x')| = 4.37e+14 |f(x)|
   * |g(x)| ≤ 1.0e-08: true
     |g(x)| = 3.46e-14
   * Stopped by an increasing objective: false
   * Reached Maximum Number of Iterations: false
 * Objective Calls: 86
 * Gradient Calls: 86
```

**Comment by pkofod** [comment]
That's mentioned in the documentation http://julianlsolvers.github.io/Optim.jl/stable/user/minimization/ . It's not super nice, but ...

**Comment by pkofod** [comment]
> Options are hard, I agree.

Can I ask what you mean exactly? Do you mean that Options are difficult to pass in Optim, or?

**Comment by simonbyrne** [comment]
I mean that providing a mechanism to specify options is complicated, especially in larger projects. This is perhaps a bigger problem in Julia due to the tendency to compose complicated functions out of lots of smaller ones (so the options need to be passed through the various caller functions to the correct one).

For example, at the moment I'm working on a project that combines both Optim and DiffEqs, but allow various options to be passed at different stages. I'm not sure yet what the best mechanism is to do that.

**Comment by ChrisRackauckas** [comment]
>For example, at the moment I'm working on a project that combines both Optim and DiffEqs, but allow various options to be passed at different stages. I'm not sure yet what the best mechanism is to do that.

I assumed the Optim options type would have handled this.

**Comment by pkofod** [comment]
> I mean that providing a mechanism to specify options is complicated, especially in larger projects. This is perhaps a bigger problem in Julia due to the tendency to compose complicated functions out of lots of smaller ones (so the options need to be passed through the various caller functions to the correct one).

Okay, then I understood you. I just wanted to know if there was something specific in Optim you weren't satisfied with.

> For example, at the moment I'm working on a project that combines both Optim and DiffEqs, but allow various options to be passed at different stages. I'm not sure yet what the best mechanism is to do that.

I don't know your specific application. Is it not enough to construct the relevant options instances up front, and then pass them around?

**Comment by simonbyrne** [comment]
Yes, that's what I'll probably end up doing (it's actually a bit more complicated, as there are 2 nested optimisations)

**Comment by pkofod** [comment]
Ok. Anyway, let's keep this open until the method error is fixed
