### ISSUE TITLE
Is posible enter the limit separatly for each parameter  ? Multivariate optimization.

### ISSUE THREAD

**Issue by programistawpf** [JuliaNLSolvers/Optim.jl#552]
I have multivariate optimization:

x0 = fill(0.5, 3) (makes x0.1, x0.2 x0.3)
optimize(my_f,x0)
Is posible enter the limit separatly for each parameter  ? like this :

1 > x0.1 >0
1 > x0.2 >0
2 > x0.3 >0

or one for all ?

Paul

**Comment by anriseth** [comment]
When you say limit, do you mean the bounds?

If so, the answer is yes, and we have two ways to do this. 

- Use Fminbox. See "Box minimisation" at http://julianlsolvers.github.io/Optim.jl/stable/user/minimization/
- Use ConstrainedOptim. This is experimental, however it supports more complicated constraints. See the readme for examples at https://github.com/JuliaNLSolvers/ConstrainedOptim.jl

(I would provide you with an example for your case, but I'm on my phone so it's a bit difficult)

**Comment by programistawpf** [comment]
Yes, bound for a, b c

|x0 = fill(0.5, 3) # use three 0.5's as starting values for a,b,c 
my_vector_function(x) = my_function(a,b,c) optimize(my_vector_function, 
x0) is the same like |
||optimize(|||||my_function|, x0)| ||1 > x0.1 >0 (a) |||1 > x0.2 >0| (b) |||2 > x0.3 >0 (c) Paul ||||


W dniu 2018-03-16 o 12:49, Asbjørn Nilsen Riseth pisze:

**Comment by anriseth** [comment]
Did the explanation from the documentation on Fminbox provide you with a sufficient explanation for how to implement this?

It is quite difficult to read  your example. Can you please use the markdown code blocks and provide a minimum working example in the future? See https://github.com/JuliaNLSolvers/Optim.jl/blob/master/CONTRIBUTING.md and the link within.

**Comment by pkofod** [comment]
If this is still unclear, please ask on discourse.
