### ISSUE TITLE
Maximize option for the optimizer

### ISSUE THREAD

**Issue by jlperla** [JuliaNLSolvers/Optim.jl#554]
A major usability addition for making code clearer would be an interface to directly maximize a function.  Yes, I know you can do it right now by introducing an anonymous function to take the negative, and then remember to negate the minimum, but it is error prone, adds syntactic noise, and not very intuitive for undergrads when looking at sample code.

Would you be willing to consider a PR to maximize?

If so, I am not 100% sure the best way to do it.  The problem is that the `MultivariateOptimizationResults` structure has the fields `minimizer::Tx` and `minimum::Tf`, so it is not so clear how to write the convenience wrapper or additional named parameter.

Any thoughts?  In the short term, what about having a `maximize` function that returns a  `MultivariateMaximizationResults` structure which is basically a copy of  `MultivariateOptimizationResults`?  This could just be a convenience function which negates the function, swaps the sign of the `minimum` etc.?

**Comment by pkofod** [comment]
ref #308 

let me think about the best way to do this

**Comment by arnavs** [comment]
OK, q from slack was basically: how much renaming/refitting are we comfortable with here? For example, all the type fields and getters and printers say `minimum` and `minimizer`, etc. So if we are to move to `optimum` and `optimizer`, I think that would be a fairly significant re-write. 

Also, for the multivariate code(and even univariate), it looks like there are lots of points where we could insert the negation logic. Take the univariate case. You could put it in each solver, which has the advantage of making sure that maximization is handled properly, but the downside of code duplication.

Alternately, you could put it in the functions in `/univariate/optimize/interface.jl`. Less code duplication, but this requires teasing out the hierarchy of methods (_this_ one calls _this_ one which calls _that_ one, but sometimes we can go directly to the solver using _this_ one...) which introduces possible error. 

cc: @jlperla

**Comment by jlperla** [comment]
@pkofod   To be precise, I think what @arnavs  is asking about here is whether you want him to:
1. Go to https://github.com/JuliaNLSolvers/Optim.jl/blob/master/src/univariate/types.jl and rename `minimizer` and `minimum` to `optimizer` and `optimum` and add in some sort of direction flag.
    - This would have big changes throughout the library and is probably breaking.
1. Add in some sort of direction flag to `UnivariateOptimizationResults` but not rename anything directly.
   - Change `Base.show(io::IO, r::UnivariateOptimizationResults)` to use that flag to tweak what to display
   - We would write a `maximum` and `maximizer` in https://github.com/JuliaNLSolvers/Optim.jl/blob/master/src/api.jl where signs are swapped if appropriate.  These would access the `.minumum` and `.minimizer` fields, since they wouldn't be renamed with this approach.

Besides that, the question is how that flag would be set?  Call `maximize` instead of `optimizer`?  or a keyword argument?  Totally up to you guys.

**Comment by arnavs** [comment]
@jlperla Yes, that's right. Thanks for making this clearer.

**Comment by pkofod** [comment]
I'm not sure I like the flag idea... hm.. I know we discussed this, but it's because all these boolean flags are just not.. nice.. I hated the "iscomplex" flag in the NDifferentiables, and I'm so happy they're gone. Let my try something else... It's getting late though, so I won't finish it tonight.

**Comment by pkofod** [comment]
With #661 merged, it would be great if @arnavs could maybe add multivariate constrained api, and also add the `maximize(f, g!, x0)` and `maximize(f, g!, h!, x0)` calls just like I did with `maximize(f, x0)` - that is: the case where no method is given. More tests would be great as well, say test that all of the function based api for getting results works and is consistent across min and max.

**Comment by arnavs** [comment]
Sounds like a plan. I’ll update you here.
