### ISSUE TITLE
Limit time Error? . how to inset?

### ISSUE THREAD

**Issue by programistawpf** [JuliaNLSolvers/Optim.jl#559]
How to insert time_limit ?
restmp = OnceDifferentiable(licz, abc)
julia> result1 = optimize(restmp, abc, lower, upper, Fminbox{GradientDescent}(), Optim.Options(time_limit=10));

ERROR: MethodError: no method matching Optim.Options(::Float64, ::Float64, ::Float64, ::Int64, ::Int64, ::Int64, ::Bool,
 ::Int64, ::Int64, ::Bool, ::Bool, ::Bool, ::Int64, ::Void, ::Int64)
Closest candidates are:
  Optim.Options(::T, ::T, ::T, ::Int64, ::Int64, ::Int64, ::Bool, ::Int64, ::Int64, ::Bool, ::Bool, ::Bool, ::Int64, ::T
Callback, ::Float64) where {T, TCallback} at C:\Users\PC\.julia\v0.6\Optim\src\types.jl:11
Stacktrace:
 [1] #Options#1(::Float64, ::Float64, ::Float64, ::Int64, ::Int64, ::Int64, ::Bool, ::Int64, ::Int64, ::Bool, ::Bool, ::
Bool, ::Int64, ::Void, ::Int64, ::Type{T} where T) at C:\Users\PC\.julia\v0.6\Optim\src\types.jl:48
 [2] (::Core.#kw#Type)(::Array{Any,1}, ::Type{Optim.Options}) at .\<missing>:0
Paul

**Comment by pkofod** [comment]
Hm, the times are floats for a stupid reason (to use NaN is invalid comparison in the "is the time up" checks), try `10.0`

**Comment by pkofod** [comment]
after https://github.com/JuliaNLSolvers/Optim.jl/pull/560 is merged you can use 10 like you did :)

**Comment by programistawpf** [comment]
`julia>  result1 = optimize(restmp, abc, lower, upper, Fminbox{GradientDescent}(), Optim.Options(time_limit=NaN));
ERROR: No default objective type for Optim.Fminbox{Optim.GradientDescent}() and (NLSolversBase.OnceDifferentiable{Float6
4,Array{Float64,1},Array{Float64,1},Val{false}}(licz, Optim.g!, Optim.fg!, 0.0, [NaN, NaN, NaN], [NaN, NaN, NaN], [NaN,
NaN, NaN], [0], [0]), [0.5, 0.5, 0.5], [0.0, 0.0, 0.0]).
Stacktrace:
 [1] optimize at C:\Users\PC\.julia\v0.6\Optim\src\multivariate/optimize\interface.jl:80 [inlined]
 [2] optimize(::NLSolversBase.OnceDifferentiable{Float64,Array{Float64,1},Array{Float64,1},Val{false}}, ::Array{Float64,
1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Optim.Fminbox{Optim.GradientDescent}, ::Optim.Options{Float64,Void}) at C:
\Users\PC\.julia\v0.6\Optim\src\multivariate/optimize\interface.jl:77

julia>  result1 = optimize(restmp, abc, lower, upper, Fminbox{GradientDescent}(), Optim.Options(time_limit=10.0));
ERROR: No default objective type for Optim.Fminbox{Optim.GradientDescent}() and (NLSolversBase.OnceDifferentiable{Float6
4,Array{Float64,1},Array{Float64,1},Val{false}}(licz, Optim.g!, Optim.fg!, 0.0, [NaN, NaN, NaN], [NaN, NaN, NaN], [NaN,
NaN, NaN], [0], [0]), [0.5, 0.5, 0.5], [0.0, 0.0, 0.0]).
Stacktrace:
 [1] optimize at C:\Users\PC\.julia\v0.6\Optim\src\multivariate/optimize\interface.jl:80 [inlined]
 [2] optimize(::NLSolversBase.OnceDifferentiable{Float64,Array{Float64,1},Array{Float64,1},Val{false}}, ::Array{Float64,
1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Optim.Fminbox{Optim.GradientDescent}, ::Optim.Options{Float64,Void}) at C:
\Users\PC\.julia\v0.6\Optim\src\multivariate/optimize\interface.jl:77
`

**Comment by anriseth** [comment]
Glad you found it :) The Fminbox interface is a little bit awkward.
