### ISSUE TITLE
PositiveFactorizations not creating good Newton steps

### ISSUE THREAD

**Issue by bdeonovic** [JuliaNLSolvers/Optim.jl#563]
I have an example where the PositiveFactorizations approach for Newton steps is not creating reasonable Newton Steps. Is there a way to force it to do a Newton step that is simply `h\g` where h is hessian and g is gradient? 

See discussion at https://discourse.julialang.org/t/newton-optimization-with-optim-doing-strange-things/10008

**Comment by pkofod** [comment]
Yes

**Comment by pkofod** [comment]
@timholy might be interested in the problematic case

**Comment by bdeonovic** [comment]
Can you elaborate? Like someone has submitted a PR or someone plans to submit a PR? And soon being...? I'd love to share my problem case with @timholy

**Comment by bdeonovic** [comment]
I'd also like to understand the code a bit better. In the newton code there is:

```julia
if typeof(NLSolversBase.hessian(d)) <: AbstractSparseMatrix
        state.s .= -NLSolversBase.hessian(d)\convert(Vector{T}, gradient(d))
    else
        state.F = cholfact!(Positive, NLSolversBase.hessian(d))
        if typeof(gradient(d)) <: Array
            # is this actually StridedArray?
            A_ldiv_B!(state.s, state.F, -gradient(d))
        else
            # not Array, we can't do inplace ldiv 
            gv = Vector{T}(length(gradient(d)))
            copy!(gv, -gradient(d))
            copy!(state.s, state.F\gv)
        end
    end
```
The first code after the if clause seems to be what I would like my newton step to be...so it seems like in my example that if statement is not evaluating to true. Why is that?

**Comment by pkofod** [comment]
An AbstractMatrix?

**Comment by bdeonovic** [comment]
Oh I see, it does the standard newton step for sparse hessians got it.

**Comment by anriseth** [comment]
A workaround for you right now is to create a TwiceDifferentiable from NLSolversBase where you explicitly create a sparse matrix for the Hessian cache for the constructor.

(It may be easier to just change the code you have linked to and replace AbstractSparseMatrix with AbstractMatrix, or whatever your Hessian is stored as)

**Comment by bdeonovic** [comment]
Thanks guys I just edited the Optim code so that it always uses the standard newton step. It would be nice to have a configurable option though to determine this.

**Comment by pkofod** [comment]
> It would be nice to have a configurable option though to determine this.

Yes, especially if you know your Hessian is psd
