### ISSUE TITLE
Output printing

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaNLSolvers/Optim.jl#570]
The output printing leaves much to be desired IMO.

- It only gives the algorithm, not other important parameters (line search for instance)
- It prints the starting point and minimizer, which is only helpful for small instances (not completely true, it's sometimes helpful to get a quick look at the first component of these)
- It is very verbose
- It is not aligned and hard to parse
- The output does not follow a logical order

How about something like:

```
 * Result: converged | increasing objective | max iters
 * Minimizer:       [1.000000002262018,1.0000000045408348]
 * Minimum:         5.144946e-18
 * |x - x'|:        2.09e-10
 * |f(x) - f(x')|:  1.55e+00
 * |g(x)|:          3.36e-09
 * Algorithm: Conjugate Gradient with Hager-Zhang line search
 * Starting Point:  [0.0,0.0]
 * Iterations:      21
 * Objective Calls: 54
 * Gradient Calls:  39
```

**Comment by anriseth** [comment]
Just as a quick note, the `|f(x) - f(x')|` line is missing the `|f(x)|` value on the right hand side (as we are looking at a relative change)
