### ISSUE TITLE
Tolerances

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaNLSolvers/Optim.jl#571]
Right now, f is measured in relative terms, while x and g are in absolute terms. What would make more sense? Should there be a relative and absolute tolerance for all three quantities?

**Comment by anriseth** [comment]
Ref https://github.com/JuliaNLSolvers/Optim.jl/issues/279

**Comment by pkofod** [comment]
I really haven't been able to find a good discussion of this anywhere. Different libraries do different things. Would love to see if and how anyone have argued for or against different things.

**Comment by antoine-levitt** [comment]
The standard argument is that absolute tolerances don't have any meaning because they depend on the scale of your problem, which floating point arithmetic is designed to ignore (as long as you don't go too crazy). A counter-argument is that relative comparisons break down when the quantity naturally approaches 0 (for g definitely, for x and f because sometimes you want to minimize x^2+y^2). My preference would be to put everything in absolute and trust the users to know the scale of their problems.

I've seen @stevengj have strong opinions on that on discourse, so pinging him here.

**Comment by stevengj** [comment]
I think it's generally useful to allow the user to specify both/either absolute and/or relative tolerances (`atol` and `rtol`).

**Comment by pkofod** [comment]
> I think it's generally useful to allow the user to specify both/either absolute and/or relative tolerances (atol and rtol).

Reading https://nlopt.readthedocs.io/en/latest/NLopt_Introduction/#termination-conditions it's not clear to me how you stop based on the gradient?

**Comment by stevengj** [comment]
NLopt doesn't currently support stopping based on the gradient.  (Not all of the solvers even have a gradient.  For nonlinearly constrained problems, a gradient condition would need to be coupled with a tolerance on the constraints to indicate when they are considered to be active.)

**Comment by pkofod** [comment]
> NLopt doesn't currently support stopping based on the gradient.

Interesting

> Not all of its solvers even have a gradient.

I know, but it could be that those that did had this criterion set up

> For the gradient, I find it particularly difficult as a user to choose a reasonable absolute tolerance. You need to have some sense of the absolute scale of the variation in both x and f. And it's tricky to define a relative tolerance in that case. But I realize that many people find it useful nonetheless.

Interesting to get your perspective on this. So what would happen if you set no stopping criterion? Will it then go on and on until there's an exact 0 change in x or f?

**Comment by stevengj** [comment]
> So what would happen if you set no stopping criterion? 

Some of the solvers will go on for ever, some of them will detect that convergence has become roundoff-limited and will stop with a `NLOPT_ROUNDOFF_LIMITED` return code.
