### ISSUE TITLE
Rewrite NGMRES loops as broadcasts / BLAS?

### ISSUE THREAD

**Issue by anriseth** [JuliaNLSolvers/Optim.jl#573]
It may help with readability and (according to @antoine-levitt) performance to rewrite the `NGMRES` and `OACCEL` procedures with broadcasts / BLASify things. 
Something along the lines of the Anderson implementation in NLsolve could be a good place to start: https://gist.github.com/antoine-levitt/d02385ae194c65971ca15dbc285946be 

This could also make it easier to see whether we are doing the "right thing" in handling complex numbers.

For OACCEL, that means creating the matrix `A` and vector `b` in Algorithm 1 below in the most readable and efficient way.
The current implementation uses a lot of loops (Algorithm 2)

![oaccel](https://user-images.githubusercontent.com/5601805/38424037-ae2f1e5c-39a7-11e8-8afb-f06f5095f95b.png)

![oaccel2](https://user-images.githubusercontent.com/5601805/38424046-b77d221a-39a7-11e8-9120-feb833e29836.png)

**Comment by pkofod** [comment]
Is this a reminder, or is there a question that I missed somewhere? :)

**Comment by anriseth** [comment]
> Is this a reminder, or is there a question that I missed somewhere? :)

It's a reminder, in case I have time to get back to it sometime this summer :)

**Comment by pkofod** [comment]
Feel free to open if you get the time to do it ;)
