### ISSUE TITLE
Some questions about convergence assessment and results

### ISSUE THREAD

**Issue by jonathanBieler** [JuliaNLSolvers/Optim.jl#574]
Sorry if that's not quite the right place to ask these questions, but I don't know of others.

 I'm working a bit on my [CMAES implementation](https://gist.github.com/jonathanBieler/7000344c67dc715c8a52601db7985b5a) and it works pretty well but I have a couple of issues.

1. I included `x_previous` and `f_x_previous` in my state so I can use `default_convergence_assessment` but I also need to add some other checks, and disable `f_increased`, I'm not sure what's the right way to do it. Should I put all my others conditions in `converged` ?

2. I haven't found where `x_previous` and `f_x_previous` are updated in optimisers that use them, I added 

```
state.x_previous = copy(state.x)
state.f_x_previous = d.f(state.x_previous)
```

At the beginning of my `update_state` but I think that will do an additional function evaluation. Is there some default way to update those ?

3. My result output is bit messed up (Minimum is always zero), where does that get updated ? I've tried to implement an `after_while` but I haven't manage to fix it.

```
Results of Optimization Algorithm
 * Algorithm: CMAES.CMA
 * Starting Point: [3.8636745518960613,2.444114056003256, ...]
 * Minimizer: [2.979823383407434,-3.9645680069721423, ...]
 * Minimum: 0.000000e+00
```

Thanks!

**Comment by pkofod** [comment]
Cool to see an attempt at an Optim extension. I really want what you're doing to be feasible, so it's valuable to see an attempt. Let me get back to you later!

**Comment by anriseth** [comment]
May I quickly note that,  for your case, emulating the approach by [NewtonTrustRegion](https://github.com/JuliaNLSolvers/Optim.jl/blob/master/src/multivariate/solvers/second_order/newton_trust_region.jl#L268) may be what you want:

```jl
state.f_x_previous = value(d) # potentially value!(d,state.x)
copy!(state.x_previous, state.x)
```
to prevent an additional function evaluation. (See [NLSolversBase](https://github.com/JuliaNLSolvers/NLSolversBase.jl#single-valued-objectives) for documentation on `value`)


The methods that use a linesearch update `x_previous` in  `perform_linesearch`: https://github.com/JuliaNLSolvers/Optim.jl/blob/master/src/utilities/perform_linesearch.jl#L29

**Comment by jonathanBieler** [comment]
I've managed to fix some of these issues, I implemented `pick_best_f` and `pick_best_x` which fix my OptimizationResults, I also wasn't using `value!` to update my function and that was causing some problems.

For the convergence ideally one could display other conditions that the default ones (CMAES as a couple of conditions on the covariance matrix), but it's not that important.

**Comment by pkofod** [comment]
The last point is actially quite important to me as I want to moduralize this, so please show me what you could show in the beat of all worlds

**Comment by jonathanBieler** [comment]
Btw, would you like CMAES in Optim in the long term ? I think with the way it's done now it doesn't add much complication to use it as an independent package, but adding it in wouldn't be too complicated either.

**Comment by ChrisRackauckas** [comment]
I would like to see it. Random packages tend to get bitrot, while things inside of a common interface with an org tend to get upgrades. I think if you put CMAES then @antoine-levitt will come and add manifold support, you'll get complex number and numerical diff support, when linear solver swapping and sparse diff comes they'll sweep through and add it (whatever is applicable to this algorithm of course). Adding constraints and a MathOptInferface binding will also come naturally. 

I think you and @AStupidBear should double check each other's CMA/CMAES Julia implementations and see if they are in sync. If they are, then one into Optim would be my preferred choice.

**Comment by pkofod** [comment]
@jonathanBieler did you end up contributing to blackboxoptim instead?

**Comment by jonathanBieler** [comment]
@pkofod No I have my version here:

https://github.com/jonathanBieler/CMAES.jl

I never managed to make perform as well as the python version, there's several versions in the original papers so it's not super clear what is wrong.

**Comment by mohamed82008** [comment]
There is also an implementation in https://github.com/wildart/Evolutionary.jl.

**Comment by pkofod** [comment]
> I never managed to make perform as well as the python version, there's several versions in the original papers so it's not super clear what is wrong.

how much worse is it? is it in your blackboxoptimbenchmarks repo? I don't think so?

**Comment by jonathanBieler** [comment]
IIRC it was converging too fast and was failing on hard functions. It's not included in my blackboxoptimbenchmarks repo no. I can try to update it if you want, the code I've posted is a bit outdated and messy.
