### ISSUE TITLE
API

### ISSUE THREAD

**Issue by iwelch** [JuliaNLSolvers/Optim.jl#575]
I would suggest that the API offer an alternative to passing cache locations to gradients and hessians.  Logically, one wants a gradient and/or a Hessian at a point, and so one should give a point.  Ergo, the logical user-facing method should be `g(x)` and `OnceDifferentiable(g, n; type=Float64)`.  With a gc language, the allocation of the cache deeper inside is no longer an issue.

As it stands, it seems quixotic for a user to specify a value that is completely ignored.  Whether one provides '[-Inf,Inf]' or '[0.0,0.0]' always leads to the same result.  Instead, the user should specify what is **not** ignored.

Fortunately, this can be fixed trivially easily.  Just add a few more (logical) methods to the existing (efficiency-based) methods.  One for `g(Vector)` and `OnceDifferentiable( Function, Int; type=Float)` that invoke the existing ones.

Just a suggestion...

**Comment by anriseth** [comment]
Can I ask what you intend to do with the `OnceDifferentiable` objects? Currently they are designed for the internal workings of Optim, with an additional "autodiff"-feature to help the user create gradient evaluation methods with forward-mode differentiation or finite differences. 

The GradientConfig in ForwardDiff and GradientCache in DiffEqDiffTools need to be passed an object of the same type and size as `x`, so with your suggestion, we would still need to create an array internally.

Optim supports `x::AbstractArray`, which means that `x` does not necessarily have to be a `Vector{T}`,. How would your suggested API work with more exotic types such as n-dimensional arrays, tensors, or other types of `AbstractArray`s?

**Comment by iwelch** [comment]
Over my head.  I come from userland.  I am trying to pass my own symbolic derivatives for later use, following the instructions.

```
myfun(x)= (x[1]-2)^2 + (x[2]-3)^2 + ((x[1]-2)*(x[2]-3))^2;
myfungradients(x)= [ 2*(1 + (x[2]-3)^2)*(x[1]-2 ),  2*(1 + (x[1]-2)^2)*(x[2]-3) ]

function f(x) myfun(x) end#function
function g!(G,x) G=myfungradients(x) end#function

using Optim
od = OnceDifferentiable( f, g!, [0.0,0.0] )
```

what would have seemed more logical, on my side would have been

```
myfun(x)= (x[1]-2)^2 + (x[2]-3)^2 + ((x[1]-2)*(x[2]-3))^2;
myfungradients(x)= [ 2*(1 + (x[2]-3)^2)*(x[1]-2 ),  2*(1 + (x[1]-2)^2)*(x[2]-3) ]

using Optim
od = OnceDifferentiable( myfun, myfungradients, 2; type=Float64 )
```

because each and every input that I am passing in has a deliberate meaning to *me*, that I know the algorithm will need.

I don't know how it would work win other cases.

**Comment by anriseth** [comment]
I see that @mohmed82008 has explained on Discourse why Optim wants the gradient and Hessian to be mutable (that is, of the form `g!(storage, x)` :+1: 

Regarding optimization, you don't need to define a `OnceDifferentiable` object if you have already defined the gradient. (The exception is for `FMinbox`).
```jl
f(x) = # define function
g!(out, x) = #define gradient that stores the values in `out`
optimize(f, g!, x0, method())
```

As @pkofod mentioned we should probably make it easier to let the user ask `Optim` to use automatic differentiation when calling `optimize`.

**Comment by pkofod** [comment]
I will add `autodiff` and `inplace` keywords to optim as I did to nlsolve, see here https://github.com/JuliaNLSolvers/NLsolve.jl#with-functions-returning-residuals-and-jacobian-as-output

then you could write

```
f(x) = ...
g(x) = ...
optimize(f, g, x0, method; inplace = false)
```

**Comment by pkofod** [comment]
fixed with the `inplace` keyword many moons ago
