### ISSUE TITLE
wrong link in docs

### ISSUE THREAD

**Issue by iwelch** [JuliaNLSolvers/Optim.jl#578]
A simple way to get in touch, is to join our gitter channel.

a click on gitter tells me 404.

**Comment by pkofod** [comment]
It works here, can you confirm that it points to https://gitter.im/JuliaNLSolvers/Optim.jl ?

**Comment by iwelch** [comment]
link at http://julianlsolvers.github.io/Optim.jl/latest/dev/contributing/ leads to

https://gitter.im/JuliaOpt/Optim.jl

which leads to Gitter

404. This is not the chat you're looking for. Sorry. :(404. This is not the chat you're looking for. Sorry.

**Comment by pkofod** [comment]
Oh, in docs... good catch

**Comment by pkofod** [comment]
fixed, thanks
