### ISSUE TITLE
linesearch warning

### ISSUE THREAD

**Issue by iwelch** [JuliaNLSolvers/Optim.jl#579]
Suggestion:  I am doing experimentation about performance with some test functions.  `@btime`.  Unfortunately, because linesearch is used internally, my output ends up full of a few thousand

```
WARNING: Linesearch failed, using alpha = 0.1666510647579419 and exiting optimization.
```

can I suggest that this error should propagate up and just potentially cause the same (non-convergence) error like others?  from the user's perspective, they probably don't care about how the sausages are made internally.  either the solution is found or it is not.

if automatic suppression is not a good choice, could there be a user option to suppress its output?  (I was tempted to use Suppressor.jl, but then I was concerned that it could interfere with `@btime`.

**Comment by iwelch** [comment]
apologies, guys.  I know you are busy, but this would be very convenient if fixed.

**Comment by anriseth** [comment]
For reference, https://github.com/JuliaNLSolvers/Optim.jl/issues/263

We are open to handling errors in a different, coherent, way. This needs a proper proposal and someone's time. 

A quick fix may exist, such as a flag in options,. You can experiment with that and submit a pull request if you want.

**Comment by iwelch** [comment]
let me phrase it differently---it is a useful developer error message, but not necessarily enduser error message.

**Comment by anriseth** [comment]
Feel free to submit a PR if you find a good way of handling errors or suppressing messages when they are not wanted. 

> but not necessarily enduser error message.

I was speaking as an enduser when I said it has been very useful to me. I sometimes thousands of `optimize`-calls as part of larger problems and this tells me when something is wrong.


I would again like to stress that these warnings may indicate that you are trying to solve problems with unsuitable methods and that taking a step back and rethinking your testing approach.

**Comment by iwelch** [comment]
I think users need to rethink your function approach whenever they fail to converge---whether based on the linmin or some other issue.  it's the same thing.

I think there is a good choice here, and it would make Optim better all around.

right now, all default parameters are hardcoded.  for example, you have 1000 iterations.  Overrideable.  Good.  Alas, I would have an (overrideable) user-settable default.  For example, Optim.setdefault( iterations= 2_000, f_tol=1e-30 ).  This would generally be very convenient.

Now, one of these should be Optim.setdefault(linesearch_warnings=false).

and then, of course, in perform_linesearch.jl, line 55:

```
(linesearch_warnings) && Base.warn("Linesearch failed, using alpha = $(state.alpha) and exiting optimization.")
```

/iaw

**Comment by pkofod** [comment]
How is setdefault easier than Options(...)?

**Comment by iwelch** [comment]
does Optim.Options not have to be provided each time an optimize call is made.  but, indeed, this is trivial.

the real suggestion here is to make the linesearch_warnings a part of the Optim.Options() functionality.

**Comment by pkofod** [comment]
Sure, but is
```julia
opt = Optim.Options(; linesearch_warnings = false)
optimize(f1, x0, opt)
optimize(f2, x0, opt)
optimize(f3, x0, opt)
```
really that bad compared to
```julia
setdefault(;linesearch_warnings = false)
optimize(f1, x0)
optimize(f2, x0)
optimize(f3, x0)
```
?
If you only need to optimize one thing they're identical, but even if you optimize several things with the same options, you'd probably copy paste to some extent, so I don't really see the burden.

What we could do is to make something like this
```julia
default_opts = Optim.Options(; ...)
special_opts(default_opts; x_tol = 0.3)
```
where `special_opts` is then identical to `default_opts` for all options **besides** the ones specified by the keyword (x_tol here). That would make it easy for you to have some defaults that you could then update using the constructor `Options(o::Options; kwargs)`.

**Comment by iwelch** [comment]
as I said, it's a minor issue.  actually, it could even be that Optim.Options!() sets the (global) parameters, too.  then one can reinclude it or simply leave it.  but it's really unimportant.

the big one is to be able to set an option that linesearch will honor to turn off the warning 

/iaw
