### ISSUE TITLE
Credit

### ISSUE THREAD

**Issue by iwelch** [JuliaNLSolvers/Optim.jl#580]
gentlemen---

* you may want to add Mogensen, Patrick Kofod and Riseth, Asbj{\o}rn Nilsen to the (c) notice on the license on the http://julianlsolvers.github.io/Optim.jl/latest/LICENSE/ , and mention John Myles White at the github below the citation.  just a suggestion.

* also, there seems to be no link from the docs on the googled http://julianlsolvers.github.io/Optim.jl/latest/ to the github (and perhaps vice-versa).

* more importantly, I am planning to use Optim.jl quite a bit to see if I can invent improved ways to go about optimizing.   (can you please send me an email to ivo.welch@gmail.com so we can take some of this offline.)

to be clear, I do not expect bug-free Optim.jl.  I am fully aware that Optim is a work in progress.  still, having the base in julia itself is very appealing to me.

now, I may or may not be able to help you with my tests to find bugs, if there are some.  Please take a look at where I have gotten, so far:

http://julia.cookbook.tips/doku.php?id=optim-results

I am assuming you coded faithfully to the original algorithm.  I was surprised by a couple of aspects. 
 For example, how often even Nelder-Mead fails to find a good optimum given unlimited iterations.  

[you can delete this issue afterwards]

**Comment by pkofod** [comment]
> I am assuming you coded faithfully to the original algorithm. I was surprised by a couple of aspects.
> For example, how often even Nelder-Mead fails to find a good optimum given unlimited iterations.

Given the often nasty features of test problems (they're invented to challenge the algorithms!), I wouldn't be surprised in general, but there might of course be much room for improvement. Let's look at the specific problems, and see if there's something we can learn or improve. You say it surprises you, is this because other implementations do better? That would of course be a concern.

**Comment by anriseth** [comment]
> you may want to add Mogensen, Patrick Kofod and Riseth, Asbj{\o}rn Nilsen to the (c) notice on the license on the http://julianlsolvers.github.io/Optim.jl/latest/LICENSE/

The license file in the docs has not been updated. Thanks for pointing that out

> also, there seems to be no link from the docs on the googled http://julianlsolvers.github.io/Optim.jl/latest/ to the github

There is one at the bottom left of all the docs pages (it says GitHub). I'll see if I can make this more clear.
Re vice-versa, the table in the README has a badge "docs | stable" that takes you to the docs
