### ISSUE TITLE
ParticleSwarm Feeds NaN to Be Optimized

### ISSUE THREAD

**Issue by iwelch** [JuliaNLSolvers/Optim.jl#581]
See http://julia.cookbook.tips/doku.php?id=optim-results .  In the discfunnel (cliff funnel) examples, the particle swarm feeds NaN as x values.  Repeatable.

**Comment by pkofod** [comment]
You mean if an input isn't feasible (or returns NaN for some numerical reason) it keeps on propagating them forward in the calculations?

Cool tables btw, will be happy to look at the lessons we can learn from them

**Comment by iwelch** [comment]
no.  I mean your optimizer actually sends a vector of NaN's to my test function for evaluation.  that should never happen.

**Comment by pkofod** [comment]
That's what I meant. At some point an infeasible point is probably evaluated leading to a NaN, that probably propagates. If you disagree, you could try showing the trace and we can try to debug it.

**Comment by iwelch** [comment]
could be, but unlikely given the functions (then again, could be overflow).  the cases are in my output in the tables.  I will later try to play with a trace.

**Comment by anriseth** [comment]
I believe #583 fixes this. The error message was very helpful.

Two comments / questions regarding your cookbook:

- What is your intention of adding `x::Vector{Float64}` to your functions?
When I started using Julia, I added a lot of type information which turned out to be superfluous. In particular cases it actually slowed my code down (for example, using AbstractVector is the following fashion is bad, as the compiler cannot infer the type of a properly: `type Test ; a::AbstractVector{Float64} ; end` )
- There are a lot of assertions and other checks in your functions that will slow down the function evaluations, and hence your tests.

**Comment by iwelch** [comment]
these are test functions.  they are not supposed to be fast.  (in fact, they are standins for real-life problems that take much longer.)  what I want them to do is to alert me to problems, so the more tests, the better.

your code needs to run fast.  mine can be slow.  as long as it is equally slow for all optimizers, that is.

**Comment by iwelch** [comment]
I was not sure whether you wanted it.  It takes time to winnow it down.  Here it is

```
using Optim

function kinkyfunnel(x::Vector{Float64})::Float64
    onekinkyfunnel(x::Float64) = (1.01 + ((x<0) ? 1.0/(x-1) : -1.0/(x+1)))*10.0

    kc= onekinkyfunnel.(x)
    @assert( all( x ->(x>=0), kc ), "dc received bad input request $kc at $x" )

    rv= prod( kc )

    @assert( !isnan(rv), " returning an NaN!\n")

    rv
end#function

optimize( kinkyfunnel, zeros(2),  ParticleSwarm(), Optim.Options(iterations=1_000_000))
```

Let me know (email) when you have a natural breakpoint at which I should update my Optimum and run the tests again.   Afaik, you have added interface changes (kudos), and it makes more sense for me to work with something that is supposed to work, or else I don't know whether I am running into a transient or a real bug.  good?

**Comment by anriseth** [comment]
> I was not sure whether you wanted it. It takes time to winnow it down. Here it is

Your code works for me on `master`. Is the error in the unconstrained version, or the Fminbox version? In your cookbook, the errors you report are for the `Fminbox{ParticleSwarm}` examples if I remember correctly.

**Comment by iwelch** [comment]
```
julia> include("asserterror.jl")
INFO: Recompiling stale cache file /Users/ivo/.julia/lib/v0.6/Optim.ji for module Optim.
ERROR: LoadError: AssertionError: dc received bad input request [NaN, NaN] at [NaN, NaN]
Stacktrace:
 [1] kinkyfunnel(::Array{Float64,1}) at /Users/ivo/bitcookbook/asserterror.jl:7
 [2] value(::NLSolversBase.NonDifferentiable{Float64,Array{Float64,1},Val{false}}, ::Array{Float64,1}) at /Users/ivo/.julia/v0.6/NLSolversBase/src/interface.jl:19
 [3] compute_cost!(::NLSolversBase.NonDifferentiable{Float64,Array{Float64,1},Val{false}}, ::Int64, ::Array{Float64,2}, ::Array{Float64,1}) at /Users/ivo/.julia/v0.6/Optim/src/multivariate/solvers/zeroth_order/particle_swarm.jl:444
 [4] update_state!(::NLSolversBase.NonDifferentiable{Float64,Array{Float64,1},Val{false}}, ::Optim.ParticleSwarmState{Array{Float64,1},Float64}, ::Optim.ParticleSwarm{Any}) at /Users/ivo/.julia/v0.6/Optim/src/multivariate/solvers/zeroth_order/particle_swarm.jl:149
 [5] optimize(::NLSolversBase.NonDifferentiable{Float64,Array{Float64,1},Val{false}}, ::Array{Float64,1}, ::Optim.ParticleSwarm{Any}, ::Optim.Options{Float64,Void}, ::Optim.ParticleSwarmState{Array{Float64,1},Float64}) at /Users/ivo/.julia/v0.6/Optim/src/multivariate/optimize/optimize.jl:51
 [6] optimize(::Function, ::Array{Float64,1}, ::Optim.ParticleSwarm{Any}, ::Optim.Options{Float64,Void}) at /Users/ivo/.julia/v0.6/Optim/src/multivariate/optimize/interface.jl:73
 [7] include_from_node1(::String) at ./loading.jl:576
 [8] include(::String) at ./sysimg.jl:14
while loading /Users/ivo/bitcookbook/asserterror.jl, in expression starting on line 16
```

 - Optim                         0.14.1             6b412863 (dirty)  ## computer 1

 - Optim                         0.14.0+            master (dirty)  ## another computer---I had to take out the LINESEARCH warning , so I can't see the version.

both of them give the same error.  if you have fixed it in master, then you can close this one.  (I will see it again on my next full run-through if we are wrong here.  It won't be forgotten.  You can think of this is being one of my test units.)

**Comment by iwelch** [comment]
not sure what MWE is, but you have my 15-line code in one post and the reproducible error in the second post.

**Comment by pkofod** [comment]
I missed the most recent communication. Let’s see where things go wrong.

**Comment by anriseth** [comment]
> ERROR: LoadError: AssertionError: dc received bad input request [NaN, NaN] at [NaN, NaN]
Stacktrace:

If you remove the assertions you have in your functions, does it produce an error?

**Comment by pkofod** [comment]
No. At some point X gets populated with NaNs, and I'm trying to figure out why. Since NaNs won't produce an error anywhere, it'll just keep running and return the best guess for f  (which converges quickly, the iterations=1_000_000 is not necessary) at the end.

**Comment by anriseth** [comment]
Okay, so I don't get this error on my laptop, but do on my desktop. May it be a seed issue? I don't really understand the use case for these stochastic derivative-free algorithms - they seem overused for problems that are better solved with other methods.

**Comment by pkofod** [comment]
I found the source of the nan, it’s a division problem when the change in the swarm is zero. I’ll try to put in a safe guard

**Comment by pkofod** [comment]
@iwelch 
```
julia> optimize( kinkyfunnel, zeros(2),  ParticleSwarm(), Optim.Options(iterations=1_000_000))
Results of Optimization Algorithm
 * Algorithm: Particle Swarm
 * Starting Point: [0.0,0.0]
 * Minimizer: [2.964750152563214e-17,1.7853292341074152e-17, ...]
 * Minimum: 1.000000e-02
 * Iterations: 1000000
 * Convergence: false
   * |x - x'| ≤ 1.0e-32: false 
     |x - x'| = NaN 
   * |f(x) - f(x')| ≤ 1.0e-32 |f(x)|: false
     |f(x) - f(x')| = NaN |f(x)|
   * |g(x)| ≤ 1.0e-08: false 
     |g(x)| = NaN 
   * Stopped by an increasing objective: false
   * Reached Maximum Number of Iterations: true
 * Objective Calls: 3999830
 * Gradient Calls: 0
```

**Comment by pkofod** [comment]
please reopen if the error reappears - this is fixed on master.
