### ISSUE TITLE
See if we can learn from Ivo's benchmarks

### ISSUE THREAD

**Issue by pkofod** [JuliaNLSolvers/Optim.jl#593]
http://julia.cookbook.tips/doku.php?id=optim-results

**Comment by pkofod** [comment]
Ivo, can you maybe comment on the following? 

Newton looks like it fails in your examples for vfun. If you allow for f to increase, it looks like it gets it right. @anriseth has previously talked about allowing f to increase, and maybe we should. Notice I let it run until g tol = 0.0
```

julia> optimize(vfun, rand(10)*10, Newton(), Optim.Options(allow_f_increases=true, g_tol=0.0))
Results of Optimization Algorithm
 * Algorithm: Newton's Method
 * Starting Point: [1.4713087450008633,9.72681922034744, ...]
 * Minimizer: [-2.0184848174601398e-6,-2.018484817466573e-6, ...]
 * Minimum: 1.000020e+00
 * Iterations: 208
 * Convergence: true
   * |x - x'| ≤ 1.0e-32: false 
     |x - x'| = 7.59e-17 
   * |f(x) - f(x')| ≤ 1.0e-32 |f(x)|: true
     |f(x) - f(x')| = 0.00e+00 |f(x)|
   * |g(x)| ≤ 0.0e+00: true 
     |g(x)| = 0.00e+00 
   * Stopped by an increasing objective: false
   * Reached Maximum Number of Iterations: false
 * Objective Calls: 3806
 * Gradient Calls: 3806
 * Hessian Calls: 208
 ```

**Comment by antoine-levitt** [comment]
Can't HZ be coerced into always returning something if the direction is a direction of descent?

**Comment by anriseth** [comment]
> Can't HZ be coerced into always returning something if the direction is a direction of descent?

Maybe it relies on some smoothness assumption? In any case, there's a `linesearchmax = 50` which sets the maximum number of iterations in each line search, so I guess it hits that and then you end up with a `f_increased`.
