### ISSUE TITLE
Complex manifolds ?

### ISSUE THREAD

**Issue by stumarcus576** [JuliaNLSolvers/Optim.jl#611]
Do the Optim manifolds accept complex inputs, e.g. to model the complex circle?

**Comment by antoine-levitt** [comment]
Yes, see the docs, and the example here: https://github.com/JuliaNLSolvers/Optim.jl/blob/master/test/multivariate/manifolds.jl. Feel free to report if something does not work as expected.

**Comment by pkofod** [comment]
@anriseth @iewaij we should try to Literate.jl this example and include it in the docs!

**Comment by stumarcus576** [comment]
Is it correct that optimization problems defined on Optim manifolds can only be solved with first-order solvers? Trust region solvers are not supported if the domain is a real or complex Optim manifold?

**Comment by antoine-levitt** [comment]
That's right. It mostly reflects my own interests rather than any fundamental limitations ;-) Also, for second-order methods I'm not sure how competitive Riemannian methods are compared to constrained solvers. What's your use-case ?

**Comment by stumarcus576** [comment]
I was interested in minimizing a real-valued function defined on n copies of the complex circle. Alternatively, the problem can be solved over R^n by making the unknowns the phases of the unit magnitude complex numbers, though this makes the objective function more complicated.

**Comment by antoine-levitt** [comment]
I think your best bet is to solve for the phases. Otherwise, you can use the Product manifold to make copies of the Sphere manifold and that will get you what you want, although second-order methods are not implemented.
