### ISSUE TITLE
Allow for hessian to be updated upon convergence

### ISSUE THREAD

**Issue by pkofod** [JuliaNLSolvers/Optim.jl#629]
For problems like maximum likelihood you may want the hessian in a `TwiceDifferentiable` to be updated at convergence. We should provide a switch.

**Comment by priamfive** [comment]
This would be helpful.  I have been puzzling why I seemed to obtained something which was clearly not the Hessian matrix (e.g. not symmetric) when following the steps in the documentation and think I have discovered why.

The documentation under Maximum Likelihood says that if you are minimizing func and want the hessian at convergence you can obtain it by 
                       ```numerical_hessian = hessian!(func,parameters)```
        To be sure of obtaining the correct object I think you actually need `hessian!!`
                      ``` numerical_hessian = hessian!!(func,parameters)```
`hessian!!` forces re-evaluation but `hessian!` checks if the value requested is the previous point the hessian was evaluated at and only re-evaluates if it isn't (code in interface.jl in NLSolversBase)
                   ```function hessian!(obj::AbstractObjective, x)
                            if x != obj.x_h
                            hessian!!(obj, x)
                             end
                           hessian(obj)
                           end```
      This may seem sensible but it seems that what is held in the Hessian field is not always the Hessian. In the Newton algorithm the line
                   ```state.F = cholesky!(Positive, NLSolversBase.hessian(d))```
     seems to store the Cholesky decomposition in the Hessian field.  Calling `hessian!(func,parameters)` if the this step has been executed at `parameters` will yield this object not the Hessian.

**Comment by pkofod** [comment]
Aha, that’s a great observation. Yes that factorization happens in place. I hope to make some improvements around hessian approximations and linsolves I’m general, so stay tuned. For now we should just improve docs
