### ISSUE TITLE
Project manifold tangent when we reset search direction

### ISSUE THREAD

**Issue by anriseth** [JuliaNLSolvers/Optim.jl#649]
If (L)BFGS or CG proposes a direction with is not a direction of descent, we reset the search direction using the gradient, see
https://github.com/JuliaNLSolvers/Optim.jl/blob/492454088e6dd9a32c90bfa3940a2ed252b38012/src/utilities/perform_linesearch.jl#L26.

For manifolds to still behave as we want them to on these algorithms, we should therefore call `project_tangent!` on the new search direction given by the gradient.

**Comment by pkofod** [comment]
I think this is incorrect, because we've projected just after the evaluation of the gradient, so closing, but I'm adding a comment right away.
