### ISSUE TITLE
Julia 1.0 Problem with @printf

### ISSUE THREAD

**Issue by iwelch** [JuliaNLSolvers/Optim.jl#655]
under julia 1.0, @printf does not seem to be defined.

```
optimize( avgobj, initval; show_trace=true )

ERROR: LoadError: LoadError: LoadError: UndefVarError: @printf not defined
 [5] include(::String) at /Users/ivo/.julia/packages/Optim/5JqO8/src/Optim.jl:18
```

**Comment by anriseth** [comment]
Optim has not been updated for Julia 1.0 yet. We're almost there, see https://github.com/JuliaNLSolvers/Optim.jl/pull/643

In the future, can you please include the version of Optim you're using when you have an issue?

**Comment by anriseth** [comment]
Regarding printf: I think you need load it by `using Printf`. (I'm away from my laptop for another week, so somebody correct me if I'm wrong)

Many features were moved out of base in Julia 1.0.

**Comment by pkofod** [comment]
Optim is ready, we just need to tag and publish

**Comment by brilhana** [comment]
@anriseth is correct, `using Printf` is indeed needed.

**Comment by pkofod** [comment]
https://github.com/JuliaNLSolvers/Optim.jl/pull/643#issuecomment-412323218
https://github.com/JuliaLang/METADATA.jl/pull/16707

**Comment by pkofod** [comment]
Should work now
