### ISSUE TITLE
Julia 0.7 win7 64 error

### ISSUE THREAD

**Issue by programistawpf** [JuliaNLSolvers/Optim.jl#657]
Julia 0.7 win7 64 error
D:\pawel\Julia_7.0_otwarty>C:\Users\PC\AppData\Local\Julia-0.7.0\bin\julia.exe -L start.jl

               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.7.0 (2018-08-08 06:46 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> using Optim

julia> rosenbrock(x) =  (1.0 - x[1])^2 + 100.0 * (x[2] - x[1]^2)^2
rosenbrock (generic function with 1 method)

julia> result = optimize(rosenbrock, zeros(2), BFGS())
WARNING: importing deprecated binding Base.eye into Optim.
WARNING: Base.eye is deprecated: it has been moved to the standard library package `LinearAlgebra`.
Add `using LinearAlgebra` to your imports.
 in module Optim
WARNING: Base.eye is deprecated: it has been moved to the standard library package `LinearAlgebra`.
Add `using LinearAlgebra` to your imports.
 in module Optim
WARNING: Base.eye is deprecated: it has been moved to the standard library package `LinearAlgebra`.
Add `using LinearAlgebra` to your imports.
 in module Optim
WARNING: importing deprecated binding Base.vecnorm into Optim.
WARNING: Base.vecnorm is deprecated: it has been moved to the standard library package `LinearAlgebra`.
Add `using LinearAlgebra` to your imports.
 in module Optim
WARNING: Base.vecnorm is deprecated: it has been moved to the standard library package `LinearAlgebra`.
Add `using LinearAlgebra` to your imports.
 in module Optim
WARNING: Base.vecnorm is deprecated: it has been moved to the standard library package `LinearAlgebra`.
Add `using LinearAlgebra` to your imports.
 in module Optim
WARNING: importing deprecated binding Base.STDOUT into Optim.
WARNING: Base.vecnorm is deprecated: it has been moved to the standard library package `LinearAlgebra`.
Add `using LinearAlgebra` to your imports.
 in module Optim
WARNING: importing deprecated binding Base.scale! into Optim.
WARNING: Base.scale! is deprecated: it has been moved to the standard library package `LinearAlgebra`.
Add `using LinearAlgebra` to your imports.
 in module Optim
WARNING: importing deprecated binding Base.vecdot into Optim.
WARNING: Base.vecdot is deprecated: it has been moved to the standard library package `LinearAlgebra`.
Add `using LinearAlgebra` to your imports.
 in module Optim
WARNING: Base.vecdot is deprecated: it has been moved to the standard library package `LinearAlgebra`.
Add `using LinearAlgebra` to your imports.
 in module Optim
WARNING: Base.vecdot is deprecated: it has been moved to the standard library package `LinearAlgebra`.
Add `using LinearAlgebra` to your imports.
 in module Optim
WARNING: Base.vecdot is deprecated: it has been moved to the standard library package `LinearAlgebra`.
Add `using LinearAlgebra` to your imports.
 in module Optim
WARNING: Base.scale! is deprecated: it has been moved to the standard library package `LinearAlgebra`.
Add `using LinearAlgebra` to your imports.
 in module Optim
WARNING: Base.scale! is deprecated: it has been moved to the standard library package `LinearAlgebra`.
Add `using LinearAlgebra` to your imports.
 in module Optim
WARNING: Base.vecnorm is deprecated: it has been moved to the standard library package `LinearAlgebra`.
Add `using LinearAlgebra` to your imports.
 in module Optim
WARNING: Base.vecnorm is deprecated: it has been moved to the standard library package `LinearAlgebra`.
Add `using LinearAlgebra` to your imports.
 in module Optim
WARNING: Base.vecdot is deprecated: it has been moved to the standard library package `LinearAlgebra`.
Add `using LinearAlgebra` to your imports.
 in module Optim
WARNING: Base.vecdot is deprecated: it has been moved to the standard library package `LinearAlgebra`.
Add `using LinearAlgebra` to your imports.
 in module Optim
WARNING: Base.vecdot is deprecated: it has been moved to the standard library package `LinearAlgebra`.
Add `using LinearAlgebra` to your imports.
 in module Optim
WARNING: Base.vecdot is deprecated: it has been moved to the standard library package `LinearAlgebra`.
Add `using LinearAlgebra` to your imports.
 in module Optim
WARNING: Base.vecnorm is deprecated: it has been moved to the standard library package `LinearAlgebra`.
Add `using LinearAlgebra` to your imports.
 in module Optim
WARNING: Base.vecnorm is deprecated: it has been moved to the standard library package `LinearAlgebra`.
Add `using LinearAlgebra` to your imports.
 in module Optim
WARNING: Base.vecnorm is deprecated: it has been moved to the standard library package `LinearAlgebra`.
Add `using LinearAlgebra` to your imports.
 in module Optim
WARNING: Base.vecnorm is deprecated: it has been moved to the standard library package `LinearAlgebra`.
Add `using LinearAlgebra` to your imports.
 in module Optim
WARNING: Base.vecnorm is deprecated: it has been moved to the standard library package `LinearAlgebra`.
Add `using LinearAlgebra` to your imports.
 in module Optim
in optimize at C:\Users\PC\.julia\packages\Optim\5JqO8\src\multivariate\optimize\optimize.jl
WARNING: Base.vecnorm is deprecated: it has been moved to the standard library package `LinearAlgebra`.
Add `using LinearAlgebra` to your imports.
 in module Optim
in trace! at C:\Users\PC\.julia\packages\Optim\5JqO8\src\multivariate\solvers\first_order\bfgs.jl
WARNING: Base.STDOUT is deprecated, use stdout instead.
 in module Optim
in update! at C:\Users\PC\.julia\packages\Optim\5JqO8\src\utilities\update.jl
WARNING: Base.scale! is deprecated: it has been moved to the standard library package `LinearAlgebra`.
Add `using LinearAlgebra` to your imports.
 in module Optim
in update_state! at C:\Users\PC\.julia\packages\Optim\5JqO8\src\multivariate\solvers\first_order\bfgs.jl
WARNING: Base.vecdot is deprecated: it has been moved to the standard library package `LinearAlgebra`.
Add `using LinearAlgebra` to your imports.
 in module Optim
in perform_linesearch! at C:\Users\PC\.julia\packages\Optim\5JqO8\src\utilities\perform_linesearch.jl
WARNING: Base.vecdot is deprecated: it has been moved to the standard library package `LinearAlgebra`.
Add `using LinearAlgebra` to your imports.
 in module Optim
in perform_linesearch! at C:\Users\PC\.julia\packages\Optim\5JqO8\src\utilities\perform_linesearch.jl
WARNING: Base.vecnorm is deprecated: it has been moved to the standard library package `LinearAlgebra`.
Add `using LinearAlgebra` to your imports.
 in module Optim
in optimize at C:\Users\PC\.julia\packages\Optim\5JqO8\src\multivariate\optimize\optimize.jl
WARNING: Base.vecnorm is deprecated: it has been moved to the standard library package `LinearAlgebra`.
Add `using LinearAlgebra` to your imports.
 in module Optim
in default_convergence_assessment at C:\Users\PC\.julia\packages\Optim\5JqO8\src\utilities\assess_convergence.jl

WARNING: Base.vecdot is deprecated: it has been moved to the standard library package `LinearAlgebra`.
Add `using LinearAlgebra` to your imports.
 in module Optim
in update_h! at C:\Users\PC\.julia\packages\Optim\5JqO8\src\multivariate\solvers\first_order\bfgs.jl
WARNING: Base.vecdot is deprecated: it has been moved to the standard library package `LinearAlgebra`.
Add `using LinearAlgebra` to your imports.
 in module Optim
in update_h! at C:\Users\PC\.julia\packages\Optim\5JqO8\src\multivariate\solvers\first_order\bfgs.jl
┌ Warning: `eye(T::Type, m::Integer)` has been deprecated in favor of `I` and `Matrix` constructors. For a direc
t replacement, consider `Matrix{T}(I, m, m)`. If `T` element type is not necessary, consider the shorter `Matrix
(I, m, m)`(with default `eltype(I)` `Bool`)
│   caller = ip:0x0
└ @ Core :-1
┌ Warning: `vecnorm` is deprecated, use `norm` instead.
│   caller = initial_convergence at optimize.jl:26 [inlined]
└ @ Core C:\Users\PC\.julia\packages\Optim\5JqO8\src\multivariate\optimize\optimize.jl:26
┌ Warning: `vecnorm` is deprecated, use `norm` instead.
│   caller = trace!(::Array{OptimizationState{Float64,BFGS{LineSearches.InitialStatic{Float64},LineSearches.Hage
rZhang{Float64,Base.RefValue{Bool}},getfield(Optim, Symbol("##17#19"))}},1}, ::OnceDifferentiable{Float64,Array{
Float64,1},Array{Float64,1}}, ::Optim.BFGSState{Array{Float64,1},Array{Float64,2},Float64,Array{Float64,1}}, ::I
nt64, ::BFGS{LineSearches.InitialStatic{Float64},LineSearches.HagerZhang{Float64,Base.RefValue{Bool}},getfield(O
ptim, Symbol("##17#19"))}, ::Optim.Options{Float64,Nothing}) at bfgs.jl:143
└ @ Optim C:\Users\PC\.julia\packages\Optim\5JqO8\src\multivariate\solvers\first_order\bfgs.jl:143
ERROR: UndefVarError: A_mul_B! not defined
Stacktrace:
 [1] update_state!(::OnceDifferentiable{Float64,Array{Float64,1},Array{Float64,1}}, ::Optim.BFGSState{Array{Floa
t64,1},Array{Float64,2},Float64,Array{Float64,1}}, ::BFGS{LineSearches.InitialStatic{Float64},LineSearches.Hager
Zhang{Float64,Base.RefValue{Bool}},getfield(Optim, Symbol("##17#19"))}) at C:\Users\PC\.julia\packages\Optim\5Jq
O8\src\multivariate\solvers\first_order\bfgs.jl:87
 [2] optimize(::OnceDifferentiable{Float64,Array{Float64,1},Array{Float64,1}}, ::Array{Float64,1}, ::BFGS{LineSe
arches.InitialStatic{Float64},LineSearches.HagerZhang{Float64,Base.RefValue{Bool}},getfield(Optim, Symbol("##17#
19"))}, ::Optim.Options{Float64,Nothing}, ::Optim.BFGSState{Array{Float64,1},Array{Float64,2},Float64,Array{Floa
t64,1}}) at C:\Users\PC\.julia\packages\Optim\5JqO8\src\multivariate\optimize\optimize.jl:57
 [3] optimize at C:\Users\PC\.julia\packages\Optim\5JqO8\src\multivariate\optimize\optimize.jl:33 [inlined]
 [4] #optimize#87(::Bool, ::Symbol, ::Function, ::Function, ::Array{Float64,1}, ::BFGS{LineSearches.InitialStati
c{Float64},LineSearches.HagerZhang{Float64,Base.RefValue{Bool}},getfield(Optim, Symbol("##17#19"))}, ::Optim.Opt
ions{Float64,Nothing}) at C:\Users\PC\.julia\packages\Optim\5JqO8\src\multivariate\optimize\interface.jl:114
 [5] optimize(::Function, ::Array{Float64,1}, ::BFGS{LineSearches.InitialStatic{Float64},LineSearches.HagerZhang
{Float64,Base.RefValue{Bool}},getfield(Optim, Symbol("##17#19"))}, ::Optim.Options{Float64,Nothing}) at C:\Users
\PC\.julia\packages\Optim\5JqO8\src\multivariate\optimize\interface.jl:113 (repeats 2 times)
 [6] top-level scope at none:0

julia>

Paul

**Comment by anriseth** [comment]
What version of Optim are you using?

master should work with Julia 1.0 as of this morning 

Version 0.16 is being tagged soon, see https://github.com/JuliaLang/METADATA.jl/pull/16707

**Comment by programistawpf** [comment]
[429524aa] Optim v0.15.3
Paul

W dniu 2018-08-12 o 12:01, Asbjørn Nilsen Riseth pisze:

**Comment by pkofod** [comment]
Yes, please wait for https://github.com/JuliaLang/METADATA.jl/pull/16707 . That is the PR that will bring Optim to v0.7 and v1.0! Thanks for your patience.

**Comment by pkofod** [comment]
Should work now
