### ISSUE TITLE
Documenting solver and linesearch choices

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaNLSolvers/Optim.jl#665]
Doc issue split off from https://github.com/JuliaNLSolvers/Optim.jl/pull/663.

Regardless of the defaults, we should at some point explain what solver/linesearches to use and when. There also seems to be regular discussions on discourse on gradients (analytical, finite diff, autodiff) and how to take gradients of complicated functions (eg eigenvectors). It would be good to link to https://math.mit.edu/~stevenj/18.336/adjoint.pdf here.

I was thinking two sections "gradient and hessians" and "advice on algorithms" between "minimizing a function" and "configurable options". If people think this is a good idea I can do a PR.

**Comment by anriseth** [comment]
Thumbs up :)
