### ISSUE TITLE
CG errors when current and previous gradients are the same

### ISSUE THREAD

**Issue by mohamed82008** [JuliaNLSolvers/Optim.jl#669]
I tracked down a bug that happens due to these 2 lines:

https://github.com/JuliaNLSolvers/Optim.jl/blob/e12fdbf1a64b8c28df42289d8a962d55b2327e18/src/multivariate/solvers/first_order/cg.jl#L178

https://github.com/JuliaNLSolvers/Optim.jl/blob/e12fdbf1a64b8c28df42289d8a962d55b2327e18/src/multivariate/solvers/first_order/cg.jl#L183

So when `gradient(d)` and `state.g_previous` are the same, `betak` will be `NaN` and that will result in a `NaN`s search direction which will corrupt the next line search. Interestingly, the backtracking line search still "succeeds" but gives a `NaN` step which gives a `NaN`s `x` which gives a `NaN`s objective which is caught by this line:

https://github.com/JuliaNLSolvers/Optim.jl/blob/e12fdbf1a64b8c28df42289d8a962d55b2327e18/src/multivariate/solvers/first_order/cg.jl#L164

**Comment by mohamed82008** [comment]
MWE:

```julia
julia> using Optim

julia> f(x) = 100 - x[1] + e^(x[1] - 100)
f (generic function with 1 method)

julia> g(grad, x) = grad[1] = -1 + e^(x[1] - 100)
g (generic function with 1 method)

julia> optimize(f, g, [0.0], ConjugateGradient(alphaguess=Optim.InitialStatic(alpha=1.0), linesearch=Optim.BackTracking()))
```

**Comment by antoine-levitt** [comment]
Related discussions in https://github.com/JuliaNLSolvers/Optim.jl/issues/669

**Comment by mohamed82008** [comment]
I think you made a typo, this is #669.

**Comment by anriseth** [comment]
I had a quick look at the HZ paper ("Limited memory conjugate gradient method", 2012); and I can't see any reference to how they handle `y_k=0`. The only thing I can think about is that they are using a "nanmath" assumption in the `max` statement of (2.10), and hence we should probably just use `NaNMath.max` in
https://github.com/JuliaNLSolvers/Optim.jl/blob/e12fdbf1a64b8c28df42289d8a962d55b2327e18/src/multivariate/solvers/first_order/cg.jl#L184

**Comment by mohamed82008** [comment]
>  hence we should probably just use NaNMath.max

This solves the MWE.

**Comment by anriseth** [comment]
Another alternative would be to say that we have hit an undefined situation in the CG algorithm, and must reset the algorithm (set `beta=0`). 

I don't know what would be the preferred option here. @mohamed82008 yields the best result in your case?

**Comment by mohamed82008** [comment]
For the MWE, the second option is faster. In my use case, both don't error but there are other problems going on there so I can't properly compare them just yet.

**Comment by pkofod** [comment]
Ah, I see. Wow, really the exact same gradient? For different `x`?

**Comment by mohamed82008** [comment]
Ya this possible for very badly conditioned functions like the MWE above, which has a term `e^(-100)` at the initial `x` but is otherwise linear. The nonlinearity starts showing up as you move against the gradient.

**Comment by pkofod** [comment]
Well, you certainly always do provide us with excellent edge cases :) Did you move past the "other probems"?

**Comment by mohamed82008** [comment]
> Well, you certainly always do provide us with excellent edge cases :)
Unfortunately for me :) 
> Did you move past the "other probems"?
Not yet, seems to be a tolerance issue.

**Comment by mohamed82008** [comment]
I think the `NaNMath` approach now works better for me.
