### ISSUE TITLE
User experience for univariate optimization

### ISSUE THREAD

**Issue by OvidiusCicero** [JuliaNLSolvers/Optim.jl#672]
In the moment optimizing a univariate problem from a starting point  requires this (trivial example of a parabola):

    optimize(x->x[1]^2,[1.0], BFGS())

First of all consider this: (EDITED)

    optimize(x->x[1]^2,[1.0])

This will fail since the default algorithm is only univariate so another algorithm explicitly needs to be specified. It would be nice if `optimize` would check whether the problem is one-dimensional and change the algorithm then.

Also, it would be nice to be able to write the problem without vectors like this:

    optimize(x->x^2,1.0)

which seemingly is not supported

**Comment by anriseth** [comment]
Your first and second code lines are exactly the same?

In any case, Optim provides two univariate optimization focused algorithms, Brent and GoldenRatio, which both require bounds. I understand that it may feel convenient to be able to write `optimize(x-x^2, 1.0)`, but it adds more code trying to "guess" what the user wants, and is prone to be forgotten when the general code base is changed.

**Comment by pkofod** [comment]
This is somewhat related to the discussions about StaticArrays (and StaticOptim). The most annoying thing as developers and maintainers is that there's no unified syntax for working on scalars or immutables and inplace operations for mutable arrays.

```
x .= x.*y .+ z
```
will fail for numbers and static arrays. We're working on this (though I have little time these days), but it requires a complete separate version of basically all code in Optim, so there are also maintenance issues involved.

Happy to take help :)

If you instead mean that it would be nice if Optim automatically wrapped what you said with functions and vectors I think that that is a bad idea. It gives the impressions that you're working with efficient immutable operations, while you're not. But as I said, I'm happy to do it if we can use the StaticArrays-compliant code..

**Comment by antoine-levitt** [comment]
Hm that is indeed annoying. But with a mutating code, don't you get most of the benefits of static arrays with the mutable (MArray) version?

**Comment by OvidiusCicero** [comment]
I see the problem of not being able to write two versions of the code since Julia does not allow that.
But what about a function (as mentioned above)

    function optimize_1dim(f,x0,method=BFGS())
         optimize(f(x[1], [x0], method)
    end

, maybe also as a overload to `optimize`?

We do talk only about cosmetic stuff but it was a bit nasty for me to run into this at the beginning

**Comment by pkofod** [comment]
I understand where you’re coming from, I just feel like it sells the wrong impression: that you’re getting an efficient scalar implementation.

**Comment by ChrisRackauckas** [comment]
>But with a mutating code, don't you get most of the benefits of static arrays with the mutable (MArray) version?

A lot, but not entirely. It's still enough of an issue that DiffEq has two implementations of the internals for each algorithm to accommodate for mutating vs non-mutating types.

**Comment by pkofod** [comment]
This will be fixed with the NLSolvers.jl backend, but won't be fixed in this version of the code.
