### ISSUE TITLE
No trace for `NelderMead()`

### ISSUE THREAD

**Issue by briochemc** [JuliaNLSolvers/Optim.jl#678]
The NelderMead algorithm does not fill in the trace when asked in the options. MWE (julia v0.7): 
```julia
using Optim
f(x) = (1.0 - x[1])^2 + 100.0 * (x[2] - x[1]^2)^2 # Rosenbrock function
opt = Optim.Options(store_trace = true, show_trace = false, extended_trace = true)
results = optimize(f, [0.0, 0.0], NelderMead(), opt)
Optim.x_trace(results)
```
gives the following error:
```julia
ERROR: Trace does not contain x. To get a trace of x, run optimize() with extended_trace = true
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] x_trace(::Optim.MultivariateOptimizationResults{NelderMead{Optim.AffineSimplexer,Optim.AdaptiveParameters},Float64,Array{Float64,1},Float64,Float64,Array{OptimizationState{Float64,NelderMead{Optim.AffineSimplexer,Optim.AdaptiveParameters}},1}}) at /Users/benoitpasquier/.julia/packages/Optim/U0b9c/src/api.jl:28
 [3] top-level scope at none:0
```

**Comment by anriseth** [comment]
If I understand NelderMead correctly, it does not have a particular `x` in the same way as the derivative-based algorithms. What decision variable are you interested in? If it is the centroid you're after, a temporary fix would be to do this:
```julia
[ state.metadata["centroid"] for state in results.trace ]
```

If `centroid` is the sensible thing to access, then we should implement an API call for that. If not, let us know what type of decision variable in the NM algorithm you want and we can add that to the trace.

**Comment by briochemc** [comment]
Oh I see and this makes sense. Your suggestion about the centroids makes a lot of sense. Otherwise I guess I was simply expecting a list of `x` values where `f` is evaluated? And now that I looked into it, I feel like having a list of the simplexes would also make sense.

Either way, the`ERROR` message should be changed, right? (Currently it suggests to use the `extended_trace = true` option but this was not the issue in this case)

**Comment by anriseth** [comment]
Returning the simplexes would probably contain more of the relevent info, yes. Can you play with what you need for the extended trace and add a PR, please? (I'm away from my computer for most of the tone until October, and then I'm staying a new job). I believe a revamp of the tracing code has been on the to-do list for a long time, albeit not a high priority.

It may be that more custom tracing could be better implemented with a callback. An [example of how they work](http://julianlsolvers.github.io/Optim.jl/stable/#user/tipsandtricks/#early-stopping) is in the docs. @pkofod is better suited to help you here :p

Regarding the error message, yes, that would be fixed. It may be that the same problem appears for all the derivative free algorithms (haven't checked add I'm on my phone)

**Comment by pkofod** [comment]
It already saves the centroid if you use `extended_trace`. The problem of saving the full collection of simpleces is that it is potentially very memory intensive (each step requires a `n x (n+1)` matrix where `n=length(x)`).

**Comment by pkofod** [comment]
It would however be super cool if these differences across methods was documented in the docstrings. Then `?NelderMead` could have a section on what to expect to find in the trace-
