### ISSUE TITLE
updating MLE notebook for 0.7+

### ISSUE THREAD

**Issue by fpmenninger** [JuliaNLSolvers/Optim.jl#680]
add packages Random and LinearAlgebra to the 'using' statement
change 'srand(0)' to 'Random.seed!(0)'
(diag has moved to the LinearAlgebra package)

**Comment by anriseth** [comment]
The diag part is fixed in the latest release, but if you can make a PR with other changes we'd appreciate that very much :)

**Comment by pkofod** [comment]
This is fixed on master.
