### ISSUE TITLE
Package compatibility caps

### ISSUE THREAD

**Issue by KZiemian** [JuliaNLSolvers/Optim.jl#681]
Ref: https://discourse.julialang.org/t/package-compatibility-caps/15301

**Comment by pkofod** [comment]
I think Asbjørn was really asking a slightly different question: why did you open this issue?

**Comment by ChrisRackauckas** [comment]
These were opened on every Julia package, regardless of if it was actually effected by the caps. This can probably be closed since Optim shouldn't have an issue with it or any of its dependencies.

**Comment by pkofod** [comment]
Thanks for notifying us @KZiemian but I think we're good wrt versions.
