### ISSUE TITLE
Rename `optimize` to `minimize`?

### ISSUE THREAD

**Issue by cossio** [JuliaNLSolvers/Optim.jl#685]
Now that there is a `maximize`, I think it makes sense to rename `optimize` to `minimize`.

**Comment by pkofod** [comment]
Thought it was unnecessary, but it might make sense to be explicit. It's not top priority, and would have to be deprecated very carefully.

**Comment by Nosferican** [comment]
Maybe something to keep in mind with the re-write.

**Comment by pkofod** [comment]
It is on my mind :)

**Comment by cossio** [comment]
Is there something to read about what to expect from the coming re-write of Optim?

**Comment by pkofod** [comment]
Won't happen in this version of Optim, but it'll be in NLSolvers.jl for example https://github.com/pkofod/NLSolvers.jl/blob/bc8b1941218fea9349dc9797ed32bb577c59289c/src/optimize/problem_types.jl#L33
