### ISSUE TITLE
Pass linesearch options to fminbox()

### ISSUE THREAD

**Issue by gregorykimmel** [JuliaNLSolvers/Optim.jl#693]
I  would like to know how to change the linesearch method and number of maximum iterations when using Fminbox(). I could not find any tips from the documentation.

results = optimize(cost_function, lower, upper,initparams,Fminbox())

**Comment by pkofod** [comment]
What kind of restriction do you want to go place on the iterations? Line search is controlled by the inner optimizer `Fminbox(BFGS(linesearch=...))` . Both things should be in the docs under box constrained optimization.

**Comment by gregorykimmel** [comment]
I don't see in the docs where there is a configurable options page for either linesearch.jl or in optim.jl. My question wasn't specific enough though. I'd like to change the maximum number of linesearch max iterations using Fminbox.

┌ Warning: Linesearch failed, using alpha = 0.002085087167607069 and exiting optimization.
│ The linesearch exited with message:
│ Linesearch failed to converge, reached maximum iterations 50.
└ @ Optim ~/.julia/packages/Optim/U0b9c/src/utilities/perform_linesearch.jl:47

**Comment by pkofod** [comment]
The line search options are always passed to optimizers: BFGS, GradientDescent, whatever. Fminbox takes in one of these, so you need to say `Fminbox(WhatEverOptimizer(linesearch=...)`. 

In this case (if you're using BFGS, say):
```
using LineSearches
inner_method = BFGS(linesearch=LineSearches.HagerZhang(linesearchmax=200))
box_method = Fminbox(inner_method)
optimize(..., box_method)
```

**Comment by gregorykimmel** [comment]
Perfect! That worked, I apologize but could you link where in the docs page this option is, so if I want to make any other modifications to parameters I can?

I couldn't find anything here: https://julianlsolvers.github.io/LineSearches.jl/latest/index.html

**Comment by pkofod** [comment]
Yes, the actual line searches are not well documented. The closest place would be in the actual source https://github.com/JuliaNLSolvers/LineSearches.jl/blob/fae0768f4a79d1fec637a53104c24d4761312abe/src/hagerzhang.jl#L90

However, it would be great to have the different options in the doc strings.

**Comment by pkofod** [comment]
We could leave this open to keep focus on improving that part of the Fminbox docs?

**Comment by gregorykimmel** [comment]
Ok, sorry about that.

**Comment by pkofod** [comment]
> Ok, sorry about that.

Oh, it's totally fine to close your own issues, I just need it to remember to get back to this ;)
