### ISSUE TITLE
Extend maxlikenlm.jl to system of dependent variables

### ISSUE THREAD

**Issue by finmod** [JuliaNLSolvers/Optim.jl#696]
The MLE example is fine and elegant in showing how to obtain in a few efficient steps the standard OLS result. 

However, the point of using Julia, Optim and TwiceDifferentiable would be better illustrated by moving to an example of a system of equation with a possibility of blowing up the number of endogenous variables and the matrix of parameters to be estimated.

**Comment by pkofod** [comment]
> However, the point of using Julia, Optim and TwiceDifferentiable would be better illustrated by moving to an example of a system of equation with a possibility of blowing up the number of endogenous variables and the matrix of parameters to be estimated.

Do you mean something like a SEM (simultaneous equations model) example?

**Comment by finmod** [comment]
Yes,  y = x * β + ε with y a vector, everything else matrices. There is a subtle point here on how best to handle standard linear algebra in Julia to calculate the llk and optimize on datasets.

**Comment by pkofod** [comment]
> Yes, y = x * β + ε with y a vector, everything else matrices. There is a subtle point here on how best to handle standard linear algebra in Julia to calculate the llk and optimize on datasets.

It's not my first priority to add this, but I'd certainly give feedback and help out of someone had a swing at this!

**Comment by finmod** [comment]
@djlacombe would you be interested to extend your earlier notebook as mentioned above?

**Comment by finmod** [comment]
@johnmyleswhite @anriseth @fredrikekre Would anyone of you be interested to extend this example to 
y = x * β + ε with y a vector of variables, everything else matrices. 

There is a subtle point here on how best to handle standard linear algebra in Julia to calculate the llk and optimize on datasets of timeseries. Any direction where this is already done in Julia would be appreciated. Perhaps Distributions.jl @lindahua @simonbyrne

**Comment by anriseth** [comment]
I think you're tagging the wrong people here, @finmod, we're not actively involved in the package development (anymore).

Is there a reason why you are not extending this yourself? You seem to have some knowledge of the type of problem you are interested in.

**Comment by pkofod** [comment]
Sounds like a great blog post

**Comment by finmod** [comment]
@johnmyleswhite Correct. This was my aim. I also note that not much is going on using variance measures and the relation to quantity of information/entropy.

**Comment by djlacombe** [comment]
Hello All,

I think it might be a good idea maybe to solicit help for examples in the
forum. Individuals can make requests and others can choose to help with the
proviso that the completed code will be placed in an "Examples" section of
the appropriate documentation website.

I originally made the maximum likelihood example for my own purposes and
I'm happy that it helped others but I'm afraid that certain models are not
in my wheelhouse and I may not be able to code a decent example.

Just my $0.02.

Thanks.

**Comment by pkofod** [comment]
I'm not going to do this, and it doesn't seem central enough for Optim to be an outstanding issue. People who want to submit such a PR are welcome, or they can write a cool blog post about it.
