### ISSUE TITLE
Making manifolds their own package

### ISSUE THREAD

**Issue by jc211** [JuliaNLSolvers/Optim.jl#699]
I would like to add the SE3 and Sim3 manifolds to the ones currently available. I can imagine more being added later as well. Would it be better to separate the manifolds and put them in their own package? What is the current recommended way of extending manifolds? An advantage of splitting out manifolds is that it can be included in LsqFit.jl as well. Currently LsqFit.jl  is not dependent on Optim.jl but I would still like to perform levenberg marquardt.

**Comment by pkofod** [comment]
I’ll try to keep the discussion here then. This work has already begun. If you’re interested in this being finished, we’d love some help over at https://github.com/JuliaNLSolvers/ManifoldProjections.jl

**Comment by jc211** [comment]
Great!
