### ISSUE TITLE
Feature request: trace time()

### ISSUE THREAD

**Issue by briochemc** [JuliaNLSolvers/Optim.jl#700]
Just a suggestion: Add a field saving the `time()` of each iteration in the trace. 

Right now I use the callback function to print `time()` to benchmark long runs, but I thought it would be nice to be able to save it in the trace. Maybe via a flag like `trace_time=true` or something like that?

Maybe a feature with more reusability would be to add a "callback" field to the trace, which the callback function could write to (while the optimization runs)? But maybe this is a pain to implement... I have no idea! 😄

**Comment by antoine-levitt** [comment]
Can't you use profiling to get timings?

**Comment by briochemc** [comment]
> Can't you use profiling to get timings?

I'm not sure what you are suggesting... You mean Profile.jl? One of the things I'd like to do is to plot the norm of the gradient vs time when using a Newton type of solver.

**Comment by antoine-levitt** [comment]
OK, I misunderstood, sorry!

**Comment by pkofod** [comment]
The callback interface needs a complete rewrite. You can do some things, but it would be much better to have access to things like the solver state as well.

I have been wanting to look for some great examples of logging control and callbacks in the Julia, but I havn't gotten around to it.

What I really want to do is to rewrite things as proper iterators. Then you'd basically not even need a callback system, as people could just do

```
...
newton_iterator = ...
...
iter_result = iterate(newton_iterator)
while iter_result !== nothing
    (k, state) = iter_result
    # do whatever you want to do here... save stuff, log timing, evaluate on hold-out set if you're doing ML
    # and then continue
    iter_result = iterate(newton_iterator, state)
end
```
