### ISSUE TITLE
Fminbox() using parameters outside of the box specified

### ISSUE THREAD

**Issue by gregorykimmel** [JuliaNLSolvers/Optim.jl#712]
I am running Fminbox to find optimal parameters for a 2D lotka-volterra differential equation and constrained the parameters to all be between [0, p_{max}]. However it seems that the optimizer can still search below 0, which causes some problems (the ODE will grow past the carrying capacity, since it is now negative).

**Comment by pkofod** [comment]
Yes, this is possible because of the way Fminbox is written currently. I had a branch that fixed this, but I never got around to finishing it up. Could you try returning `NaN` in your objective if the parameters are not in the box? I know it seems odd that you have to check it yourself, but it may be a workaround for now.

**Comment by gregorykimmel** [comment]
Sorry for the late response. This works, I also had some wiggle room with background knowledge (the bound of 0 was soft, I was able to use 5 or 10), which seemed to be large enough away from 0 to avoid any issues.

**Comment by pkofod** [comment]
So basically, what I need to do at some point, is just to do the NaN-stuff for the user, but I havn't gotten around to it :) I know it's a disappointing answer, but I'll get around to it sometime after the summer.

**Comment by pkofod** [comment]
Hi @gregorykimmel , can you still reproduce the error if you go back to the original bounds and don't throw NaNs manually? I have a fix that I want to try to implement, and I would love if you could try your problem on it. I'll have a PR one of these days.

**Comment by BioTurboNick** [comment]
Hello from the future. I'm encountering this issue and would be happy to test it.
