### ISSUE TITLE
SAMIN does not show_trace

### ISSUE THREAD

**Issue by MaximilianJHuber** [JuliaNLSolvers/Optim.jl#721]
```
f(x) = x[1]^2

Optim.optimize(f,[-1.], [1.], [1.], SAMIN(),Optim.Options(iterations = 10^5, show_every = 10, show_trace = true))
```
does not show the trace, but 

```
Optim.optimize(f,[1.], SimulatedAnnealing(),Optim.Options(iterations = 10^5, show_every = 100, show_trace = true))
```
does.

I am on Julia 1.1.0 and Optim master.

**Comment by pkofod** [comment]
Unfortunately, I never got around to it, see https://github.com/JuliaNLSolvers/Optim.jl/issues/555 .

Is this something you'd like to have a stab at yourself? I'll give feedback and help you through the PR process.

**Comment by pkofod** [comment]
I'll push a fix in a few minutes when I've made sure it works

**Comment by pkofod** [comment]
Thanks. The problem should be fixed on master, and will be included in the next release of Optim.
