### ISSUE TITLE
Documentation suggests no support for global optimizaiton

### ISSUE THREAD

**Issue by robsmith11** [JuliaNLSolvers/Optim.jl#731]
> The provided solvers, under certain conditions, will converge to a local minimum. In the case where a global minimum is desired, global optimization techniques should be employed instead (see e.g. BlackBoxOptim).

https://julianlsolvers.github.io/Optim.jl/latest/

To me, it seems that the docs are suggesting that Optim.jl is not appropriate for global optimization and that one should use BlackBoxOptim.jl instead.  However, Optim.jl provides both simulated annealing and particle swarm optimization, which are both generally used for global optimization.

**Comment by pkofod** [comment]
> To me, it seems that the docs are suggesting that Optim.jl is not appropriate for global optimization and that one should use BlackBoxOptim.jl instead. However, Optim.jl provides both simulated annealing and particle swarm optimization, which are both generally used for global optimization.

I think it's meant as a defensive comment that predates SAMIN (and ParticleSwarm). Back then we only had SimulatedAnnealing, which isn't always super efficient. I think SAMIN is the best bet for global opt in Optim, and then comes ParticleSwarm. We could mention what we have, and say that people can look at BBO for a package dedicated to global opt.

**Comment by pkofod** [comment]
I've moderated it slightly.
