### ISSUE TITLE
Using IterativeSolvers in the Newton solvers

### ISSUE THREAD

**Issue by tlienart** [JuliaNLSolvers/Optim.jl#736]
In cases where the application `f(v) == H*v` of the Hessian `H` to a vector `v` is not too expensive to compute, using an iterative solver like CG or Minres could be a good alternative to constructing the full Hessian and solving `H \ ∇f`. 

It seems it wouldn't be too hard to allow the user to pass a LinearMap `Hm = LinearMap(f, ...)` and use `cg` or `minres` from IterativeSolvers. 

Has this been considered?

### short example

I was playing around with the regularised logistic regression where the Hessian is given by 

`(X' * Λ * X + λ * I)`  

where `X` is the design matrix (`n * p` and let's assume `n >> p`) and `Λ` is a diagonal matrix that's cheap to compute. In this case forming the Hessian is `O(np²)` and applying it to a vector is `O(np)`. The cost of solving a Newton step is dominated by the cost of forming the Hessian.
However, using CG/Minres costs one Hessian application per iteration (here `O(np)`) and there's at most `p` of those until convergence so at worse it's the same cost as a full Newton step but usually it converges very quickly so that for high dimensional problem this can be quite competitive; I believe that's what's implemented in the Scikitlearn `newton-cg` solver.

Any thoughts?

PS: I'm happy to try a PR for this but need a few guidelines as this may require also fiddling with NLSolversBase

**Comment by tlienart** [comment]
Hmmm, this may in fact just be the "KrylovTrustRegion" that I hadn't seen, I'll have a look at that and re-open if appropriate (probably not). Apologies for the spam.

**Comment by antoine-levitt** [comment]
It's not documented, so feel free to reopen at least as a doc issue!

**Comment by tlienart** [comment]
Yeah I figured it would be nice to have some doc and example for that, I'm keen to try it. Will open an issue to track
