### ISSUE TITLE
Document KrylovTrustRegion

### ISSUE THREAD

**Issue by tlienart** [JuliaNLSolvers/Optim.jl#737]
Add KrylovTrustRegion + example in the docs

**Comment by pkofod** [comment]
Yes, most definitely. I'm experimenting with Krylov solvers (nlsolve and optimize-style) in another package, so more stuff is to come, but we should document it as it works now.

**Comment by tlienart** [comment]
Would you guys be interested in an example with the Logistic Regression? (btw, that would be a simple example to use to fill the gaps in examples for Newton and LBFGS as well and showcase the `only_fg!` and `only_fgh!` tricks). I'm using this for a package already so I could suggest a PR with this.

**Comment by pkofod** [comment]
Sure, please post it!
