### ISSUE TITLE
Inconsistencies with fg! in Krylov vs LBFGS

### ISSUE THREAD

**Issue by tlienart** [JuliaNLSolvers/Optim.jl#738]
This may also be an issue with NLSolversBase; I'm happy to try to help but would need guidelines for how to proceed. 

Currently a trick suggested with solvers like LBFGS is to implement a function `fg!` and pass it to `Optim.only_fg!(fg!)`; as per https://julianlsolvers.github.io/Optim.jl/stable/#user/tipsandtricks/ this function must be of the form

```
fg!(f, g, x)
    # common computations
    g === nothing || ... # in place update of g with gradient at x
    f === nothing || ... # return eval function at x
end
```

However when using the `KrylovTrustRegion` optimizer, we have to construct a `TwiceDifferentiableHV` taking `f, fg!, Hv!` where this time `fg!` is of the form

```
fg!(g, x)
    # common computations
    ... # in place update of g with gradient at x
    ... # return eval function at x
end
```

this inconsistency is a bit annoying when trying to expose both Krylov and LBFGS to the user and we have to define an ugly function like

```
fg_for_krylov! = (g, x) -> fg!(0.0, g, x)
```

### suggestions

1. instead of passing `f, fg!, Hv!` to `TwiceDifferentiableHV`, just pass `fg!, Hv!` with the same convention as for `only_fg!`
2. allow `TwiceDifferentiableHV` to be constructed with a single function `fghv!` for the same reason as the `only_fg!` trick: usually the computation of `Hv` can re-use some stuff from the computation of the gradient (in fact it's a common trick in ML where you compute `Hv` by computing `d/dr g(x+rv)` at r=0 (see e.g. http://www.bcl.hamilton.ie/~barak/papers/nc-hessian.pdf) 

thoughts?

**Comment by pkofod** [comment]
Thanks! Yes, this should be cleaned up. As I mentioned in the other issue, NewtonKrylov is sort of untested and undocumented, but yes, let's try to clean it up!

**Comment by tlienart** [comment]
The PR offers this stuff. Note that I still find ambiguities in `NLSolverBase` with regards to `fg` functions a bit annoying (but this is broader than the current issue, maybe worth considering in a refactoring):

* sometimes it's called via `fg(g, x)` returns `f(x)` always
* sometimes it's called via `fg(f, g, x)` returns if things are not nothing

and there's a bit of a mix of the two in the code with weird functions like `fdf!_from_fdf` 😱. It wouldn't hurt to maybe just use one of the two everywhere (maybe the second one since it can avoid needless computations of `f(x)`).

**Comment by pkofod** [comment]
I'm not totally sure I understand what  you mean by the bullet points, but it does look like something that should be avoided. Can you point me to specific places? Thanks for you patience btw.

**Comment by tlienart** [comment]
No worries (and apologies for lack of clarity)

I'll list references in no particular order, probably should be bunched in separate issues, and some are probably to be fixed in NLSolverBase and others here:

* in the code below , the way `fg!` is defined applies the transformation on `storage` (always) and returns `f(x)` (always) while in https://github.com/JuliaNLSolvers/Optim.jl/blob/master/docs/src/user/tipsandtricks.md the "avoid repeating computations" section shows a `fg!` which works differently.

https://github.com/JuliaNLSolvers/Optim.jl/blob/40e939b1d5ab6c07dd0352c009c90983bf32d02b/test/multivariate/solvers/second_order/krylov_trust_region.jl#L3-L22

The `Optim.only_fg!` expects one that works like so:

```julia
function fg!(F,G,x)
  # ...
  G === nothing || # in place modif
  F === nothing || # return value after computation
end
```

Then you have functions like

https://github.com/JuliaNLSolvers/NLSolversBase.jl/blob/248631c337997d452bf99d3664bc4a1b6807175e/src/objective_types/inplace_factory.jl#L36-L46

which return things with the first convention

etc.

So there seems (to me) to be inconsistencies; it would probably be relevant to use a single convention and use it everywhere?
