### ISSUE TITLE
Print information on whether time limit reached

### ISSUE THREAD

**Issue by magerton** [JuliaNLSolvers/Optim.jl#739]
It would be helpful for the optimization to report whether the time limit was reached. Currently, when I hit the `time_limit` set in `Optim.options`, the output reports that `line search failed`. This is a little confusing. I'm proposing a partial fix and will reference this issue.

**Comment by pkofod** [comment]
This is not a little confusing, this is super confusing! Thanks for noticing this.

**Comment by pkofod** [comment]
I fixed the other ones

**Comment by pkofod** [comment]
Thanks :)

**Comment by magerton** [comment]
Fantastic! Thank you!
