### ISSUE TITLE
Parameters.jl 0.11 cannot be installed with Optim.jl

### ISSUE THREAD

**Issue by tkf** [JuliaNLSolvers/Optim.jl#743]
Parameters.jl v0.11.0 was released some time ago with getproperty/setproperty!
https://github.com/mauro3/Parameters.jl/releases but it is not usable with Optim.jl because it has compat bound:

https://github.com/JuliaNLSolvers/Optim.jl/blob/40e939b1d5ab6c07dd0352c009c90983bf32d02b/Project.toml#L29

Can you relax compat so that it is installable with Parameters.jl v0.11.0?

**Comment by pkofod** [comment]
Sure, let me have a look at the change log for Parameters. Thanks for letting me know.

**Comment by tkf** [comment]
Regarding the change in bc76368655a74a9ab7bfe6ca20c93eb1ad098b36:

https://github.com/JuliaNLSolvers/Optim.jl/blob/bc76368655a74a9ab7bfe6ca20c93eb1ad098b36/Project.toml#L29

I don't mind `≥ 0.11` but I suppose `≥ 0.10` would work too? The latter would reduce the probability of unsatisfiable dependency error when some other packages happen to use `Parameters = "0.10"`.

**Comment by pkofod** [comment]
> I don't mind `≥ 0.11` but I suppose `≥ 0.10` would work too? The latter would reduce the probability of unsatisfiable dependency error when some other packages happen to use `Parameters = "0.10"`.

that's true

**Comment by fredrikekre** [comment]
https://github.com/JuliaRegistries/General/pull/3425

**Comment by fredrikekre** [comment]
Oh, https://github.com/JuliaRegistries/General/pull/3447 seems to deal with both the OP and https://github.com/JuliaNLSolvers/Optim.jl/issues/743#issuecomment-530277813
