### ISSUE TITLE
first-order trust region

### ISSUE THREAD

**Issue by tpapp** [JuliaNLSolvers/Optim.jl#750]
Can one use the quasi-Newton approximation & updating for the Hessian for trust-region methods too? This would allow usage of this method without calculating the Hessian.

**Comment by pkofod** [comment]
Yes, and I have code for this in NLSolvers, I can help you try it out if you want.

**Comment by tpapp** [comment]
Thanks for the offer. Yes, that would be great, I find TR methods to be very robust for posteriors but Hessians are tedious to obtain for large problems.

**Comment by pkofod** [comment]
Things are still changing, code is not up to date with my local branches (yes, unfortunately I'm keeping track of several 😑 ), and neither is the readme, but something like this should work, but will change "soon", so...

```
using NLSolvers
function himmelblau!(∇f, x)
    if !(∇f == nothing)
        ∇f[1] = 4.0 * x[1]^3 + 4.0 * x[1] * x[2] -
            44.0 * x[1] + 2.0 * x[1] + 2.0 * x[2]^2 - 14.0
        ∇f[2] = 2.0 * x[1]^2 + 2.0 * x[2] - 22.0 +
            4.0 * x[1] * x[2] + 4.0 * x[2]^3 - 28.0 * x[2]
    end

    fx = (x[1]^2 + x[2] - 11)^2 + (x[1] + x[2]^2 - 7)^2
    return ∇f == nothing ? fx : (fx, ∇f)
end

function himmelblau!(∇²f, ∇f, x)
    if !(∇²f == nothing)
        ∇²f[1, 1] = 12.0 * x[1]^2 + 4.0 * x[2] - 42.0
        ∇²f[1, 2] = 4.0 * x[1] + 4.0 * x[2]
        ∇²f[2, 1] = 4.0 * x[1] + 4.0 * x[2]
        ∇²f[2, 2] = 12.0 * x[2]^2 + 4.0 * x[1] - 26.0
    end


    if ∇f == nothing && ∇²f == nothing
        fx = himmelblau!(∇f, x)
        return fx
    elseif ∇²f == nothing
        return himmelblau!(∇f, x)
    else
        fx, ∇f = himmelblau!(∇f, x)
        return fx, ∇f, ∇²f
    end
end
res = minimize!(TwiceDiffed(himmelblau!), copy([2.0,2.0]), (Newton(), NWI()))
res = minimize!(OnceDiffed(himmelblau!), copy([2.0,2.0]), (BFGS(), NWI()))
```

You can read the lines as first an annotation about the methods of himmelblau! to call, than initial point followed by a) the hessian approximation (Newton means the actual hessian) and NWI is the globalization strategy. In this case it's NWI which is a slightly improved TR method to the one in Optim (but an even better one is in the works, and you can also solve bigger problems using https://github.com/oxfordcontrol/TRS.jl (I can show you have to use their solver if you want). You could have chosen `Backtracking()` instead if you wanted to use a linesearch strategy.

**Comment by pkofod** [comment]
The output is
```
julia> res = minimize!(TwiceDiffed(himmelblau!), copy([2.0,2.0]), (Newton(), NWI()))                                    ([2.9999999999999996, 2.000000000000002], 7.888609052210118e-29, [1.7763568394002505e-14, 6.394884621840902e-14], 7)                                                                                                                            julia> res = minimize!(OnceDiffed(himmelblau!), copy([2.0,2.0]), (BFGS(), NWI()))                                       ([2.9999999974226688, 1.9999999857290345], 4.443625375236093e-15, [-4.761418281873375e-7, -5.367594440031098e-7], 58)                 
```
which is: optimizer, optimum, gradient at optimum and number of major iterations

**Comment by antoine-levitt** [comment]
That looks extremely nice, please hurry up to release it!! :p 

Does it do limited memory also? BFGS is just not an option for large scale problems

**Comment by pkofod** [comment]
L-BFGS is on a local branch yes... There are quite a few things in different local branches that I need to merge, so I need to find time for that. One thing is conjugate gradient descent methods, and another is the whole manifolds stuff which is currently just copied over from Manifolds.jl (I just copy the necessary code for Euclidean to work, and then expect people to extend with their own manifolds - or when I can rely on ManifoldsBase I will just load retract/project/Euclidean from that package)

**Comment by pkofod** [comment]
Works in the new backend to be released soon.
