### ISSUE TITLE
Nelder-Mead stopping condition

### ISSUE THREAD

**Issue by jwscook** [JuliaNLSolvers/Optim.jl#759]
Hi Devs,

Currently (release v0.19.3 (2019-09-11)),  the stopping condition for Nelder Mead is checking that the standard deviation of function evaluations at the vertices of the simplex is below "g_abstol". 

Here is the snippet:

> Optim.jl/src/multivariate/solvers/zeroth_order/nelder_mead.jl

```
function assess_convergence(state::NelderMeadState, d, options::Options)
    g_converged = state.nm_x <= options.g_abstol # Hijact g_converged for NM stopping criterior
    return false, false, g_converged, g_converged, false
end
```

Shouldn't it also depend on:
1. "x_tol" such that it terminates if the vertices of the simplex are too close
2. "f_tol" so that it terminates if the *best* value is below the threshold

Maybe something like this:

```
function assess_convergence(state::NelderMeadState, d, options::Options)
    g_converged = state.nm_x <= options.g_abstol # Hijact g_converged for NM stopping criterior
    f_converged = state.f_lowest <= options.f_tol
    x_converged = all(all(isapprox.(state.simplex[1], i,
      rtol=options.x_tol)) for i ∈ state.simplex[2:end]) # something like this
    return x_converged, f_converged, g_converged, g_converged, false
end
```

I'm happy to open a PR if this behaviour is correct.

Cheers,
James

Edit: I wrote "g_tol" instead of "g_abstol".

**Comment by pkofod** [comment]
Hi @jwscook . I won't fix this in this version of Optim, but there'll soon be a new version out that allows you to control the threshold level. Wrt x, I'm not sure what you're thinking about, but the standard deviation is exactly a measure of how close they are.
