### ISSUE TITLE
Parallel batched interface

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaNLSolvers/Optim.jl#765]
It would be nice if there was an interface for parallelized versions which batched calls to `f` so the user could perform parallelism. @pkofod wrote a version of a method for this:

https://gist.github.com/pkofod/c6f0dc28588e1d65b521ba785405aff2

**Comment by pkofod** [comment]
Btw, have you tried to see if it works? :) I can try to pull it into Optim, maybe with alternative parallel interfaces.

**Comment by pkofod** [comment]
This is in NLSolvers that is hopefully ready for beta soon. Eventually Optim will call into that.
