### ISSUE TITLE
Maximizing a complicated nonlinear logliklihood function

### ISSUE THREAD

**Issue by sama2689** [JuliaNLSolvers/Optim.jl#787]
I have a log likelihood function with 3 parameters that I have defined, it is nonlinear with respect to its 3 fitting parameters.

Is there a function in Optim that can take in the function, and some initial guesses for the parameters, and then fit the output? 
Specifically I want to solve equation 8 in this paper: https://www.sciencedirect.com/science/article/pii/S0360301611005244?via%3Dihub

I looked in the documentation for this but had some trouble navigating and was unable to find it, the page I did find on log liklihood pointed me to the optimize function. I believe that this function would work but I am a bit confused about the syntax on how to deploy it.
My loglikliood function is a function of several variables,` LLH_LKB(dvh_h, dvh_s, dpf, nf, ab, n, m, TD50)`
Where only the final three variables (n,m,TD50) are parameters to be fitted.

I was thinking that I could call this as 
`optimum = optimize(LLH_LKB,params0,method=:cg)`
but of course this would not work because I don't see how to specify that the parameters to fit are n,m, and TD50.

Thanks

**Comment by pkofod** [comment]
```
objective(x) = LLH_LKB(dvh_h, dvh_s, dpf, nf, ab, x[1], x[2], x[3])
optimize(objective, x0, ConjugateGradient())
```
should work if you have the first parameters already defined, and x0 is a vector of n,m,TD50 starting values. Where did you see the `method=:cg` syntax? That's very old. What version of Julia and Optim are you running, and where did you find the documentation?

Anyway, if you have more questions on usage, then I suggest http://discourse.julialang.org.

**Comment by sama2689** [comment]
> ```
> objective(x) = LLH_LKB(dvh_h, dvh_s, dpf, nf, ab, x[1], x[2], x[3])
> optimize(objective, x0, ConjugateGradient())
> ```
> 
> should work if you have the first parameters already defined, and x0 is a vector of n,m,TD50 starting values. Where did you see the `method=:cg` syntax? That's very old. What version of Julia and Optim are you running, and where did you find the documentation?
> 
> Anyway, if you have more questions on usage, then I suggest http://discourse.julialang.org.

Thank you! That is exactly what I was looking for, I'll give that a try. Just a couple questions first though
1. What does the ConjugateGradient option do? Does this just ask the optimize function to find the gradient itself?
2. Does optimize find either a maximum or a minimum? It looks like from the way you have described the code that Optimize does not need to be told to find a maximum vs. a minimum and it will simply find the nearest extreme using gradient descent, is this accurate?


I am using Julia 1.3.1, I am not sure how to check the version of Optim I am using but it should be the latest version. The syntax was found here: https://juliaeconomics.com/2014/06/16/numerical-maximum-likelihood-the-ols-example/

 Thanks again,

**Comment by pkofod** [comment]
Oh, okay. That's very out of date, but then again, it's six years old :) ConjugateGradient is just a method (Conjugate Gradient Descent by Hager and Zhang), you can replace it with things like `BFGS()`, `LBFGS()` or `Newton()` for example.
