### ISSUE TITLE
Unused return value from update_state!() in optimize()

### ISSUE THREAD

**Issue by gwater** [JuliaNLSolvers/Optim.jl#789]
The variable `ls_failed` is assigned but never used. At the same time `ls_success` is never changed during optimization and is always set to `true` no matter what happens.
https://github.com/JuliaNLSolvers/Optim.jl/blob/74794f21b131825c0cd16882276b103dcf94e723/src/multivariate/optimize/optimize.jl#L57

**Comment by pkofod** [comment]
Thanks, I merged the PR

**Comment by gwater** [comment]
Thanks!
