### ISSUE TITLE
It seems like dot is being incorrectly overwritten

### ISSUE THREAD

**Issue by juliohm** [JuliaNLSolvers/Optim.jl#801]
```
WARNING: Method definition dot(Any, Any, Any) in module LinearAlgebra at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/LinearAlgebra/src/generic.jl:924 overwritten in module Optim at /home/juliohm/.julia/packages/Optim/Agd3B/src/multivariate/precon.jl:23.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition dot(Any, Any, Any) in module LinearAlgebra at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/LinearAlgebra/src/generic.jl:924 overwritten in module Optim at /home/juliohm/.julia/packages/Optim/Agd3B/src/multivariate/precon.jl:23.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition dot(Any, Any, Any) in module LinearAlgebra at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/LinearAlgebra/src/generic.jl:924 overwritten in module Optim at /home/juliohm/.julia/packages/Optim/Agd3B/src/multivariate/precon.jl:23.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition dot(Any, Any, Any) in module LinearAlgebra at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/LinearAlgebra/src/generic.jl:924 overwritten in module Optim at /home/juliohm/.julia/packages/Optim/Agd3B/src/multivariate/precon.jl:23.
  ** incremental compilation may be fatally broken for this module **

WARNING: Method definition dot(Any, Any, Any) in module LinearAlgebra at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/LinearAlgebra/src/generic.jl:924 overwritten in module Optim at /home/juliohm/.julia/packages/Optim/Agd3B/src/multivariate/precon.jl:23.
  ** incremental compilation may be fatally broken for this module **
```

This is happening on a fresh install of Julia v1.4.

**Comment by mauro3** [comment]
Just installing Optim does not trigger this for me, but installing `GeoArrays` (v0.2.0) does:
```
(Test) pkg> add GeoArrays
   Updating registry at `~/.julia/registries/General`
   Updating git-repo `https://github.com/JuliaRegistries/General.git`
...
julia> using GeoArrays
[ Info: Precompiling GeoArrays [2fb1d81b-e6a0-5fc5-82e6-8e06903437ab]
WARNING: Method definition dot(Any, Any, Any) in module LinearAlgebra at /home/mauro/julia/julia-1.4/usr/share/julia/stdlib/v1.4/LinearAlgebra/src/generic.jl:924 overwritten in module Optim at /home/mauro/.julia/packages/Optim/Agd3B/src/multivariate/precon.jl:23.
  ** incremental compilation may be fatally broken for this module **
```
Note that
- GeoArray does not define any `dot` methods
- this only happens during pre-compilation, subsequent uses of GeoArrays in fresh sessions do not trigger it.
- when using Revise.jl, above warning appears twice

If I do the same thing in Julia 1.3 (also with GeoArrays v0.2.0), it all works fine.

**Comment by juliohm** [comment]
This is probably related to my GeoStatsBase.jl package then, since it is a dependency of GeoArrays.jl. However, the package doesn't define any dot method either, so it is strange that the warning is only raised under these circumstances.

Does Optim.jl load optional code with Requires.jl? Why is it that the warning is only raised in the presence of other packages?

**Comment by mauro3** [comment]
Yes, the above reproducer can also be triggered by GeoStatsBase.jl.

**Comment by visr** [comment]
For what Optim version is this? It looks like it must be pretty old, since #748 was added for this reason (and explains the 1.3/1.4 difference). More recently, Compat is used for dot in #791.

This also came up in this issue at GeoArrays: https://github.com/evetion/GeoArrays.jl/issues/26#issuecomment-600840021. In that issue a very old GDAL version was used, a similar thing may be happening here that you get such an old version.

**Comment by pkofod** [comment]
Yeah, it must be some upper bounding that is causing an old version of Optim to be installed.

**Comment by mauro3** [comment]
Maybe we should take this issue to GeoStatsBase.jl?

I did some digging: Installing both GeoStatsBase and Optim results either in 
GeoStatsBase@v0.7.1 & Optim@v0.18.1 OR  GeoStatsBase@v0.4.3 & Optim@v0.20.5

If it is indeed Compat causing the problem underneath, then the two possible culprits are
- DataFrames, installed 0.18.4 vs newest 0.20
- BinDeps installed 0.8.10 vs newest 1.0

One of those two probably bounds Compat, but this is as far as I got.

**Comment by juliohm** [comment]
It is very strange that GeoStatsBase is holding back Optim. I've never used upper bounds explicitly in my packages, and only adhered to the semantic versioning with minor releases. When I look at the Project.toml file of GeoStatsBase v0.7.1 it is indeed holding Optim to 0.18. Should I just bump it to 0.20? I think CompatHelper failed here to update the version for me.

**Comment by pkofod** [comment]
Well, if you have 0.18 in your Project.toml I don't understand why you think it's weird it's holding back Optim? So yes, you should bump it, because v0.20 is the version that fixed this. :+1:

**Comment by mauro3** [comment]
Ah, yes, I see in your 0.7.1 release you're holding Optim back; I only looked at Project.toml on master.  My bad.

In general, you should release soon after CompatHelper bumps as otherwise you can hold back other packages, as happened here.

**Comment by juliohm** [comment]
Got it. I will try to release to release it soon. Thanks for digging into the Project.toml files.
