### ISSUE TITLE
New minor release for StatsBase v0.33 compatibility?

### ISSUE THREAD

**Issue by oschulz** [JuliaNLSolvers/Optim.jl#803]
Would you consider tagging a new minor release for StatsBase v0.33 compatibility? Last test on master ran with 0.33, so should be fine. It's just that a lot of packages depend on Optim (which is awesome!) ... :-)

**Comment by pkofod** [comment]
Yes

**Comment by pkofod** [comment]
Wait... I should be compatible already?

**Comment by oschulz** [comment]
Sorry, my bad - I don't know how,  but I must have looked at an older version!

**Comment by pkofod** [comment]
:shrug: As long as it works :)
