### ISSUE TITLE
Natural Evolution Strategies [gradient free]

### ISSUE THREAD

**Issue by francescoalemanno** [JuliaNLSolvers/Optim.jl#804]
is there any interest in having a method such as the one in:

https://arxiv.org/abs/1703.03864

this method is very simple and provides good results on many tough problems,
in case there is some interest i will work on a PR :)

Thank you

**Comment by pkofod** [comment]
Probably yes. BlackBoxOptim already has CMAES if it's omething you need right now :)

**Comment by francescoalemanno** [comment]
Thank you! i was aware of BBOptim, as soon as i get the chance i will try to implement it :)

**Comment by pkofod** [comment]
Maybe just do it as a completely separate function first, and I'll help you integrate it?

**Comment by francescoalemanno** [comment]
Thank you! i'm experimenting here https://github.com/francescoalemanno/NaturalES.jl, i will let you know very soon

**Comment by francescoalemanno** [comment]
hi @pkofod i'm now almost satisfied with the performance of those functions, how would you like to proceed?
