### ISSUE TITLE
numerical values for alphaguess

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaNLSolvers/Optim.jl#805]
I think it would be very convenient for the `alphaguess` keyword, defined for many algorithms, to accept numerical values. Then, `alphaguess` would be transformed to an `InitialStatic` object :

```julia 
if isnumeric(alphaguess):
   alphaguess = LineSearches.InitialStatic(alpha=alphaguess)
end
```
This is in order to make smoother the most common tweak one would perform to tune the optimization, i.e. changing the step size. Now, one has to write
```julia
optimize(fg!, x0, Optim.LBFGS(alphaguess=LineSearches.InitialStatic(alpha=η)))
```
while I'd like to have
```julia
optimize(fg!, x0, Optim.LBFGS(alphaguess=η))
```
As a side note, I found LineSearches documentation a bit lacking and had to go look into the source to understand how to construct an InitialStatic object.

**Comment by pkofod** [comment]
I agree. Is it something you'd feel comfortable making a PR for?

**Comment by pkofod** [comment]
Opened #812 to fix this.
