### ISSUE TITLE
Error - assertion failed: dphia < 0

### ISSUE THREAD

**Issue by Wedg** [JuliaNLSolvers/Optim.jl#81]
Hi all

Really enjoying getting started on Julia. Huge thank you for all that you're doing.

Am trying to get Optim running and am getting the following error message for a particular problem:
assertion failed: dphia < 0
in secant2! at hz_linesearch.jl:423
in push! at array.jl:458

Any idea what would cause this?

Here is the setup:

function linRegCost(θ, X, y, m, λ)
        cost = (1/(2_m) \* (X_θ - y)' \* (X_θ - y)
                    + λ/(2_m) \* sum(θ[2:end].^2)
                   )[1]
end
f(θ) = linRegCost(θ, X, y, m, λ)

function linRegGradient!(θ, grad, X, y, m, λ)
        grad = (1/m  \*  X' \* (X*θ - y)
                    + λ/m \* [0, θ[2:end]]
                   )
end
g!(θ, grad) = linRegGradient!(θ, grad, X, y, m, λ)

initial_θ = zeros(size(X, 2))

res = optimize(f, g!, initial_θ)

**Comment by benkuhn** [comment]
I just ran into this error as well (my Hessian calculation was incorrect and I was using Newton's method). Can I suggest that from a usability perspective, it might be helpful to give a more informative error message here? Something like "check your derivatives"?

**Comment by mlubin** [comment]
@benkuhn, that's a good idea. Feel free to open a PR.

**Comment by benkuhn** [comment]
Sure thing!

**Comment by johnmyleswhite** [comment]
It would be good to make sure we understand the line that triggers that error. I believe `dphia` is the inner product of the search prediction and the derivative. If so, we should probably say exactly that before suggesting that people check their derivatives.

**Comment by benkuhn** [comment]
Oops, @johnmyleswhite, I didn't see your comment before making a PR. I don't have a great understanding of the Hager-Zhang algorithm yet (nor the innards of Optim.jl, nor idiomatic Julia), I may not be the best person to come up with appropriate error handling here, but I'm happy to try as long as you don't mind correcting me a bunch.
