### ISSUE TITLE
Use AbstractConstrainedOptimizer as the parent type for all the constrained optimizers?

### ISSUE THREAD

**Issue by abhigupta768** [JuliaNLSolvers/Optim.jl#818]
Hey, I wanted to know if there has been discussion on using AbstractConstrainedOptimizer uniformly within Optim as the parent type for the constrained optimizers. Currently only `Fminbox` follows this where as `SAMIN<:ZerothOrderOptimizer` and `IPNewton` defines a new abstract `ConstrainedOptimizer` type.

If you agree I can put together the PR for this. Thanks.

**Comment by pkofod** [comment]
Hi! The very short ansewr is: no there hasn't been any real discussion around this. Can you flesh out your plan a bit? Thanks
