### ISSUE TITLE
Optim: No method matching iterate

### ISSUE THREAD

**Issue by castrovjm** [JuliaNLSolvers/Optim.jl#824]
Hi! I am having a weird problem using Optim. It starts well and runs for some seconds. However, it suddenly stops and gives me the following error:

`MethodError: no method matching iterate(::Optim.MultivariateOptimizationResults{NelderMead{Optim.AffineSimplexer,Optim.AdaptiveParameters},Float64,Array{Float64,1},Float64,Float64,Array{OptimizationState{Float64,NelderMead{Optim.AffineSimplexer,Optim.AdaptiveParameters}},1},Bool})
Closest candidates are:
  iterate(!Matched::Core.SimpleVector) at essentials.jl:600
  iterate(!Matched::Core.SimpleVector, !Matched::Any) at essentials.jl:600
  iterate(!Matched::ExponentialBackOff) at error.jl:218
  ...
indexed_iterate(::Optim.MultivariateOptimizationResults{NelderMead{Optim.AffineSimplexer,Optim.AdaptiveParameters},Float64,Array{Float64,1},Float64,Float64,Array{OptimizationState{Float64,NelderMead{Optim.AffineSimplexer,Optim.AdaptiveParameters}},1},Bool}, ::Int64) at tuple.jl:66
msm(::Array{Int8,2}, ::Array{Float64,2}, ::Array{Float64,3}, ::UniformScaling{Bool}, ::Array{Float64,1}) at simulations.jl:173
estim_MSM(::Int64, ::Int64, ::Array{Float64,2}, ::Array{Float64,1}) at simulations.jl:187
top-level scope at simulations.jl:196
`

In all my time working with Optim, I hadn't ever received this message.

**Comment by pkofod** [comment]
Can you tell me more about the code you're running?

**Comment by pkofod** [comment]
Please reopen if you have more info to supply or ask on discourse.julialang.org for help.
