### ISSUE TITLE
Comment doesn't really seem to reflect logic in code

### ISSUE THREAD

**Issue by samuela** [JuliaNLSolvers/Optim.jl#830]
The comment here states:
https://github.com/JuliaNLSolvers/Optim.jl/blob/0794f443954d1a843fc786c1cea561f474a650e7/src/multivariate/solvers/first_order/l_bfgs.jl#L42
But the logic does something quite different:
https://github.com/JuliaNLSolvers/Optim.jl/blob/0794f443954d1a843fc786c1cea561f474a650e7/src/multivariate/solvers/first_order/l_bfgs.jl#L44

What is the actual logic here? Is it correct?

**Comment by pkofod** [comment]
Yeah, I agree it's not too clear. If you end up in the else branch it does what it says. If you have `scaleinvH0` enabled it won't apply the preconditioner, which I think makes sense. The scaling attempts to achieve the same thing as preconditioning, so it wouldn't make sense to do both imo.

**Comment by pkofod** [comment]
changed the wording. Thanks
