### ISSUE TITLE
Particle Swarm algorithm fails in very simple objective function

### ISSUE THREAD

**Issue by astrojhgu** [JuliaNLSolvers/Optim.jl#835]
```Julia
pso=ParticleSwarm([-1., -1.], [1., 1.], 10)
result=optimize(x->sum(x.^2), [3.,4.], pso)
result.minimizer```
The result is 
```
* Status: failure (reached maximum number of iterations)

 * Candidate solution
    Final objective value:     1.349053e-172

 * Found with
    Algorithm:     Particle Swarm

 * Convergence measures
    |x - x'|               = NaN ≰ 0.0e+00
    |x - x'|/|x'|          = NaN ≰ 0.0e+00
    |f(x) - f(x')|         = NaN ≰ 0.0e+00
    |f(x) - f(x')|/|f(x')| = NaN ≰ 0.0e+00
    |g(x)|                 = NaN ≰ 1.0e-08

 * Work counters
    Seconds run:   0  (vs limit Inf)
    Iterations:    1000
    f(x) calls:    11001
    ∇f(x) calls:   0
```

It does give out a correct answer, i.e., [0.0, 0.0] (by inspecting `result.minizer`), however its convergance diagonse is incorrect.

Is it just the normal behavior of PSO or it is a bug?

The `Julia` version is 1.4.2, and the `Optim` version is [429524aa] Optim v0.22.0

Thanks.

**Comment by NightMachinary** [comment]
Per its documentation (you can read it using `@doc ParticleSwarm`, ParticleSwarm never converges:
```
  Note, that convergence is never assessed for ParticleSwarm. It will run until it reaches the maximum number of iterations
  set in Optim.Options(iterations=x)`.
```

**Comment by astrojhgu** [comment]
> Per its documentation (you can read it using `@doc ParticleSwarm`, ParticleSwarm never converges:
> 
> ```
>   Note, that convergence is never assessed for ParticleSwarm. It will run until it reaches the maximum number of iterations
>   set in Optim.Options(iterations=x)`.
> ```

Thanks, that answers my question.

**Comment by aquaresima** [comment]
This is missing from the doc in 

https://julianlsolvers.github.io/Optim.jl/stable/#algo/particle_swarm/
