### ISSUE TITLE
NealderMead recalculates same points:

### ISSUE THREAD

**Issue by neoabs** [JuliaNLSolvers/Optim.jl#852]
![image](https://user-images.githubusercontent.com/53402602/91669432-40124080-eb15-11ea-8b4f-ce4f4dfa43d6.png)

My code is:
`results = optimize(prices -> objective_function(prices, mdl, method_cube), lower, upper, mdl.Prices , Fminbox(NelderMead() ) )
`
`mdl` is a `mutable struct` `method_cube` is a string. Using standard simplex. 

It is not a killer, but there is a room for improvement.

**Comment by pkofod** [comment]
oh this is for Fminbox, it's not NelderMead as such. Can you try this branch? https://github.com/JuliaNLSolvers/Optim.jl/pull/850
