### ISSUE TITLE
Functor Support with Univariate analysis

### ISSUE THREAD

**Issue by stevengogogo** [JuliaNLSolvers/Optim.jl#853]
Dear Optim contributors,

The functor type is not supported with univariate analysis.

```julia
# optimization of functor y
using Optim

"Model parameter"
struct y
  p
end

"Univariable Functor"
function (s::y)(x)
  return x*s.p
end

"Multivariable Functor with array input"
function (s::y)(x_v)
  return x_v[1]*s.p
end


model = y(1.0)

Optim.optimize(model, -1, 2, [1.]) #PASS
Optim.optimize(model, -1, 2, 1.) #ERROR

```

It reports error when using univariate input

```sh
julia> Optim.optimize(model, -1, 2, [1.]); #PASS

julia> Optim.optimize(model, -1, 2, 1.); #ERROR
ERROR: MethodError: no method matching optimize(::y, ::Int64, ::Int64, ::Float64)
Closest candidates are:
  optimize(::Any, ::Any, ::Number, ::Number, ::AbstractArray{T,N} where N, ::Optim.Options; kwargs...) where T at /Users/stevenchiu/.julia/packages/Optim/TNmSw/src/multivariate/solvers/constrained/fminbox.jl:164
  optimize(::Any, ::Number, ::Number, ::AbstractArray{T,N} where N; kwargs...) where T at /Users/stevenchiu/.julia/packages/Optim/TNmSw/src/multivariate/solvers/constrained/fminbox.jl:156
  optimize(::Any, ::Number, ::Number, ::AbstractArray{T,N} where N, ::Optim.AbstractConstrainedOptimizer) where T at /Users/stevenchiu/.julia/packages/Optim/TNmSw/src/multivariate/solvers/constrained/fminbox.jl:160
  ...
Stacktrace:
 [1] top-level scope at none:1

julia> 
```

## Proposed changes

Univariate analysis only supports `function` type, while `functor` (object-like function) should be included

https://github.com/JuliaNLSolvers/Optim.jl/blob/431a5f97f814f9df17b24fe429fcc7b9af3c9577/src/univariate/optimize/interface.jl#L2

https://github.com/JuliaNLSolvers/Optim.jl/blob/431a5f97f814f9df17b24fe429fcc7b9af3c9577/src/univariate/optimize/interface.jl#L32

https://github.com/JuliaNLSolvers/Optim.jl/blob/431a5f97f814f9df17b24fe429fcc7b9af3c9577/src/univariate/optimize/interface.jl#L44
 
It is better to remove `::F` to make those API to support `functor` inputs, which is already supported in multivariate analysis.

## Reason to use functor type

I'm currently working on biological model and found `funtor` is an elegant way to integrating algorithm with common parameters.

## Further Information

This issue is first addressed at Julia Community

https://discourse.julialang.org/t/functor-usage-for-optim-jl/45778/5

---
*Thank you for reviewing this issue.*

Steven Chiu

**Comment by pkofod** [comment]
Very thorough :) Thanks. I'm fixing it now.

**Comment by pkofod** [comment]
#854 will fix it but you have to be aware that that last signature is also wrong because the univariate interface only expects 2 numbers not 3.
