### ISSUE TITLE
Warning (again) on LinearAlgebra.dot

### ISSUE THREAD

**Issue by juliohm** [JuliaNLSolvers/Optim.jl#855]
I remember seeing this warning in the past, probably some recent change reverted the fix?

```
WARNING: Method definition dot(Any, Any, Any) in module LinearAlgebra at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/LinearAlgebra/src/generic.jl:924 overwritten in module Optim at /home/juliohm/.julia/packages/Optim/Agd3B/src/multivariate/precon.jl:23.
incremental compilation may be fatally broken for this module 
```

**Comment by pkofod** [comment]
`]st`?

**Comment by juliohm** [comment]
Oh I think some package is holding Optim.jl to version 0.18.1 in my Manifest.toml. I will close the issue, the warning should go away at some point. Sorry for the noise.

**Comment by pkofod** [comment]
I just release a new version maybe that will be able to satisfy your bounds.
