### ISSUE TITLE
BFGS `reset!` typo

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaNLSolvers/Optim.jl#859]
https://github.com/JuliaNLSolvers/Optim.jl/blob/master/src/multivariate/solvers/first_order/bfgs.jl#L72

`d` is not defined in that function. https://travis-ci.com/github/SciML/DiffEqFlux.jl/jobs/381629205#L318 . Looking at the history, `d` has never been defined for that function, so it seems like that branch may have just never been called before. Is `d` hidden in one of those objects?

**Comment by pkofod** [comment]
yeah that's a typo, it should be `obj` #860
