### ISSUE TITLE
Optim 1.0, 1.1 and Julia 1.0

### ISSUE THREAD

**Issue by mschauer** [JuliaNLSolvers/Optim.jl#863]
Did the new version accidentally break Julia 1.0? https://travis-ci.org/github/mschauer/PointProcessInference.jl/builds/724933595 seems to suggest so. Maybe you need to adjust the version bounds.

**Comment by devmotion** [comment]
The same issue shows up in DynamicHMC on Julia 1.0 and 1.1: https://travis-ci.org/github/tpapp/DynamicHMC.jl/builds/725169408

**Comment by devmotion** [comment]
I guess the problem is that NLSolversBase >= 7.6 (and hence also InPlaceObjective... introduced in https://github.com/JuliaNLSolvers/NLSolversBase.jl/compare/v7.6.3...v7.7.0) is only compatible with Julia >= 1.2.

**Comment by mschauer** [comment]
@pkofod tag

**Comment by dehann** [comment]
I just came across the same thing:
https://travis-ci.org/github/JuliaRobotics/ApproxManifoldProducts.jl/jobs/725562423

+1 for increasing minimum bounds above (Julia 1.0) for Optim.jl v1.x if it is an change introduced recently.  By issue subject it looks like minimum Julia 1.2, although i have not investigated the root cause myself yet.

**Comment by pkofod** [comment]
> @pkofod tag

Lol, thanks for the input. I appreciate the initial bug-report and I will fix this, but when communicating and asking someone else to do something or to help them it's good etiquette to use fully formed sentences. You could even come with a suggestion. No need to "drill sergeant" me. I understand this is annoying, it wasn't on purpose.

**Comment by pkofod** [comment]
https://github.com/JuliaRegistries/General/pull/21226

**Comment by pkofod** [comment]
Okay that might just have made it worse ... now you can't get v1+ of Optim on Julia v1.2+... We'll get there if we just stay strong.

**Comment by pkofod** [comment]
https://github.com/JuliaRegistries/General/pull/21275 https://github.com/JuliaRegistries/General/pull/21273 hopefully does it

**Comment by mschauer** [comment]
I think tagging people to discussions they might want to be aware of is way less confrontational then calling me out as a drill sergeant. It what meant as a friendly act. But good.

**Comment by mschauer** [comment]
Ah, perhaps I actually understand this: I pinged you because a commit of you in NLSolversBase was mentioned and I assumed you were not aware of the discussion. Now I see that you are maintainer Optim, so for you it must have looked like a not so friendly bump.

**Comment by pkofod** [comment]
Okay, my bad then ! @mschauer not hard feelings. I actually think I totally misunderstood you then. You meant "tag" as in "I'm mentioning you here", I thought

@pkofod tag

meant "@pkofod get your act together and *tag*  a new version" but the tag meant something else entirely. Sorry for misunderstanding !

I hope everything works now.

**Comment by mschauer** [comment]
I get it know... „tag!“ 😂 okay, all is well

**Comment by pkofod** [comment]
Exactly... I just thought it was a little aggressive. Lol, that's internet communication for ya huh? :) Hope everything works now.
