### ISSUE TITLE
Fminbox reset! bug: d not defined

### ISSUE THREAD

**Issue by e-zolotarevskaya** [JuliaNLSolvers/Optim.jl#864]
Here is a minimal working example of the bug: reset! function uses d that is neither passed as an argument nor defined there
[bug_example.txt](https://github.com/JuliaNLSolvers/Optim.jl/files/5184151/bug_example.txt)

**Comment by pkofod** [comment]
Should be fixed on v1.1.0 that was release the same day (thought probably after you ran into this issue) you posted this. Thanks for the bug report.
