### ISSUE TITLE
Error in using Optim with Julia v1.0:  ERROR: LoadError: LoadError: UndefVarError: InPlaceObjectiveFGHv not defined

### ISSUE THREAD

**Issue by ericagol** [JuliaNLSolvers/Optim.jl#866]
The latest version of Optim (1.0/1.1) seems to have broken the precompilation in Julia v1.0.0.  See lines 3189-3223 of this build:

https://travis-ci.org/github/ericagol/TRAPPIST1_Spitzer/builds/725391351#L3304

The error seems to be triggered by the command "using Optim" in several scripts the above repository.

**Comment by fredrikekre** [comment]
#863

**Comment by pkofod** [comment]
Yeah that's a duplicate issue. Thanks though.

**Comment by ericagol** [comment]
Thanks!  I have tried to use:

````
Pkg.add(PackageSpec(name="Optim",version="0.22.0"))
Pkg.pin(PackageSpec(name="Optim",version="0.22.0"))
````
but unfortunately travis continues to upgrade Optim to 1.1.

**Comment by ericagol** [comment]
@pkofod  I tried changing my Julia version to 1.2, and that solved the problem.   Thanks for checking in; greatly appreciated!
