### ISSUE TITLE
Optim.ldiv! is only defined on arrays

### ISSUE THREAD

**Issue by longemen3000** [JuliaNLSolvers/Optim.jl#870]
to be able to the optimization problem described [here ](https://discourse.julialang.org/t/nonlinear-optimization-help-optim-jump-something-else/47163)(using ComponentArrays) its necesary to add a method on `Optim.ldiv!`. maybe a more generic version accepting abstract vectors can work well enough in this situation?

**Comment by pkofod** [comment]
Yeah, that part of the code could probably use some improvements. Might work in NLSolvers.jl already.

**Comment by pkofod** [comment]
I loosened it to Abstract..
