### ISSUE TITLE
`optimize` passes NaN as x value to function

### ISSUE THREAD

**Issue by cordarei** [JuliaNLSolvers/Optim.jl#874]
*Edit:* I forgot to mention the version; I have version 1.2.0 installed in the environment I am running in.

I encountered a similar situation to that described in #581 : the function I am trying to optimize receives NaN as input from `optimize`. The cause appears to be non-deterministic, receiving the NaN only happens occasionally, but I encountered it several times because I am evaluating performance and thus running with the same inputs repeatedly. Pasting the code below into a blank Pluto notebook and running the cell repeatedly will eventually produce the following output:

````
* Status: success

 * Candidate solution
    Final objective value:     9.999990e+05

 * Found with
    Algorithm:     Fminbox with L-BFGS

 * Convergence measures
    |x - x'|               = NaN ≰ 0.0e+00
    |x - x'|/|x'|          = NaN ≰ 0.0e+00
    |f(x) - f(x')|         = 0.00e+00 ≤ 0.0e+00
    |f(x) - f(x')|/|f(x')| = 0.00e+00 ≤ 0.0e+00
    |g(x)|                 = NaN ≰ 1.0e-08

 * Work counters
    Seconds run:   0  (vs limit Inf)
    Iterations:    3
    f(x) calls:    39
    ∇f(x) calls:   39
````

The final objective value of 999999 indicates that a NaN value was received. The summary reports success, as does the succeeded() method, which seems wrong (I don't think it succeeded)? Would there be a problem with checking whether a NaN was produced in succeeded() etc?

MWE:

````julia
begin
	using Optim
	using QuadGK

	function fdead(a :: Real, b :: Real, μ :: Real, rec :: Integer)
		y, err = quadgk(x -> (μ * exp(-μ * x)) / (exp(-a + b * x) + 1), 0, rec)
		y * exp(μ * rec)
	end

	function loglike3(μ :: Real, a, b, rec, T)
		if isnan(μ)
			return 999999
		end
		dead = fdead(a, b, μ, rec)
		live = 1. / (1 + exp(-a + b * rec))
		ll = -μ * T + log(live + dead)
		-ll
	end

	optimize(x -> loglike3(x[1], 0.625505, 0.03187, 246, 95), [1e-8], [1.], [0.5])
end
````

**Comment by genisprat** [comment]
I have the same problem. Did you find any solution? 
Thanks

**Comment by pkofod** [comment]
Not good :) I see this is using box constrained optimization, are you using that as well @genisprat ?

**Comment by genisprat** [comment]
Yes, I am also using box constrained optimization. This is the function that I am using:

optimize(MaxEmission,lower,upper, z, Fminbox(LBFGS(linesearch = BackTracking())),Optim.Options(g_tol=1e-5); autodiff = :forward)

where lower and upper are the lower and upperd bounds, and z is the initial guess.

Thank you very much for your help
Cheers

**Comment by pkofod** [comment]
Found it. It was a Fminbox+LBFGS bug. Thanks for the report and example!
