### ISSUE TITLE
L1 regularization with box constraint in Optim ?

### ISSUE THREAD

**Issue by yewalenikhil65** [JuliaNLSolvers/Optim.jl#877]
Does optim have L1 regularization with box constraint in following form as utility ?

minimize || Ax - b ||
subject to 1st norm of x i.e. |x| < lambda (some parameter)
and 0 <=  x[i]  <= kappa (some parameter)

(If not, and you know any other that supports such kind of optimization, please let me know)

**Comment by pkofod** [comment]
No we don't have explicit L1 regularization support. I would ask on https://discourse.julialang.org/ or https://julialang.org/slack/ for alternatives, there might be something out there!
