### ISSUE TITLE
Optim.trace() fails with MethodError: no method matching length(::Nothing)

### ISSUE THREAD

**Issue by leventov** [JuliaNLSolvers/Optim.jl#895]
https://github.com/JuliaNLSolvers/Optim.jl/blob/0b53f0549d71991ac5b2ab54f75494be03a478e6/src/api.jl#L6

Should probably check `isnothing(r.trace)`

**Comment by pkofod** [comment]
I get
```
julia> Optim.trace(optimize(f, g!, [1., 0., 1., 0.], m))
ERROR: No trace in optimization results. To get a trace, run optimize() with store_trace = true.
```
Please provide an example where this occurs if it still does. Closing for now.
