### ISSUE TITLE
Importing Optim.jl causes really unexpected behaviour in unrelated code

### ISSUE THREAD

**Issue by ikirill** [JuliaNLSolvers/Optim.jl#900]
Consider this example:
```
julia> using LinearAlgebra
julia> x, y, A = randn(10), randn(10), qr(randn(10,10)+4I)
julia> ldiv!(x, A, y)
10-element Array{Float64,1}:
  0.003605693325069791
 -0.0936492498367861
 -0.034962952777132156
  0.03137575761617558
  0.06197756758207713
  0.14958980068241784
 -0.15023507720117182
  0.1662120782787171
  0.28016962488868424
  0.033634153764053536

julia> ldiv!(x, nothing, y)
ERROR: MethodError: no method matching ldiv!(::Array{Float64,1}, ::Nothing, ::Array{Float64,1})
```
This is expected.

However, in the same session:
```
julia> using Optim
[ Info: Precompiling Optim [429524aa-4258-5aef-a3af-852621145aeb]
julia> ldiv!(x, nothing, y)
10-element Array{Float64,1}:
  0.014826631206656728
 -0.8043485193410475
  0.2997560117230972
 -0.16666190999190045
  0.3807907638997067
  0.7520861293780641
 -0.4049024922798503
  0.6241402781004148
  1.1363925704295952
 -0.535914300547736
```

Suddenly the `ldiv!` call no longer produces an error (see https://github.com/JuliaNLSolvers/Optim.jl/blob/e193c6b5e0c6a47561145fe59574c4fdae77b902/src/multivariate/precon.jl#L31)

I understand that the intended behaviour is to be able to pass a `nothing` preconditioner to `ldiv!` and have it just work, but this also means that (potentially buggy) code that used to produce an error somewhere else will produce an incorrect result instead whenever `nothing` is not in fact a preconditioner. I don't think most people that use Optim.jl will have any expectation that this change in ldiv behaviour is even possible (I certainly didn't).

Why not just replace an empty preconditioner with the identity matrix `LinearAlgebra.I` instead?

**Comment by ikirill** [comment]
I looked at git blame, and does precon.jl predate inclusion of ldiv! in standard library or something?

**Comment by pkofod** [comment]
> I looked at git blame, and does precon.jl predate inclusion of ldiv! in standard library or something?

It does. this should be fixed, it's bad :grimacing:

**Comment by pkofod** [comment]
> Why not just replace an empty preconditioner with the identity matrix `LinearAlgebra.I` instead?

This is a good idea. I don't think that worked back when it was implemented. For now I'll just create our own `ldiv!` and `dot` that falls back to `LinearAlgebra.x`

Thanks, I've created a PR
