### ISSUE TITLE
Optim.minimizer returns the initial starting point

### ISSUE THREAD

**Issue by dongzn** [JuliaNLSolvers/Optim.jl#901]
Hi,

I run into an issue that the optimize function seems to get the optimal objective function value correct, but no luck with the corresponding minimizer. 

func = OnceDifferentiable( params ->  myNLL( param,x, tx, n, f  ), x0; autodiff=:forward );

julia> myopt = optimize( func, lower, upper, x0,  Fminbox() )
 * Status: success

 * Candidate solution
    Final objective value:     3.322558e+04

 * Found with
    Algorithm:     Fminbox with L-BFGS

 * Convergence measures
    |x - x'|               = 0.00e+00 ≤ 0.0e+00
    |x - x'|/|x'|          = 0.00e+00 ≤ 0.0e+00
    |f(x) - f(x')|         = 0.00e+00 ≤ 0.0e+00
    |f(x) - f(x')|/|f(x')| = 0.00e+00 ≤ 0.0e+00
    |g(x)|                 = 0.00e+00 ≤ 1.0e-08

 * Work counters
    Seconds run:   0  (vs limit Inf)
    Iterations:    1
    f(x) calls:    1
    ?f(x) calls:   1

julia> Optim.minimizer(myopt)
4-element Array{Float64,1}:
 0.2358648525966056
 0.13094051049113298
 0.46880573929459857
 0.22989816588580325

julia> x0
4-element Array{Float64,1}:
 0.2358648525966056
 0.13094051049113298
 0.46880573929459857
 0.22989816588580325

Optim v1.2.3
Julia 1.5.3

From the objective function value, I can tell it the correct minimum, however, the minimizer neither printed in the optimize output nor returned correctly from the Optim.minimizer call. Any way to get the correct minimizer optimal solution ?

**Comment by johnmyleswhite** [comment]
Did you evaluate your function at the returned minimizer?

**Comment by dongzn** [comment]
Thanks for your reply. when I evaluate my user defined function at the returned minimizer, the returned value is very different from the value printed at the optimize() call output : Final objective value. 

by the way, my instance is on the Windows OS. Let me try a couple of things today : 1) try it on linux; 2) try different package in Julia, e.g. ipopt, etc. 

I will keep folks posted. If I can narrow further down the issue, will report this back. Thanks!

**Comment by AndiMD** [comment]
Possibly related: [https://github.com/JuliaNLSolvers/LsqFit.jl/issues/178](https://github.com/JuliaNLSolvers/LsqFit.jl/issues/178)
MWE, fit an exponential function (adapted for Optim):
```
using Optim
model1(x,p) = @. p[1]*exp(p[2]*x/4E-10)
xdata = range(0.1,5,length=20) # fake data x
ydata = 0.01.*rand(20).*model1(xdata,[1E-9,4E-10]) # fake data y
res1 = optimize( p->sum((model1(xdata,p).-ydata).^2), [1E-9,4E-10], BFGS(), Optim.Options(g_tol = 1e-30)) # fail
```

**Comment by dongzn** [comment]
It looks that the issue I raised is gone after I correct my user defined function as the objective function of the underlying nonlinear optimization problem. now the output looks normal : 

given initial starting point x0 : 
julia> x0
4-element Array{Float64,1}:
 0.20322401577797033
 0.9858740490205138
 0.17654798724855625
 0.2298174297513742

and setup 

julia> func = OnceDifferentiable( param ->  myNLL( param,x, tx, n, f  ), x0; aut
odiff=:forward );

now the output looks like : 

julia> myopt = optimize( func, lower, upper, x0,  Fminbox() )
 * Status: success

 * Candidate solution
    Final objective value:     3.322558e+04

 * Found with
    Algorithm:     Fminbox with L-BFGS

 * Convergence measures
    |x - x'|               = 1.18e-07 ? 0.0e+00
    |x - x'|/|x'|          = 3.69e-08 ? 0.0e+00
    |f(x) - f(x')|         = 0.00e+00 ≤ 0.0e+00
    |f(x) - f(x')|/|f(x')| = 0.00e+00 ≤ 0.0e+00
    |g(x)|                 = 5.53e-09 ≤ 1.0e-08

 * Work counters
    Seconds run:   2  (vs limit Inf)
    Iterations:    4
    f(x) calls:    114
    ?f(x) calls:   114

The number of function calls look reasonable, instead of 1. The minimizer is looking correct ( same as answers published in research articles now )

julia> Optim.minimizer(myopt)
4-element Array{Float64,1}:
 1.2035223516029592
 0.7497163581751444
 0.6567182084622661
 2.7834422326940085

and the objective function value at the minimizer now looks correct : 

julia> myNLL( Optim.minimizer(myopt), x, tx, n, f)
33225.581274346965

and if I check the gradient at the optimizer, results look correct : gradient at optimizer close to zero.
 
using ForwardDiff
julia> @show ForwardDiff.gradient( param -> myNLL( param,x, tx, n, f  ), Optim.m
inimizer(myopt) )
ForwardDiff.gradient((param->begin
            #= REPL[34]:1 =#
            myNLL(param, x, tx, n, f)
        end), Optim.minimizer(myopt)) = [2.768047124845907e-9, 4.77530193165876e
-9, 5.5324562708847225e-9, 8.462848199997097e-10]
4-element Array{Float64,1}:
 2.768047124845907e-9
 4.77530193165876e-9
 5.5324562708847225e-9
 8.462848199997097e-10

So, the issue I reported is gone, after correcting the objective function definitions. Thanks everyone!
