### ISSUE TITLE
How to set lower and upper bound for Newton's algorithm?

### ISSUE THREAD

**Issue by zxjroger** [JuliaNLSolvers/Optim.jl#905]
Thank you for this amazing package. I tried to put lower and upper bound using the Newton's algorithm, but I got an error. I wonder if my code is wrong or it is not supported? This is my code:

```
using Optim

function f(x)
    return (1.0 - x[1])^2 + 100.0 * (x[2] - x[1]^2)^2
end

initial_x = zeros(2)
l = [0.0, 0.0]
u = [2.0, 2.0]

res = Optim.optimize(f, l, u, initial_x, Newton(); autodiff = :forward)
```
I got the following error:

> MethodError: objects of type Array{Float64,1} are not callable Use square brackets [] for indexing an Array.

**Comment by pkofod** [comment]
The error is obviously not helpful, that's unfortunate. You can try to look up the IPNewton() algorithm. This is a Newton solver that allows for constraints, including bounds. https://julianlsolvers.github.io/Optim.jl/stable/#algo/ipnewton/ Feel free to reopen if you encounter any problems.
