### ISSUE TITLE
Documentation outer configurable options

### ISSUE THREAD

**Issue by ArnoStrouwen** [JuliaNLSolvers/Optim.jl#914]
Should configurable options for outer solve such as "outer_iterations" be documented here?
https://julianlsolvers.github.io/Optim.jl/stable/#user/config/

**Comment by pkofod** [comment]
Yes, certainly :)

**Comment by JeffFessler** [comment]
The distinction between `iterations` and `outer_iterations` is unclear from the config docs, though some hint is given here:
https://julianlsolvers.github.io/Optim.jl/stable/#user/minimization/

**Comment by JeffFessler** [comment]
I just noticed that this issue is nicely addressed by #937 that has been sitting there for 1.5 years.
