### ISSUE TITLE
How to use Optim.jl's Optim.OnceDifferentiable in the context of LBFGSB.jl ?

### ISSUE THREAD

**Issue by rht** [JuliaNLSolvers/Optim.jl#926]
Since LBFGSB is not yet implemented in Optim.jl, I have been looking for alternative way to use the algorithm other than using `scipy.optimize(method='L-BFGS-B')`. I found this library https://github.com/Gnimuc/LBFGSB.jl which wraps the same Fortran routine used in Scipy.

Since it needs a `g!`, I figured if I could use `Optim.jl`'s function to generate `g!` using finite difference.
What I have so far:
```julia
using LBFGSB
import Optim

function f(x)
    y = 0.25 * (x[1] - 1)^2
    for i = 2:length(x)
        y += (x[i] - x[i-1]^2)^2
    end
    4y
end

function g!(z, x) = ... # See the definition in the README.md of https://github.com/Gnimuc/LBFGSB.jl

optimizer = L_BFGS_B(1024, 17)
n = 25  # the dimension of the problem
x = fill(Cdouble(3e0), n)  # the initial guess
# set up bounds
bounds = zeros(3, n)
for i = 1:n
    bounds[1,i] = 2  # represents the type of bounds imposed on the variables:
                     #  0->unbounded, 1->only lower bound, 2-> both lower and upper bounds, 3->only upper bound
    bounds[2,i] = isodd(i) ? 1e0 : -1e2  #  the lower bound on x, of length n.
    bounds[3,i] = 1e2  #  the upper bound on x, of length n.
end

## Now for Optim.jl to generate g!
promote_objtype(x, f) = Optim.OnceDifferentiable(f, x, real(zero(eltype(x))))
d = promote_objtype(x, f)

function optim_g!(z, x)
    Optim.value_gradient!(d, x)
    z = Optim.gradient(d)
end

fout, xout = optimizer(f, optim_g!, x, bounds, m=5, factr=1e7, pgtol=1e-5, iprint=-1, maxfun=15000, maxiter=15000)
```

However, the value of `fout` and `xout` are incorrect. Am I missing some steps?

**Comment by rht** [comment]
I just got the correct result with this gradient!
```julia
function optim_g!(z, x)
    n = length(x)
    Optim.value_gradient!(d, x)
    g = Optim.gradient(d)
    for i in 1:n
        z[i] = g[i]
    end
end
```

However, I'm still not 100% if I am using the `Optim.value_gradient!` correctly. If there is no more mistake, feel free to close the issue.

**Comment by rht** [comment]
On another note, do you think it is a good idea to wrap that LBFGSB.jl so that it can be used as one of Optim.jl optimization options?

**Comment by pkofod** [comment]
If you just need the gradient then
```julia
function optim_g!(z, x)
    z .= Optim.gradient!(d, x)
end
```
should work

**Comment by rht** [comment]
Indeed, I tried `z .= Optim.gradient!(d, x)` and the number of allocations decreased from `(419 allocations: 60.61 KiB)` to `(401 allocations: 59.48 KiB)`. Thank you very much!

**Comment by pkofod** [comment]
> On another note, do you think it is a good idea to wrap that LBFGSB.jl so that it can be used as one of Optim.jl optimization options?

Maybe we can start with something like OptimLBFGSB.jl that defines the appropriate wrappers?

**Comment by rht** [comment]
Sounds good.

**Comment by Gnimuc** [comment]
Hi @pkofod,

Do you think it would be useful to transfer LBFGSB.jl to your orgs? I'm happy to do the transfer because I haven't maintained that package for a while.

cc @rht

**Comment by rht** [comment]
@pkofod turns out that using `promote_objtype(x, f) = Optim.OnceDifferentiable(f, x, real(zero(eltype(x))))` is not sufficient, because the Python equivalent in `scipy.optimize`, `approx_derivative` (https://github.com/scipy/scipy/blob/43b76937c0aadf23b4e0fcc04f546fa5d61b543b/scipy/optimize/_numdiff.py#L257), allows one to supply bounds, which adjusts the value of the steps to be within the bounds (as in https://github.com/scipy/scipy/blob/43b76937c0aadf23b4e0fcc04f546fa5d61b543b/scipy/optimize/_numdiff.py#L11).

I suppose I somehow need to specify `OnceDifferentiableConstraints` along with `OnceDifferentiable`?

**Comment by pkofod** [comment]
Ah you mean there might be issues if you use central differences at any bound or forward finite differences if you're at the upper bounds for example? Interesting... I'm not quite sure.

**Comment by rht** [comment]
@pkofod I think you missed another message by @Gnimuc before my message.
