### ISSUE TITLE
Nelder-Mead stopping if no change in stopping criterion?

### ISSUE THREAD

**Issue by cseveren** [JuliaNLSolvers/Optim.jl#940]
First -- Thanks for the great package.

I'm running a somewhat intensive minimization problem using Nelder-Mead. The algorithm seems to be at a point where both the objective function is not decreasing and the stopping criterion (standard error of vertices) is not changing. Is there a stopping rule that is something like "if the stopping criterion does not change after X iterations, stop"? If not, I think that might be a useful rule to include (not sure what the downsides are though).

To illustrate, below is a screenshot of the trace (being shown every 10 iterations) with time markers to help manage my machines resources:

![image](https://user-images.githubusercontent.com/30906872/129230853-b2d3ded7-fe86-4746-8ef1-0e9f658033f9.png)

**Comment by cseveren** [comment]
Can confirm infinite repetition at other values, usually with sd of simplex vertices at X.Xe-08. Sometimes it will gut stuff for a while somewhere else with no change in sd of simplex vertices, but when that value is small, it stays there forever. Have set `g_tol=1e-6` to get around this.

**Comment by pkofod** [comment]
That could be a posibility yes, but in your piece wise constant world are you sure you want to do that? It could very well happen that one shrink is not enough to move to a different flat region, but two or three shrinks would.

**Comment by cseveren** [comment]
It takes many shrinks, but that makes since given the adaptive parameters with optimization over a high number of variables, also here: https://github.com/JuliaNLSolvers/Optim.jl/issues/974#issuecomment-1030248403
