### ISSUE TITLE
NelderMead() gets stuck at specific `g_tol`/(sd of simplex), which should not be possible?

### ISSUE THREAD

**Issue by cseveren** [JuliaNLSolvers/Optim.jl#974]
Hello -- I have come to the same issue now with two optimization problems using the Nelder-Mead routine; they almost-converge to a (sd of simplex) of 1.490116e-8, but then continue doing costly searches at the point forever. My work around is to set `g_tol=1e-6`. 

To be more explicit, by my read, (sd of simplex) should never be the same value two iterations in a row under Nelder Mead; it should always change a little bit. Is this correct? If so, something may be amiss in the algo coding. Moreover, when it gets stuck, each iteration is much slower, indicating that it is likely going through most/all the substeps of the NM algorithm and then not updating.

If helpful, my objective function is a stepwise function with lots of very tiny steps. The way I expect Nelder-Mead to work if it gets stuck on a step is to successively decrease the size of the simplex, until at some point (sd of simplex) `< g_tol`. What I can't figure out is why (sd of simplex) doesn't vary. 

I first raised the issue [here](https://github.com/JuliaNLSolvers/Optim.jl/issues/940), but have since found that it replicates in a different setting (similar data but simplified likelihood expression with 52 instead 104 variables). That it gets stuck at precisely the same value seems with problems of a different dimension as particularly odd.

**Comment by pkofod** [comment]
I don't think you can always expect it to change value if you have a piece-wise constant function. Let's say it goes through all the steps and it finds no improvement. Then it shrinks. Well, if your current simplex vertices are all located within the same "steps" of your staircase after the shrink, then the function values do not change, and your sd won't change.

I'm happy to see if there's a bug somewhere, but it's a bit hard without the code. Can you maybe print the simplex and centroid? ? There should be an option to set `Optim.Options(; trace_simplex=true)`. The centroid can be stored and printed with the usual `Options(;extended_trace=true)`.

Thanks

**Comment by cseveren** [comment]
This is my error: I've read sd(simplex) instead of sd(f(simplex)). And be cause I have many parameters and am using the default adaptive parameters, the shrink step is decreasing only very slowly. Thanks for the clarification!
