### ISSUE TITLE
Add option to return the final inverse hessian estimate from BFGS

### ISSUE THREAD

**Issue by jeffpollock9** [JuliaNLSolvers/Optim.jl#984]
Hello,

I was wondering if it would be possible to add an option to BFGS to easily and efficiently return the final inverse hessian estimate? This is really useful for a fast and approximate estimate. It is used in various other packages, for example TensorFlow Probability:

https://github.com/tensorflow/probability/blob/v0.16.0/tensorflow_probability/python/optimizer/bfgs.py#L199-L200

Where they use it for e.g. Laplace approximations.

I see it is possible to do this currently via something like:

``` julia
using Optim
using LinearAlgebra
using ForwardDiff

function rosenbrock(x)
    return (1.0 - x[1])^2 + 100.0 * (x[2] - x[1]^2)^2
end

opt = optimize(
    rosenbrock,
    [0.0, 0.0],
    BFGS(),
    Optim.Options(store_trace = true, extended_trace = true),
    autodiff = :forward,
)

!Optim.converged(opt) && (@warn opt)

minimizer = Optim.minimizer(opt)

inverse_hessian_estimate = Symmetric(opt.trace[end].metadata["~inv(H)"])
# julia> inverse_hessian_estimate
# 2×2 Symmetric{Float64, Matrix{Float64}}:
#  0.500135  1.00028
#  1.00028   2.00559

inverse_hessian_forward_diff = inv(Symmetric(ForwardDiff.hessian(rosenbrock, minimizer)))
# julia> inverse_hessian_forward_diff
# 2×2 Symmetric{Float64, Matrix{Float64}}:
#  0.5  1.0
#  1.0  2.005
```

But it feels awkward to have to record the full history of inverse hessian estimates when I would expect users to only ever be interested in the final one.

Thanks!

**Comment by mohamed82008** [comment]
This is a duplicate of https://github.com/JuliaNLSolvers/Optim.jl/issues/943.

**Comment by jeffpollock9** [comment]
@mohamed82008 thanks for the reply, I guess there is some desire for this feature then. I will close this and try to continue the discussion on the first issue.
