### ISSUE TITLE
only_fgh! not working - where am I going wrong?

### ISSUE THREAD

**Issue by JockLawrie** [JuliaNLSolvers/Optim.jl#987]
Hi there,

I am maintaining `MultinomialRegression.jl`, which currently uses LBFGS.
I'm trying to allow the Newton solver to be used.
I've had success with `only_fg!` and LBFGS - see line 57 [here](https://github.com/JockLawrie/MultinomialRegression.jl/blob/irls/src/solvers/optim.jl).

Using the same code structure/style, I am struggling with `only_fgh!` - see line 61 at the link above.
The error I get (below) says that the storage space for the hessian is `Nothing`.
The hessian calculation at the bottom of the linked file is working, as I use it to obtain standard errors after obtaining a solution with LBFGS.

Any ideas?

Here's the error I get when running the tests on the `irls` branch:

```julia
Iris: Error During Test at C:\Users\jock\code\MultinomialRegression.jl\test\iris.jl:1
  Got exception outside of a @test
  MethodError: no method matching setindex!(::Nothing, ::Matrix{Float64}, ::UnitRange{Int64}, ::UnitRange{Int64})
  Stacktrace:
    [1] hessian!(H::Nothing, X::Matrix{Float64}, wts::Nothing, reg::Nothing, probs::Matrix{Float64})
      @ MultinomialRegression.lbfgs C:\Users\jock\code\MultinomialRegression.jl\src\solvers\optim.jl:173
    [2] (::MultinomialRegression.lbfgs.var"#5#6"{Vector{UInt8}, Matrix{Float64}, Nothing, Nothing, Matrix{Float64}, Matrix{Float64}})(#unused#::Float64, g::Vector{Float64}, H::Nothing, b::Vector{Float64})
      @ MultinomialRegression.lbfgs C:\Users\jock\code\MultinomialRegression.jl\src\solvers\optim.jl:97
    [3] (::NLSolversBase.var"#97#103"{NLSolversBase.InplaceObjective{Nothing, Nothing, MultinomialRegression.lbfgs.var"#5#6"{Vector{UInt8}, Matrix{Float64}, Nothing, Nothing, Matrix{Float64}, Matrix{Float64}}, Nothing, Nothing}, Float64})(G::Vector{Float64}, x::Vector{Float64})
      @ NLSolversBase C:\Users\jock\.julia\packages\NLSolversBase\cfJrN\src\objective_types\incomplete.jl:114
    [4] value_gradient!!(obj::NLSolversBase.TwiceDifferentiable{Float64, Vector{Float64}, Matrix{Float64}, Vector{Float64}}, x::Vector{Float64})
      @ NLSolversBase C:\Users\jock\.julia\packages\NLSolversBase\cfJrN\src\interface.jl:82
    [5] initial_state(method::Optim.Newton{LineSearches.InitialStatic{Float64}, LineSearches.HagerZhang{Float64, Base.RefValue{Bool}}}, options::Optim.Options{Float64, Nothing}, d::NLSolversBase.TwiceDifferentiable{Float64, Vector{Float64}, Matrix{Float64}, Vector{Float64}}, initial_x::Vector{Float64})
      @ Optim C:\Users\jock\.julia\packages\Optim\wFOeG\src\multivariate\solvers\second_order\newton.jl:45
    [6] optimize
      @ C:\Users\jock\.julia\packages\Optim\wFOeG\src\multivariate\optimize\optimize.jl:36 [inlined]
    [7] #optimize#89
      @ C:\Users\jock\.julia\packages\Optim\wFOeG\src\multivariate\optimize\interface.jl:142 [inlined]
    [8] optimize(f::NLSolversBase.InplaceObjective{Nothing, Nothing, MultinomialRegression.lbfgs.var"#5#6"{Vector{UInt8}, Matrix{Float64}, Nothing, Nothing, Matrix{Float64}, Matrix{Float64}}, Nothing, Nothing}, initial_x::Vector{Float64}, method::Optim.Newton{LineSearches.InitialStatic{Float64}, LineSearches.HagerZhang{Float64, Base.RefValue{Bool}}}, options::Optim.Options{Fl      @ Optim C:\Users\jock\.julia\packages\Optim\wFOeG\src\multivariate\optimize\interface.jl:141
    [9] optimise(y::Vector{UInt8}, X::Matrix{Float64}, wts::Nothing, reg::Nothing, solver::Nothing, opts::Nothing, probs::Matrix{Float64})
      @ MultinomialRegression.lbfgs C:\Users\jock\code\MultinomialRegression.jl\src\solvers\optim.jl:61
   [10] fit_optim(y::Vector{UInt8}, X::Matrix{Float64}, wts::Nothing, reg::Nothing, solver::Nothing, opts::Nothing)
      @ MultinomialRegression.lbfgs C:\Users\jock\code\MultinomialRegression.jl\src\solvers\optim.jl:16
   [11] fit(y::Vector{UInt8}, X::Matrix{Float64}, yname::String, ylevels::Vector{String}, xnames::Vector{String}, wts::Nothing, reg::Nothing, solver::Nothing, opts::Nothing)
      @ MultinomialRegression.fitpredict C:\Users\jock\code\MultinomialRegression.jl\src\fitpredict.jl:31
```

**Comment by pkofod** [comment]
Looks like you're updating the hessian without checking if it's about to be updated first (you need to put it behind a `if !isnothing` branch for the hessian positional argument).You link doesn't lead anywhere, so I cannot check the implementation :)

**Comment by JockLawrie** [comment]
Sorry, try [this link](https://github.com/JockLawrie/MultinomialRegression.jl/blob/irls/src/optim.jl)
See the commented out lines starting from line 90 for the call to Optim.

Thanks for responding, but I don't follow your response. My understanding is that using the `only_fgh!` function will see Optim initialise a hessian which users then populate. Is this right? Or does it start as `nothing`, and users need to create it? If so, does this mean a hessian needs to be created on every iteration? 

I think I'm wrong because the use of the LBFGS solver (line 72 of the link) assumes a gradient has been initialised and I haven't had any trouble with it.

Thanks again.

**Comment by JockLawrie** [comment]
The issue seems to be in the code snippet below.
For some reason the arguments `_`, `g` and `b` are all ok (`Float64`, `Vector{Float64}` and `Vector{Float64}` respectively), but `H` is `nothing`, even on the first call. Why is this? How do I work around this?

```julia
fgh! = (_, g, H, b) -> begin
        println(typeof(H))  # Nothing
        B = reshape(b, p, k - 1)
        G = reshape(g, p, k - 1)
        update_probs!(probs, B, X)
        gradient!(G, B, X, wts, reg, probs, Y)  # grad(-LL + penalty)
        H2 = hessian!(H, X, wts, reg, probs)    # hessian(-LL + penalty). H2 is Hermitian
        copyto!(H, H2)
        -loglikelihood(y, probs, wts) + penalty(reg, b)
end

fitted = optimize(Optim.only_fgh!(fgh!), fill(0.0, p * (k - 1)), Newton())
```

For completeness, this works without a hessian:

```julia
fg! = (_, g, b) -> begin
        B = reshape(b, p, k - 1)
        G = reshape(g, p, k - 1)
        update_probs!(probs, B, X)
        gradient!(G, B, X, wts, reg, probs, Y)
        -loglikelihood(y, probs, wts) + penalty(reg, b)
end

fitted = optimize(Optim.only_fg!(fg!), fill(0.0, p * (k - 1)), LBFGS())
```

**Comment by JockLawrie** [comment]
A self-contained MWE.

```julia
using Optim

function f(x)
    return (1.0 - x[1])^2 + 100.0 * (x[2] - x[1]^2)^2
end

function g!(G, x)
    G[1] = -2.0 * (1.0 - x[1]) - 400.0 * (x[2] - x[1]^2) * x[1]
    G[2] = 200.0 * (x[2] - x[1]^2)
end

function h!(H, x)
    H[1, 1] = 2.0 - 400.0 * x[2] + 1200.0 * x[1]^2
    H[1, 2] = -400.0 * x[1]
    H[2, 1] = -400.0 * x[1]
    H[2, 2] = 200.0
end

initial_x = zeros(2)

fg! = (_, G, x) -> begin
    g!(G, x)
    f(x)
end

fgh! = (_, G, H, x) -> begin
    g!(G, x)
    h!(H, x)
    f(x)
end

fitted1 = optimize(f, g!, h!, initial_x, Newton())  # Ok
fitted2 = optimize(Optim.only_fg!(fg!), initial_x, LBFGS())  # Ok
fitted3 = optimize(Optim.only_fgh!(fgh!), initial_x, Newton())  # Error
```

**Comment by moble** [comment]
The documentation is a little hard to find — I only see anything like this [here](https://github.com/JuliaNLSolvers/NLSolversBase.jl#example), found by just googling "only_fgh!".  The point @pkofod was trying to make above was that `fgh!` (and `fg!`, if you're making one) is not always called with `G` and `H` being arrays; sometimes they can be `nothing`.  In principle, the `F`, `G`, `H` arguments may be any of all 6 possible combinations of arrays and `nothing`, as seen in [this code](https://github.com/JuliaNLSolvers/NLSolversBase.jl/blob/cef31b5060158ce678c70fd6abf5a84fa40fc51b/src/objective_types/incomplete.jl#L97-L102).  So your functions have to be able to deal with any of those combinations.

In your MWE above, you *could* add these definitions to get things working:
```julia
function g!(::Nothing, x) end
function h!(::Nothing, x) end
```
Of course, the idea of a single `fgh!` function is to reuse parts of the computation, so that's maybe not the most useful example.  Expanding on [the example from the NLSolversBase README](https://github.com/JuliaNLSolvers/NLSolversBase.jl#example), you want something like this:
```julia
function fgh!(F, G, H, x)
    common_calc(...)
    if !(H == nothing)
        # mutating calculations specific to h!
    end
    if !(G == nothing)
        # mutating calculations specific to g!
    end
    if !(F == nothing)
        # calculations specific to f
        return f
    end
end
TwiceDifferentiable(only_fgh!(fgh!), x0)
```

**Comment by JockLawrie** [comment]
Ok thanks.
Why would `G` or `H` be `nothing`?
Isn't the purpose of the `fgh!` interface to utilise `G` and `H` as workspaces for the gradient and hessian respectively?

**Comment by moble** [comment]
Yeah, the workspaces are always there, but sometimes a given algorithm doesn't need to actually *calculate* their values at every single step.  There may be parts of the algorithm where only the function value is needed, or maybe the function and gradient.  For example, many (most?) optimizers that use a gradient and Hessian have some sort of sub-optimization that happens within each iteration — such as a line search that doesn't need Hessian information.  In that case, passing `nothing` signals that we don't need to go through the extra work of computing that Hessian.

**Comment by JockLawrie** [comment]
Ah ok, makes sense. Thanks heaps for the explanation, much appreciated,
most helpful.
