### ISSUE TITLE
Proposal: Optionally Disabling Optimizer's Printed Output

### ISSUE THREAD

**Issue by amgawishx** [JuliaNLSolvers/Optim.jl#990]
When someone uses the optimizer for any optimization, they get a full printed output with the results like the following:
```
Results of Optimization Algorithm
 * Algorithm: Brent's Method
 * Search Interval: [-2.000000, 1.000000]
 * Minimizer: -7.500000e-01
 * Minimum: -1.250000e-01
 * Iterations: 7
 * Convergence: max(|x - x_upper|, |x - x_lower|) <= 2*(1.5e-08*|x|+2.2e-16): true
 * Objective Function Calls: 8
```
Taken from the example on minimizing an univariate function on a bounded interval provided in the documentation, forcing the printed output onto the programmer can cause two issues:

1- Overhead; One might write a program for control on some delicate process where he needs at some point to optimize certain function(s) several times in a certain time window, forcing the printing step might cause lag in the program and reduce uncontrollable errors and slow execution. My opinion this goes strongly against Julia fancying itself in speed.

2- Uncontrolled IO Operations; A program where there is a lot of other printed output and only a single section of the optimization results is needed is simply not possible because the forced printing will clutter the console window.

I am aware that are workarounds like: 
```
redirect_stdout(devnull) do
    # code here
end
```
But that's doesn't solve issue no. 1 and possibly the solution itself can cause overhead, also it is just not pretty.
Simply adding a keyword option like: `print_output=true` that disables the printing to `stdout` when set to `false` will fix the issue without losing backward compatibility nor introducing any unpredictable behavior.

**Comment by johnmyleswhite** [comment]
This printing only happens in the REPL if the optimizer object is the result of evaluating a top-level expression, no?
